// WARNING: Please don't edit this file. It was generated by C++/Win32 v0.0.0.1

#ifndef WIN32_Windows_Win32_WindowsStationsAndDesktops_2_H
#define WIN32_Windows_Win32_WindowsStationsAndDesktops_2_H
#include "win32/impl/Windows.Win32.WindowsStationsAndDesktops.1.h"
#include "win32/impl/complex_interfaces.h"
#pragma region abi_methods
extern "C"
{
    win32::Windows::Win32::WindowsStationsAndDesktops::HDESK __stdcall WIN32_IMPL_CreateDesktopA(int8_t* lpszDesktop, int8_t* lpszDevice, win32::Windows::Win32::Xps::DEVMODEA* pDevmode, uint32_t dwFlags, uint32_t dwDesiredAccess, win32::Windows::Win32::SystemServices::SECURITY_ATTRIBUTES* lpsa) noexcept;
    win32::Windows::Win32::WindowsStationsAndDesktops::HDESK __stdcall WIN32_IMPL_CreateDesktopW(uint16_t* lpszDesktop, uint16_t* lpszDevice, win32::Windows::Win32::DisplayDevices::DEVMODEW* pDevmode, uint32_t dwFlags, uint32_t dwDesiredAccess, win32::Windows::Win32::SystemServices::SECURITY_ATTRIBUTES* lpsa) noexcept;
    win32::Windows::Win32::WindowsStationsAndDesktops::HDESK __stdcall WIN32_IMPL_CreateDesktopExA(int8_t* lpszDesktop, int8_t* lpszDevice, win32::Windows::Win32::Xps::DEVMODEA* pDevmode, uint32_t dwFlags, uint32_t dwDesiredAccess, win32::Windows::Win32::SystemServices::SECURITY_ATTRIBUTES* lpsa, uint32_t ulHeapSize, void* pvoid) noexcept;
    win32::Windows::Win32::WindowsStationsAndDesktops::HDESK __stdcall WIN32_IMPL_CreateDesktopExW(uint16_t* lpszDesktop, uint16_t* lpszDevice, win32::Windows::Win32::DisplayDevices::DEVMODEW* pDevmode, uint32_t dwFlags, uint32_t dwDesiredAccess, win32::Windows::Win32::SystemServices::SECURITY_ATTRIBUTES* lpsa, uint32_t ulHeapSize, void* pvoid) noexcept;
    win32::Windows::Win32::WindowsStationsAndDesktops::HDESK __stdcall WIN32_IMPL_OpenDesktopA(int8_t* lpszDesktop, uint32_t dwFlags, win32::Windows::Win32::SystemServices::BOOL fInherit, uint32_t dwDesiredAccess) noexcept;
    win32::Windows::Win32::WindowsStationsAndDesktops::HDESK __stdcall WIN32_IMPL_OpenDesktopW(uint16_t* lpszDesktop, uint32_t dwFlags, win32::Windows::Win32::SystemServices::BOOL fInherit, uint32_t dwDesiredAccess) noexcept;
    win32::Windows::Win32::WindowsStationsAndDesktops::HDESK __stdcall WIN32_IMPL_OpenInputDesktop(uint32_t dwFlags, win32::Windows::Win32::SystemServices::BOOL fInherit, uint32_t dwDesiredAccess) noexcept;
    win32::Windows::Win32::SystemServices::BOOL __stdcall WIN32_IMPL_EnumDesktopsA(intptr_t hwinsta, win32::Windows::Win32::MenusAndResources::DESKTOPENUMPROCA* lpEnumFunc, win32::Windows::Win32::WindowsAndMessaging::LPARAM lParam) noexcept;
    win32::Windows::Win32::SystemServices::BOOL __stdcall WIN32_IMPL_EnumDesktopsW(intptr_t hwinsta, win32::Windows::Win32::MenusAndResources::DESKTOPENUMPROCW* lpEnumFunc, win32::Windows::Win32::WindowsAndMessaging::LPARAM lParam) noexcept;
    win32::Windows::Win32::SystemServices::BOOL __stdcall WIN32_IMPL_EnumDesktopWindows(win32::Windows::Win32::WindowsStationsAndDesktops::HDESK hDesktop, win32::Windows::Win32::MenusAndResources::WNDENUMPROC* lpfn, win32::Windows::Win32::WindowsAndMessaging::LPARAM lParam) noexcept;
    win32::Windows::Win32::SystemServices::BOOL __stdcall WIN32_IMPL_SwitchDesktop(win32::Windows::Win32::WindowsStationsAndDesktops::HDESK hDesktop) noexcept;
    win32::Windows::Win32::SystemServices::BOOL __stdcall WIN32_IMPL_SetThreadDesktop(win32::Windows::Win32::WindowsStationsAndDesktops::HDESK hDesktop) noexcept;
    win32::Windows::Win32::SystemServices::BOOL __stdcall WIN32_IMPL_CloseDesktop(win32::Windows::Win32::WindowsStationsAndDesktops::HDESK hDesktop) noexcept;
    win32::Windows::Win32::WindowsStationsAndDesktops::HDESK __stdcall WIN32_IMPL_GetThreadDesktop(uint32_t dwThreadId) noexcept;
    intptr_t __stdcall WIN32_IMPL_CreateWindowStationA(int8_t* lpwinsta, uint32_t dwFlags, uint32_t dwDesiredAccess, win32::Windows::Win32::SystemServices::SECURITY_ATTRIBUTES* lpsa) noexcept;
    intptr_t __stdcall WIN32_IMPL_CreateWindowStationW(uint16_t* lpwinsta, uint32_t dwFlags, uint32_t dwDesiredAccess, win32::Windows::Win32::SystemServices::SECURITY_ATTRIBUTES* lpsa) noexcept;
    intptr_t __stdcall WIN32_IMPL_OpenWindowStationA(int8_t* lpszWinSta, win32::Windows::Win32::SystemServices::BOOL fInherit, uint32_t dwDesiredAccess) noexcept;
    intptr_t __stdcall WIN32_IMPL_OpenWindowStationW(uint16_t* lpszWinSta, win32::Windows::Win32::SystemServices::BOOL fInherit, uint32_t dwDesiredAccess) noexcept;
    win32::Windows::Win32::SystemServices::BOOL __stdcall WIN32_IMPL_EnumWindowStationsA(win32::Windows::Win32::MenusAndResources::WINSTAENUMPROCA* lpEnumFunc, win32::Windows::Win32::WindowsAndMessaging::LPARAM lParam) noexcept;
    win32::Windows::Win32::SystemServices::BOOL __stdcall WIN32_IMPL_EnumWindowStationsW(win32::Windows::Win32::MenusAndResources::WINSTAENUMPROCW* lpEnumFunc, win32::Windows::Win32::WindowsAndMessaging::LPARAM lParam) noexcept;
    win32::Windows::Win32::SystemServices::BOOL __stdcall WIN32_IMPL_CloseWindowStation(intptr_t hWinSta) noexcept;
    win32::Windows::Win32::SystemServices::BOOL __stdcall WIN32_IMPL_SetProcessWindowStation(intptr_t hWinSta) noexcept;
    intptr_t __stdcall WIN32_IMPL_GetProcessWindowStation() noexcept;
    win32::Windows::Win32::SystemServices::BOOL __stdcall WIN32_IMPL_GetUserObjectInformationA(win32::Windows::Win32::SystemServices::HANDLE hObj, int32_t nIndex, void* pvInfo, uint32_t nLength, uint32_t* lpnLengthNeeded) noexcept;
    win32::Windows::Win32::SystemServices::BOOL __stdcall WIN32_IMPL_GetUserObjectInformationW(win32::Windows::Win32::SystemServices::HANDLE hObj, int32_t nIndex, void* pvInfo, uint32_t nLength, uint32_t* lpnLengthNeeded) noexcept;
    win32::Windows::Win32::SystemServices::BOOL __stdcall WIN32_IMPL_SetUserObjectInformationA(win32::Windows::Win32::SystemServices::HANDLE hObj, int32_t nIndex, void* pvInfo, uint32_t nLength) noexcept;
    win32::Windows::Win32::SystemServices::BOOL __stdcall WIN32_IMPL_SetUserObjectInformationW(win32::Windows::Win32::SystemServices::HANDLE hObj, int32_t nIndex, void* pvInfo, uint32_t nLength) noexcept;
}
WIN32_IMPL_LINK(CreateDesktopA, 24)
WIN32_IMPL_LINK(CreateDesktopW, 24)
WIN32_IMPL_LINK(CreateDesktopExA, 32)
WIN32_IMPL_LINK(CreateDesktopExW, 32)
WIN32_IMPL_LINK(OpenDesktopA, 16)
WIN32_IMPL_LINK(OpenDesktopW, 16)
WIN32_IMPL_LINK(OpenInputDesktop, 12)
WIN32_IMPL_LINK(EnumDesktopsA, 12)
WIN32_IMPL_LINK(EnumDesktopsW, 12)
WIN32_IMPL_LINK(EnumDesktopWindows, 12)
WIN32_IMPL_LINK(SwitchDesktop, 4)
WIN32_IMPL_LINK(SetThreadDesktop, 4)
WIN32_IMPL_LINK(CloseDesktop, 4)
WIN32_IMPL_LINK(GetThreadDesktop, 4)
WIN32_IMPL_LINK(CreateWindowStationA, 16)
WIN32_IMPL_LINK(CreateWindowStationW, 16)
WIN32_IMPL_LINK(OpenWindowStationA, 12)
WIN32_IMPL_LINK(OpenWindowStationW, 12)
WIN32_IMPL_LINK(EnumWindowStationsA, 8)
WIN32_IMPL_LINK(EnumWindowStationsW, 8)
WIN32_IMPL_LINK(CloseWindowStation, 4)
WIN32_IMPL_LINK(SetProcessWindowStation, 4)
WIN32_IMPL_LINK(GetProcessWindowStation, 0)
WIN32_IMPL_LINK(GetUserObjectInformationA, 20)
WIN32_IMPL_LINK(GetUserObjectInformationW, 20)
WIN32_IMPL_LINK(SetUserObjectInformationA, 16)
WIN32_IMPL_LINK(SetUserObjectInformationW, 16)

#pragma endregion abi_methods

#endif
