// WARNING: Please don't edit this file. It was generated by C++/Win32 v0.0.0.1

#ifndef WIN32_Windows_Win32_Direct3D12_2_H
#define WIN32_Windows_Win32_Direct3D12_2_H
#include "win32/impl/Windows.Win32.Direct3D12.1.h"
#include "win32/impl/complex_interfaces.h"
#pragma region abi_methods
extern "C"
{
    int32_t __stdcall WIN32_IMPL_D3D12SerializeRootSignature(win32::Windows::Win32::Direct3D12::D3D12_ROOT_SIGNATURE_DESC* pRootSignature, win32::Windows::Win32::Direct3D12::D3D_ROOT_SIGNATURE_VERSION Version, win32::Windows::Win32::Direct3D11::ID3DBlob** ppBlob, win32::Windows::Win32::Direct3D11::ID3DBlob** ppErrorBlob) noexcept;
    int32_t __stdcall WIN32_IMPL_D3D12CreateRootSignatureDeserializer(void* pSrcData, size_t SrcDataSizeInBytes, ::win32::guid* pRootSignatureDeserializerInterface, void** ppRootSignatureDeserializer) noexcept;
    int32_t __stdcall WIN32_IMPL_D3D12SerializeVersionedRootSignature(win32::Windows::Win32::Direct3D12::D3D12_VERSIONED_ROOT_SIGNATURE_DESC* pRootSignature, win32::Windows::Win32::Direct3D11::ID3DBlob** ppBlob, win32::Windows::Win32::Direct3D11::ID3DBlob** ppErrorBlob) noexcept;
    int32_t __stdcall WIN32_IMPL_D3D12CreateVersionedRootSignatureDeserializer(void* pSrcData, size_t SrcDataSizeInBytes, ::win32::guid* pRootSignatureDeserializerInterface, void** ppRootSignatureDeserializer) noexcept;
    int32_t __stdcall WIN32_IMPL_D3D12CreateDevice(win32::Windows::Win32::Com::IUnknown* pAdapter, win32::Windows::Win32::Direct3D11::D3D_FEATURE_LEVEL MinimumFeatureLevel, ::win32::guid* riid, void** ppDevice) noexcept;
    int32_t __stdcall WIN32_IMPL_D3D12GetDebugInterface(::win32::guid* riid, void** ppvDebug) noexcept;
    int32_t __stdcall WIN32_IMPL_D3D12EnableExperimentalFeatures(uint32_t NumFeatures, ::win32::guid* pIIDs, void* pConfigurationStructs, uint32_t* pConfigurationStructSizes) noexcept;
    int32_t __stdcall WIN32_IMPL_D3D11On12CreateDevice(win32::Windows::Win32::Com::IUnknown* pDevice, uint32_t Flags, win32::Windows::Win32::Direct3D11::D3D_FEATURE_LEVEL* pFeatureLevels, uint32_t FeatureLevels, win32::Windows::Win32::Com::IUnknown** ppCommandQueues, uint32_t NumQueues, uint32_t NodeMask, win32::Windows::Win32::Direct3D11::ID3D11Device** ppDevice, win32::Windows::Win32::Direct3D11::ID3D11DeviceContext** ppImmediateContext, win32::Windows::Win32::Direct3D11::D3D_FEATURE_LEVEL* pChosenFeatureLevel) noexcept;
}
WIN32_IMPL_LINK(D3D12SerializeRootSignature, 16)
WIN32_IMPL_LINK(D3D12CreateRootSignatureDeserializer, 16)
WIN32_IMPL_LINK(D3D12SerializeVersionedRootSignature, 12)
WIN32_IMPL_LINK(D3D12CreateVersionedRootSignatureDeserializer, 16)
WIN32_IMPL_LINK(D3D12CreateDevice, 16)
WIN32_IMPL_LINK(D3D12GetDebugInterface, 8)
WIN32_IMPL_LINK(D3D12EnableExperimentalFeatures, 16)
WIN32_IMPL_LINK(D3D11On12CreateDevice, 40)

#pragma endregion abi_methods

#endif
