// WARNING: Please don't edit this file. It was generated by C++/Win32 v0.0.0.1

#ifndef WIN32_Windows_Win32_IndexServer_2_H
#define WIN32_Windows_Win32_IndexServer_2_H
#include "win32/impl/Windows.Win32.IndexServer.1.h"
#include "win32/impl/complex_interfaces.h"
#pragma region abi_methods
extern "C"
{
    int32_t __stdcall WIN32_IMPL_LoadIFilter(uint16_t* pwcsPath, win32::Windows::Win32::Com::IUnknown* pUnkOuter, void** ppIUnk) noexcept;
    int32_t __stdcall WIN32_IMPL_LoadIFilterEx(uint16_t* pwcsPath, uint32_t dwFlags, ::win32::guid* riid, void** ppIUnk) noexcept;
    int32_t __stdcall WIN32_IMPL_BindIFilterFromStorage(win32::Windows::Win32::StructuredStorage::IStorage* pStg, win32::Windows::Win32::Com::IUnknown* pUnkOuter, void** ppIUnk) noexcept;
    int32_t __stdcall WIN32_IMPL_BindIFilterFromStream(win32::Windows::Win32::StructuredStorage::IStream* pStm, win32::Windows::Win32::Com::IUnknown* pUnkOuter, void** ppIUnk) noexcept;
}
WIN32_IMPL_LINK(LoadIFilter, 12)
WIN32_IMPL_LINK(LoadIFilterEx, 16)
WIN32_IMPL_LINK(BindIFilterFromStorage, 12)
WIN32_IMPL_LINK(BindIFilterFromStream, 12)

#pragma endregion abi_methods

#endif
