// WARNING: Please don't edit this file. It was generated by C++/Win32 v0.0.0.1

#ifndef WIN32_Windows_Win32_NetShell_2_H
#define WIN32_Windows_Win32_NetShell_2_H
#include "win32/impl/Windows.Win32.NetShell.1.h"
#include "win32/impl/complex_interfaces.h"
#pragma region abi_methods
extern "C"
{
    uint32_t __stdcall WIN32_IMPL_MatchEnumTag(win32::Windows::Win32::SystemServices::HANDLE hModule, uint16_t* pwcArg, uint32_t dwNumArg, win32::Windows::Win32::NetShell::TOKEN_VALUE* pEnumTable, uint32_t* pdwValue) noexcept;
    win32::Windows::Win32::SystemServices::BOOL __stdcall WIN32_IMPL_MatchToken(uint16_t* pwszUserToken, uint16_t* pwszCmdToken) noexcept;
    uint32_t __stdcall WIN32_IMPL_PreprocessCommand(win32::Windows::Win32::SystemServices::HANDLE hModule, uint16_t** ppwcArguments, uint32_t dwCurrentIndex, uint32_t dwArgCount, win32::Windows::Win32::NetShell::TAG_TYPE* pttTags, uint32_t dwTagCount, uint32_t dwMinArgs, uint32_t dwMaxArgs, uint32_t* pdwTagType) noexcept;
    uint32_t __stdcall WIN32_IMPL_PrintError(win32::Windows::Win32::SystemServices::HANDLE hModule, uint32_t dwErrId) noexcept;
    uint32_t __stdcall WIN32_IMPL_PrintMessageFromModule(win32::Windows::Win32::SystemServices::HANDLE hModule, uint32_t dwMsgId) noexcept;
    uint32_t __stdcall WIN32_IMPL_PrintMessage(uint16_t* pwszFormat) noexcept;
    uint32_t __stdcall WIN32_IMPL_RegisterContext(win32::Windows::Win32::NetShell::NS_CONTEXT_ATTRIBUTES* pChildContext) noexcept;
    uint32_t __stdcall WIN32_IMPL_RegisterHelper(::win32::guid* pguidParentContext, win32::Windows::Win32::NetShell::NS_HELPER_ATTRIBUTES* pfnRegisterSubContext) noexcept;
}
WIN32_IMPL_LINK(MatchEnumTag, 20)
WIN32_IMPL_LINK(MatchToken, 8)
WIN32_IMPL_LINK(PreprocessCommand, 36)
WIN32_IMPL_LINK(PrintError, 8)
WIN32_IMPL_LINK(PrintMessageFromModule, 8)
WIN32_IMPL_LINK(PrintMessage, 4)
WIN32_IMPL_LINK(RegisterContext, 4)
WIN32_IMPL_LINK(RegisterHelper, 8)

#pragma endregion abi_methods

#endif
