// WARNING: Please don't edit this file. It was generated by C++/Win32 v0.0.0.1

#ifndef WIN32_Windows_Win32_WindowsFiltering_2_H
#define WIN32_Windows_Win32_WindowsFiltering_2_H
#include "win32/impl/Windows.Win32.WindowsFiltering.1.h"
#include "win32/impl/complex_interfaces.h"
#pragma region abi_methods
extern "C"
{
    void __stdcall WIN32_IMPL_FwpmFreeMemory0(void** p) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmEngineOpen0(uint16_t* serverName, uint32_t authnService, win32::Windows::Win32::Security::SEC_WINNT_AUTH_IDENTITY_W* authIdentity, win32::Windows::Win32::WindowsFiltering::FWPM_SESSION0* session, win32::Windows::Win32::SystemServices::HANDLE* engineHandle) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmEngineClose0(win32::Windows::Win32::SystemServices::HANDLE engineHandle) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmEngineGetOption0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::WindowsFiltering::FWPM_ENGINE_OPTION option, win32::Windows::Win32::WindowsFiltering::FWP_VALUE0** value) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmEngineSetOption0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::WindowsFiltering::FWPM_ENGINE_OPTION option, win32::Windows::Win32::WindowsFiltering::FWP_VALUE0* newValue) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmEngineGetSecurityInfo0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, uint32_t securityInfo, void** sidOwner, void** sidGroup, win32::Windows::Win32::Security::ACL** dacl, win32::Windows::Win32::Security::ACL** sacl, void** securityDescriptor) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmEngineSetSecurityInfo0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, uint32_t securityInfo, win32::Windows::Win32::Security::SID* sidOwner, win32::Windows::Win32::Security::SID* sidGroup, win32::Windows::Win32::Security::ACL* dacl, win32::Windows::Win32::Security::ACL* sacl) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmSessionCreateEnumHandle0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::WindowsFiltering::FWPM_SESSION_ENUM_TEMPLATE0* enumTemplate, win32::Windows::Win32::SystemServices::HANDLE* enumHandle) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmSessionEnum0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::SystemServices::HANDLE enumHandle, uint32_t numEntriesRequested, win32::Windows::Win32::WindowsFiltering::FWPM_SESSION0*** entries, uint32_t* numEntriesReturned) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmSessionDestroyEnumHandle0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::SystemServices::HANDLE enumHandle) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmTransactionBegin0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, uint32_t flags) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmTransactionCommit0(win32::Windows::Win32::SystemServices::HANDLE engineHandle) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmTransactionAbort0(win32::Windows::Win32::SystemServices::HANDLE engineHandle) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmProviderAdd0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::WindowsFiltering::FWPM_PROVIDER0* provider, void* sd) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmProviderDeleteByKey0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, ::win32::guid* key) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmProviderGetByKey0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, ::win32::guid* key, win32::Windows::Win32::WindowsFiltering::FWPM_PROVIDER0** provider) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmProviderCreateEnumHandle0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::WindowsFiltering::FWPM_PROVIDER_ENUM_TEMPLATE0* enumTemplate, win32::Windows::Win32::SystemServices::HANDLE* enumHandle) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmProviderEnum0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::SystemServices::HANDLE enumHandle, uint32_t numEntriesRequested, win32::Windows::Win32::WindowsFiltering::FWPM_PROVIDER0*** entries, uint32_t* numEntriesReturned) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmProviderDestroyEnumHandle0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::SystemServices::HANDLE enumHandle) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmProviderGetSecurityInfoByKey0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, ::win32::guid* key, uint32_t securityInfo, void** sidOwner, void** sidGroup, win32::Windows::Win32::Security::ACL** dacl, win32::Windows::Win32::Security::ACL** sacl, void** securityDescriptor) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmProviderSetSecurityInfoByKey0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, ::win32::guid* key, uint32_t securityInfo, win32::Windows::Win32::Security::SID* sidOwner, win32::Windows::Win32::Security::SID* sidGroup, win32::Windows::Win32::Security::ACL* dacl, win32::Windows::Win32::Security::ACL* sacl) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmProviderSubscribeChanges0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::WindowsFiltering::FWPM_PROVIDER_SUBSCRIPTION0* subscription, win32::Windows::Win32::WindowsFiltering::FWPM_PROVIDER_CHANGE_CALLBACK0* callback, void* context, win32::Windows::Win32::SystemServices::HANDLE* changeHandle) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmProviderUnsubscribeChanges0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::SystemServices::HANDLE changeHandle) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmProviderSubscriptionsGet0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::WindowsFiltering::FWPM_PROVIDER_SUBSCRIPTION0*** entries, uint32_t* numEntries) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmProviderContextAdd0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::WindowsFiltering::FWPM_PROVIDER_CONTEXT0* providerContext, void* sd, uint64_t* id) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmProviderContextAdd1(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::WindowsFiltering::FWPM_PROVIDER_CONTEXT1* providerContext, void* sd, uint64_t* id) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmProviderContextAdd2(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::WindowsFiltering::FWPM_PROVIDER_CONTEXT2* providerContext, void* sd, uint64_t* id) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmProviderContextAdd3(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::WindowsFiltering::FWPM_PROVIDER_CONTEXT3_* providerContext, void* sd, uint64_t* id) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmProviderContextDeleteById0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, uint64_t id) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmProviderContextDeleteByKey0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, ::win32::guid* key) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmProviderContextGetById0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, uint64_t id, win32::Windows::Win32::WindowsFiltering::FWPM_PROVIDER_CONTEXT0** providerContext) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmProviderContextGetById1(win32::Windows::Win32::SystemServices::HANDLE engineHandle, uint64_t id, win32::Windows::Win32::WindowsFiltering::FWPM_PROVIDER_CONTEXT1** providerContext) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmProviderContextGetById2(win32::Windows::Win32::SystemServices::HANDLE engineHandle, uint64_t id, win32::Windows::Win32::WindowsFiltering::FWPM_PROVIDER_CONTEXT2** providerContext) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmProviderContextGetById3(win32::Windows::Win32::SystemServices::HANDLE engineHandle, uint64_t id, win32::Windows::Win32::WindowsFiltering::FWPM_PROVIDER_CONTEXT3_** providerContext) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmProviderContextGetByKey0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, ::win32::guid* key, win32::Windows::Win32::WindowsFiltering::FWPM_PROVIDER_CONTEXT0** providerContext) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmProviderContextGetByKey1(win32::Windows::Win32::SystemServices::HANDLE engineHandle, ::win32::guid* key, win32::Windows::Win32::WindowsFiltering::FWPM_PROVIDER_CONTEXT1** providerContext) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmProviderContextGetByKey2(win32::Windows::Win32::SystemServices::HANDLE engineHandle, ::win32::guid* key, win32::Windows::Win32::WindowsFiltering::FWPM_PROVIDER_CONTEXT2** providerContext) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmProviderContextGetByKey3(win32::Windows::Win32::SystemServices::HANDLE engineHandle, ::win32::guid* key, win32::Windows::Win32::WindowsFiltering::FWPM_PROVIDER_CONTEXT3_** providerContext) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmProviderContextCreateEnumHandle0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::WindowsFiltering::FWPM_PROVIDER_CONTEXT_ENUM_TEMPLATE0* enumTemplate, win32::Windows::Win32::SystemServices::HANDLE* enumHandle) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmProviderContextEnum0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::SystemServices::HANDLE enumHandle, uint32_t numEntriesRequested, win32::Windows::Win32::WindowsFiltering::FWPM_PROVIDER_CONTEXT0*** entries, uint32_t* numEntriesReturned) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmProviderContextEnum1(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::SystemServices::HANDLE enumHandle, uint32_t numEntriesRequested, win32::Windows::Win32::WindowsFiltering::FWPM_PROVIDER_CONTEXT1*** entries, uint32_t* numEntriesReturned) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmProviderContextEnum2(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::SystemServices::HANDLE enumHandle, uint32_t numEntriesRequested, win32::Windows::Win32::WindowsFiltering::FWPM_PROVIDER_CONTEXT2*** entries, uint32_t* numEntriesReturned) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmProviderContextEnum3(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::SystemServices::HANDLE enumHandle, uint32_t numEntriesRequested, win32::Windows::Win32::WindowsFiltering::FWPM_PROVIDER_CONTEXT3_*** entries, uint32_t* numEntriesReturned) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmProviderContextDestroyEnumHandle0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::SystemServices::HANDLE enumHandle) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmProviderContextGetSecurityInfoByKey0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, ::win32::guid* key, uint32_t securityInfo, void** sidOwner, void** sidGroup, win32::Windows::Win32::Security::ACL** dacl, win32::Windows::Win32::Security::ACL** sacl, void** securityDescriptor) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmProviderContextSetSecurityInfoByKey0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, ::win32::guid* key, uint32_t securityInfo, win32::Windows::Win32::Security::SID* sidOwner, win32::Windows::Win32::Security::SID* sidGroup, win32::Windows::Win32::Security::ACL* dacl, win32::Windows::Win32::Security::ACL* sacl) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmProviderContextSubscribeChanges0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::WindowsFiltering::FWPM_PROVIDER_CONTEXT_SUBSCRIPTION0* subscription, win32::Windows::Win32::WindowsFiltering::FWPM_PROVIDER_CONTEXT_CHANGE_CALLBACK0* callback, void* context, win32::Windows::Win32::SystemServices::HANDLE* changeHandle) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmProviderContextUnsubscribeChanges0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::SystemServices::HANDLE changeHandle) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmProviderContextSubscriptionsGet0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::WindowsFiltering::FWPM_PROVIDER_CONTEXT_SUBSCRIPTION0*** entries, uint32_t* numEntries) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmSubLayerAdd0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::WindowsFiltering::FWPM_SUBLAYER0* subLayer, void* sd) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmSubLayerDeleteByKey0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, ::win32::guid* key) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmSubLayerGetByKey0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, ::win32::guid* key, win32::Windows::Win32::WindowsFiltering::FWPM_SUBLAYER0** subLayer) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmSubLayerCreateEnumHandle0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::WindowsFiltering::FWPM_SUBLAYER_ENUM_TEMPLATE0* enumTemplate, win32::Windows::Win32::SystemServices::HANDLE* enumHandle) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmSubLayerEnum0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::SystemServices::HANDLE enumHandle, uint32_t numEntriesRequested, win32::Windows::Win32::WindowsFiltering::FWPM_SUBLAYER0*** entries, uint32_t* numEntriesReturned) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmSubLayerDestroyEnumHandle0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::SystemServices::HANDLE enumHandle) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmSubLayerGetSecurityInfoByKey0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, ::win32::guid* key, uint32_t securityInfo, void** sidOwner, void** sidGroup, win32::Windows::Win32::Security::ACL** dacl, win32::Windows::Win32::Security::ACL** sacl, void** securityDescriptor) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmSubLayerSetSecurityInfoByKey0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, ::win32::guid* key, uint32_t securityInfo, win32::Windows::Win32::Security::SID* sidOwner, win32::Windows::Win32::Security::SID* sidGroup, win32::Windows::Win32::Security::ACL* dacl, win32::Windows::Win32::Security::ACL* sacl) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmSubLayerSubscribeChanges0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::WindowsFiltering::FWPM_SUBLAYER_SUBSCRIPTION0* subscription, win32::Windows::Win32::WindowsFiltering::FWPM_SUBLAYER_CHANGE_CALLBACK0* callback, void* context, win32::Windows::Win32::SystemServices::HANDLE* changeHandle) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmSubLayerUnsubscribeChanges0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::SystemServices::HANDLE changeHandle) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmSubLayerSubscriptionsGet0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::WindowsFiltering::FWPM_SUBLAYER_SUBSCRIPTION0*** entries, uint32_t* numEntries) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmLayerGetById0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, uint16_t id, win32::Windows::Win32::WindowsFiltering::FWPM_LAYER0** layer) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmLayerGetByKey0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, ::win32::guid* key, win32::Windows::Win32::WindowsFiltering::FWPM_LAYER0** layer) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmLayerCreateEnumHandle0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::WindowsFiltering::FWPM_LAYER_ENUM_TEMPLATE0* enumTemplate, win32::Windows::Win32::SystemServices::HANDLE* enumHandle) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmLayerEnum0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::SystemServices::HANDLE enumHandle, uint32_t numEntriesRequested, win32::Windows::Win32::WindowsFiltering::FWPM_LAYER0*** entries, uint32_t* numEntriesReturned) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmLayerDestroyEnumHandle0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::SystemServices::HANDLE enumHandle) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmLayerGetSecurityInfoByKey0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, ::win32::guid* key, uint32_t securityInfo, void** sidOwner, void** sidGroup, win32::Windows::Win32::Security::ACL** dacl, win32::Windows::Win32::Security::ACL** sacl, void** securityDescriptor) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmLayerSetSecurityInfoByKey0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, ::win32::guid* key, uint32_t securityInfo, win32::Windows::Win32::Security::SID* sidOwner, win32::Windows::Win32::Security::SID* sidGroup, win32::Windows::Win32::Security::ACL* dacl, win32::Windows::Win32::Security::ACL* sacl) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmCalloutAdd0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::WindowsFiltering::FWPM_CALLOUT0* callout, void* sd, uint32_t* id) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmCalloutDeleteById0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, uint32_t id) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmCalloutDeleteByKey0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, ::win32::guid* key) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmCalloutGetById0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, uint32_t id, win32::Windows::Win32::WindowsFiltering::FWPM_CALLOUT0** callout) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmCalloutGetByKey0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, ::win32::guid* key, win32::Windows::Win32::WindowsFiltering::FWPM_CALLOUT0** callout) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmCalloutCreateEnumHandle0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::WindowsFiltering::FWPM_CALLOUT_ENUM_TEMPLATE0* enumTemplate, win32::Windows::Win32::SystemServices::HANDLE* enumHandle) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmCalloutEnum0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::SystemServices::HANDLE enumHandle, uint32_t numEntriesRequested, win32::Windows::Win32::WindowsFiltering::FWPM_CALLOUT0*** entries, uint32_t* numEntriesReturned) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmCalloutDestroyEnumHandle0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::SystemServices::HANDLE enumHandle) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmCalloutGetSecurityInfoByKey0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, ::win32::guid* key, uint32_t securityInfo, void** sidOwner, void** sidGroup, win32::Windows::Win32::Security::ACL** dacl, win32::Windows::Win32::Security::ACL** sacl, void** securityDescriptor) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmCalloutSetSecurityInfoByKey0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, ::win32::guid* key, uint32_t securityInfo, win32::Windows::Win32::Security::SID* sidOwner, win32::Windows::Win32::Security::SID* sidGroup, win32::Windows::Win32::Security::ACL* dacl, win32::Windows::Win32::Security::ACL* sacl) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmCalloutSubscribeChanges0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::WindowsFiltering::FWPM_CALLOUT_SUBSCRIPTION0* subscription, win32::Windows::Win32::WindowsFiltering::FWPM_CALLOUT_CHANGE_CALLBACK0* callback, void* context, win32::Windows::Win32::SystemServices::HANDLE* changeHandle) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmCalloutUnsubscribeChanges0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::SystemServices::HANDLE changeHandle) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmCalloutSubscriptionsGet0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::WindowsFiltering::FWPM_CALLOUT_SUBSCRIPTION0*** entries, uint32_t* numEntries) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmFilterAdd0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::WindowsFiltering::FWPM_FILTER0* filter, void* sd, uint64_t* id) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmFilterDeleteById0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, uint64_t id) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmFilterDeleteByKey0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, ::win32::guid* key) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmFilterGetById0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, uint64_t id, win32::Windows::Win32::WindowsFiltering::FWPM_FILTER0** filter) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmFilterGetByKey0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, ::win32::guid* key, win32::Windows::Win32::WindowsFiltering::FWPM_FILTER0** filter) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmFilterCreateEnumHandle0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::WindowsFiltering::FWPM_FILTER_ENUM_TEMPLATE0* enumTemplate, win32::Windows::Win32::SystemServices::HANDLE* enumHandle) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmFilterEnum0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::SystemServices::HANDLE enumHandle, uint32_t numEntriesRequested, win32::Windows::Win32::WindowsFiltering::FWPM_FILTER0*** entries, uint32_t* numEntriesReturned) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmFilterDestroyEnumHandle0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::SystemServices::HANDLE enumHandle) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmFilterGetSecurityInfoByKey0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, ::win32::guid* key, uint32_t securityInfo, void** sidOwner, void** sidGroup, win32::Windows::Win32::Security::ACL** dacl, win32::Windows::Win32::Security::ACL** sacl, void** securityDescriptor) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmFilterSetSecurityInfoByKey0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, ::win32::guid* key, uint32_t securityInfo, win32::Windows::Win32::Security::SID* sidOwner, win32::Windows::Win32::Security::SID* sidGroup, win32::Windows::Win32::Security::ACL* dacl, win32::Windows::Win32::Security::ACL* sacl) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmFilterSubscribeChanges0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::WindowsFiltering::FWPM_FILTER_SUBSCRIPTION0* subscription, win32::Windows::Win32::WindowsFiltering::FWPM_FILTER_CHANGE_CALLBACK0* callback, void* context, win32::Windows::Win32::SystemServices::HANDLE* changeHandle) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmFilterUnsubscribeChanges0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::SystemServices::HANDLE changeHandle) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmFilterSubscriptionsGet0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::WindowsFiltering::FWPM_FILTER_SUBSCRIPTION0*** entries, uint32_t* numEntries) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmGetAppIdFromFileName0(uint16_t* fileName, win32::Windows::Win32::WindowsFiltering::FWP_BYTE_BLOB** appId) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmBitmapIndexGet0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, ::win32::guid* fieldId, uint8_t* idx) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmBitmapIndexFree0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, ::win32::guid* fieldId, uint8_t* idx) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmIPsecTunnelAdd0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, uint32_t flags, win32::Windows::Win32::WindowsFiltering::FWPM_PROVIDER_CONTEXT0* mainModePolicy, win32::Windows::Win32::WindowsFiltering::FWPM_PROVIDER_CONTEXT0* tunnelPolicy, uint32_t numFilterConditions, win32::Windows::Win32::WindowsFiltering::FWPM_FILTER_CONDITION0* filterConditions, void* sd) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmIPsecTunnelAdd1(win32::Windows::Win32::SystemServices::HANDLE engineHandle, uint32_t flags, win32::Windows::Win32::WindowsFiltering::FWPM_PROVIDER_CONTEXT1* mainModePolicy, win32::Windows::Win32::WindowsFiltering::FWPM_PROVIDER_CONTEXT1* tunnelPolicy, uint32_t numFilterConditions, win32::Windows::Win32::WindowsFiltering::FWPM_FILTER_CONDITION0* filterConditions, ::win32::guid* keyModKey, void* sd) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmIPsecTunnelAdd2(win32::Windows::Win32::SystemServices::HANDLE engineHandle, uint32_t flags, win32::Windows::Win32::WindowsFiltering::FWPM_PROVIDER_CONTEXT2* mainModePolicy, win32::Windows::Win32::WindowsFiltering::FWPM_PROVIDER_CONTEXT2* tunnelPolicy, uint32_t numFilterConditions, win32::Windows::Win32::WindowsFiltering::FWPM_FILTER_CONDITION0* filterConditions, ::win32::guid* keyModKey, void* sd) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmIPsecTunnelAdd3(win32::Windows::Win32::SystemServices::HANDLE engineHandle, uint32_t flags, win32::Windows::Win32::WindowsFiltering::FWPM_PROVIDER_CONTEXT3_* mainModePolicy, win32::Windows::Win32::WindowsFiltering::FWPM_PROVIDER_CONTEXT3_* tunnelPolicy, uint32_t numFilterConditions, win32::Windows::Win32::WindowsFiltering::FWPM_FILTER_CONDITION0* filterConditions, ::win32::guid* keyModKey, void* sd) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmIPsecTunnelDeleteByKey0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, ::win32::guid* key) noexcept;
    uint32_t __stdcall WIN32_IMPL_IPsecGetStatistics0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::WindowsFiltering::IPSEC_STATISTICS0* ipsecStatistics) noexcept;
    uint32_t __stdcall WIN32_IMPL_IPsecGetStatistics1(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::WindowsFiltering::IPSEC_STATISTICS1* ipsecStatistics) noexcept;
    uint32_t __stdcall WIN32_IMPL_IPsecSaContextCreate0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::WindowsFiltering::IPSEC_TRAFFIC0* outboundTraffic, uint64_t* inboundFilterId, uint64_t* id) noexcept;
    uint32_t __stdcall WIN32_IMPL_IPsecSaContextCreate1(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::WindowsFiltering::IPSEC_TRAFFIC1* outboundTraffic, win32::Windows::Win32::WindowsFiltering::IPSEC_VIRTUAL_IF_TUNNEL_INFO0* virtualIfTunnelInfo, uint64_t* inboundFilterId, uint64_t* id) noexcept;
    uint32_t __stdcall WIN32_IMPL_IPsecSaContextDeleteById0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, uint64_t id) noexcept;
    uint32_t __stdcall WIN32_IMPL_IPsecSaContextGetById0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, uint64_t id, win32::Windows::Win32::WindowsFiltering::IPSEC_SA_CONTEXT0** saContext) noexcept;
    uint32_t __stdcall WIN32_IMPL_IPsecSaContextGetById1(win32::Windows::Win32::SystemServices::HANDLE engineHandle, uint64_t id, win32::Windows::Win32::WindowsFiltering::IPSEC_SA_CONTEXT1** saContext) noexcept;
    uint32_t __stdcall WIN32_IMPL_IPsecSaContextGetSpi0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, uint64_t id, win32::Windows::Win32::WindowsFiltering::IPSEC_GETSPI0* getSpi, uint32_t* inboundSpi) noexcept;
    uint32_t __stdcall WIN32_IMPL_IPsecSaContextGetSpi1(win32::Windows::Win32::SystemServices::HANDLE engineHandle, uint64_t id, win32::Windows::Win32::WindowsFiltering::IPSEC_GETSPI1* getSpi, uint32_t* inboundSpi) noexcept;
    uint32_t __stdcall WIN32_IMPL_IPsecSaContextSetSpi0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, uint64_t id, win32::Windows::Win32::WindowsFiltering::IPSEC_GETSPI1* getSpi, uint32_t inboundSpi) noexcept;
    uint32_t __stdcall WIN32_IMPL_IPsecSaContextAddInbound0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, uint64_t id, win32::Windows::Win32::WindowsFiltering::IPSEC_SA_BUNDLE0* inboundBundle) noexcept;
    uint32_t __stdcall WIN32_IMPL_IPsecSaContextAddOutbound0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, uint64_t id, win32::Windows::Win32::WindowsFiltering::IPSEC_SA_BUNDLE0* outboundBundle) noexcept;
    uint32_t __stdcall WIN32_IMPL_IPsecSaContextAddInbound1(win32::Windows::Win32::SystemServices::HANDLE engineHandle, uint64_t id, win32::Windows::Win32::WindowsFiltering::IPSEC_SA_BUNDLE1* inboundBundle) noexcept;
    uint32_t __stdcall WIN32_IMPL_IPsecSaContextAddOutbound1(win32::Windows::Win32::SystemServices::HANDLE engineHandle, uint64_t id, win32::Windows::Win32::WindowsFiltering::IPSEC_SA_BUNDLE1* outboundBundle) noexcept;
    uint32_t __stdcall WIN32_IMPL_IPsecSaContextExpire0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, uint64_t id) noexcept;
    uint32_t __stdcall WIN32_IMPL_IPsecSaContextUpdate0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, uint64_t flags, win32::Windows::Win32::WindowsFiltering::IPSEC_SA_CONTEXT1* newValues) noexcept;
    uint32_t __stdcall WIN32_IMPL_IPsecSaContextCreateEnumHandle0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::WindowsFiltering::IPSEC_SA_CONTEXT_ENUM_TEMPLATE0* enumTemplate, win32::Windows::Win32::SystemServices::HANDLE* enumHandle) noexcept;
    uint32_t __stdcall WIN32_IMPL_IPsecSaContextEnum0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::SystemServices::HANDLE enumHandle, uint32_t numEntriesRequested, win32::Windows::Win32::WindowsFiltering::IPSEC_SA_CONTEXT0*** entries, uint32_t* numEntriesReturned) noexcept;
    uint32_t __stdcall WIN32_IMPL_IPsecSaContextEnum1(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::SystemServices::HANDLE enumHandle, uint32_t numEntriesRequested, win32::Windows::Win32::WindowsFiltering::IPSEC_SA_CONTEXT1*** entries, uint32_t* numEntriesReturned) noexcept;
    uint32_t __stdcall WIN32_IMPL_IPsecSaContextDestroyEnumHandle0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::SystemServices::HANDLE enumHandle) noexcept;
    uint32_t __stdcall WIN32_IMPL_IPsecSaContextSubscribe0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::WindowsFiltering::IPSEC_SA_CONTEXT_SUBSCRIPTION0* subscription, win32::Windows::Win32::WindowsFiltering::IPSEC_SA_CONTEXT_CALLBACK0* callback, void* context, win32::Windows::Win32::SystemServices::HANDLE* eventsHandle) noexcept;
    uint32_t __stdcall WIN32_IMPL_IPsecSaContextUnsubscribe0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::SystemServices::HANDLE eventsHandle) noexcept;
    uint32_t __stdcall WIN32_IMPL_IPsecSaContextSubscriptionsGet0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::WindowsFiltering::IPSEC_SA_CONTEXT_SUBSCRIPTION0*** entries, uint32_t* numEntries) noexcept;
    uint32_t __stdcall WIN32_IMPL_IPsecSaCreateEnumHandle0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::WindowsFiltering::IPSEC_SA_ENUM_TEMPLATE0* enumTemplate, win32::Windows::Win32::SystemServices::HANDLE* enumHandle) noexcept;
    uint32_t __stdcall WIN32_IMPL_IPsecSaEnum0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::SystemServices::HANDLE enumHandle, uint32_t numEntriesRequested, win32::Windows::Win32::WindowsFiltering::IPSEC_SA_DETAILS0*** entries, uint32_t* numEntriesReturned) noexcept;
    uint32_t __stdcall WIN32_IMPL_IPsecSaEnum1(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::SystemServices::HANDLE enumHandle, uint32_t numEntriesRequested, win32::Windows::Win32::WindowsFiltering::IPSEC_SA_DETAILS1*** entries, uint32_t* numEntriesReturned) noexcept;
    uint32_t __stdcall WIN32_IMPL_IPsecSaDestroyEnumHandle0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::SystemServices::HANDLE enumHandle) noexcept;
    uint32_t __stdcall WIN32_IMPL_IPsecSaDbGetSecurityInfo0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, uint32_t securityInfo, void** sidOwner, void** sidGroup, win32::Windows::Win32::Security::ACL** dacl, win32::Windows::Win32::Security::ACL** sacl, void** securityDescriptor) noexcept;
    uint32_t __stdcall WIN32_IMPL_IPsecSaDbSetSecurityInfo0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, uint32_t securityInfo, win32::Windows::Win32::Security::SID* sidOwner, win32::Windows::Win32::Security::SID* sidGroup, win32::Windows::Win32::Security::ACL* dacl, win32::Windows::Win32::Security::ACL* sacl) noexcept;
    uint32_t __stdcall WIN32_IMPL_IPsecDospGetStatistics0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::WindowsFiltering::IPSEC_DOSP_STATISTICS0* idpStatistics) noexcept;
    uint32_t __stdcall WIN32_IMPL_IPsecDospStateCreateEnumHandle0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::WindowsFiltering::IPSEC_DOSP_STATE_ENUM_TEMPLATE0* enumTemplate, win32::Windows::Win32::SystemServices::HANDLE* enumHandle) noexcept;
    uint32_t __stdcall WIN32_IMPL_IPsecDospStateEnum0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::SystemServices::HANDLE enumHandle, uint32_t numEntriesRequested, win32::Windows::Win32::WindowsFiltering::IPSEC_DOSP_STATE0*** entries, uint32_t* numEntries) noexcept;
    uint32_t __stdcall WIN32_IMPL_IPsecDospStateDestroyEnumHandle0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::SystemServices::HANDLE enumHandle) noexcept;
    uint32_t __stdcall WIN32_IMPL_IPsecDospGetSecurityInfo0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, uint32_t securityInfo, void** sidOwner, void** sidGroup, win32::Windows::Win32::Security::ACL** dacl, win32::Windows::Win32::Security::ACL** sacl, void** securityDescriptor) noexcept;
    uint32_t __stdcall WIN32_IMPL_IPsecDospSetSecurityInfo0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, uint32_t securityInfo, win32::Windows::Win32::Security::SID* sidOwner, win32::Windows::Win32::Security::SID* sidGroup, win32::Windows::Win32::Security::ACL* dacl, win32::Windows::Win32::Security::ACL* sacl) noexcept;
    uint32_t __stdcall WIN32_IMPL_IPsecKeyManagerAddAndRegister0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::WindowsFiltering::IPSEC_KEY_MANAGER0* keyManager, win32::Windows::Win32::WindowsFiltering::IPSEC_KEY_MANAGER_CALLBACKS0* keyManagerCallbacks, win32::Windows::Win32::SystemServices::HANDLE* keyMgmtHandle) noexcept;
    uint32_t __stdcall WIN32_IMPL_IPsecKeyManagerUnregisterAndDelete0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::SystemServices::HANDLE keyMgmtHandle) noexcept;
    uint32_t __stdcall WIN32_IMPL_IPsecKeyManagersGet0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::WindowsFiltering::IPSEC_KEY_MANAGER0*** entries, uint32_t* numEntries) noexcept;
    uint32_t __stdcall WIN32_IMPL_IPsecKeyManagerGetSecurityInfoByKey0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, void* reserved, uint32_t securityInfo, void** sidOwner, void** sidGroup, win32::Windows::Win32::Security::ACL** dacl, win32::Windows::Win32::Security::ACL** sacl, void** securityDescriptor) noexcept;
    uint32_t __stdcall WIN32_IMPL_IPsecKeyManagerSetSecurityInfoByKey0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, void* reserved, uint32_t securityInfo, win32::Windows::Win32::Security::SID* sidOwner, win32::Windows::Win32::Security::SID* sidGroup, win32::Windows::Win32::Security::ACL* dacl, win32::Windows::Win32::Security::ACL* sacl) noexcept;
    uint32_t __stdcall WIN32_IMPL_IkeextGetStatistics0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::WindowsFiltering::IKEEXT_STATISTICS0* ikeextStatistics) noexcept;
    uint32_t __stdcall WIN32_IMPL_IkeextGetStatistics1(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::WindowsFiltering::IKEEXT_STATISTICS1* ikeextStatistics) noexcept;
    uint32_t __stdcall WIN32_IMPL_IkeextSaDeleteById0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, uint64_t id) noexcept;
    uint32_t __stdcall WIN32_IMPL_IkeextSaGetById0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, uint64_t id, win32::Windows::Win32::WindowsFiltering::IKEEXT_SA_DETAILS0** sa) noexcept;
    uint32_t __stdcall WIN32_IMPL_IkeextSaGetById1(win32::Windows::Win32::SystemServices::HANDLE engineHandle, uint64_t id, ::win32::guid* saLookupContext, win32::Windows::Win32::WindowsFiltering::IKEEXT_SA_DETAILS1** sa) noexcept;
    uint32_t __stdcall WIN32_IMPL_IkeextSaGetById2(win32::Windows::Win32::SystemServices::HANDLE engineHandle, uint64_t id, ::win32::guid* saLookupContext, win32::Windows::Win32::WindowsFiltering::IKEEXT_SA_DETAILS2** sa) noexcept;
    uint32_t __stdcall WIN32_IMPL_IkeextSaCreateEnumHandle0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::WindowsFiltering::IKEEXT_SA_ENUM_TEMPLATE0* enumTemplate, win32::Windows::Win32::SystemServices::HANDLE* enumHandle) noexcept;
    uint32_t __stdcall WIN32_IMPL_IkeextSaEnum0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::SystemServices::HANDLE enumHandle, uint32_t numEntriesRequested, win32::Windows::Win32::WindowsFiltering::IKEEXT_SA_DETAILS0*** entries, uint32_t* numEntriesReturned) noexcept;
    uint32_t __stdcall WIN32_IMPL_IkeextSaEnum1(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::SystemServices::HANDLE enumHandle, uint32_t numEntriesRequested, win32::Windows::Win32::WindowsFiltering::IKEEXT_SA_DETAILS1*** entries, uint32_t* numEntriesReturned) noexcept;
    uint32_t __stdcall WIN32_IMPL_IkeextSaEnum2(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::SystemServices::HANDLE enumHandle, uint32_t numEntriesRequested, win32::Windows::Win32::WindowsFiltering::IKEEXT_SA_DETAILS2*** entries, uint32_t* numEntriesReturned) noexcept;
    uint32_t __stdcall WIN32_IMPL_IkeextSaDestroyEnumHandle0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::SystemServices::HANDLE enumHandle) noexcept;
    uint32_t __stdcall WIN32_IMPL_IkeextSaDbGetSecurityInfo0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, uint32_t securityInfo, void** sidOwner, void** sidGroup, win32::Windows::Win32::Security::ACL** dacl, win32::Windows::Win32::Security::ACL** sacl, void** securityDescriptor) noexcept;
    uint32_t __stdcall WIN32_IMPL_IkeextSaDbSetSecurityInfo0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, uint32_t securityInfo, win32::Windows::Win32::Security::SID* sidOwner, win32::Windows::Win32::Security::SID* sidGroup, win32::Windows::Win32::Security::ACL* dacl, win32::Windows::Win32::Security::ACL* sacl) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmNetEventCreateEnumHandle0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::WindowsFiltering::FWPM_NET_EVENT_ENUM_TEMPLATE0* enumTemplate, win32::Windows::Win32::SystemServices::HANDLE* enumHandle) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmNetEventEnum0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::SystemServices::HANDLE enumHandle, uint32_t numEntriesRequested, win32::Windows::Win32::WindowsFiltering::FWPM_NET_EVENT0*** entries, uint32_t* numEntriesReturned) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmNetEventEnum1(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::SystemServices::HANDLE enumHandle, uint32_t numEntriesRequested, win32::Windows::Win32::WindowsFiltering::FWPM_NET_EVENT1*** entries, uint32_t* numEntriesReturned) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmNetEventEnum2(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::SystemServices::HANDLE enumHandle, uint32_t numEntriesRequested, win32::Windows::Win32::WindowsFiltering::FWPM_NET_EVENT2*** entries, uint32_t* numEntriesReturned) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmNetEventEnum3(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::SystemServices::HANDLE enumHandle, uint32_t numEntriesRequested, win32::Windows::Win32::WindowsFiltering::FWPM_NET_EVENT3*** entries, uint32_t* numEntriesReturned) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmNetEventEnum4(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::SystemServices::HANDLE enumHandle, uint32_t numEntriesRequested, win32::Windows::Win32::WindowsFiltering::FWPM_NET_EVENT4_*** entries, uint32_t* numEntriesReturned) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmNetEventEnum5(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::SystemServices::HANDLE enumHandle, uint32_t numEntriesRequested, win32::Windows::Win32::WindowsFiltering::FWPM_NET_EVENT5_*** entries, uint32_t* numEntriesReturned) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmNetEventDestroyEnumHandle0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::SystemServices::HANDLE enumHandle) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmNetEventsGetSecurityInfo0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, uint32_t securityInfo, void** sidOwner, void** sidGroup, win32::Windows::Win32::Security::ACL** dacl, win32::Windows::Win32::Security::ACL** sacl, void** securityDescriptor) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmNetEventsSetSecurityInfo0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, uint32_t securityInfo, win32::Windows::Win32::Security::SID* sidOwner, win32::Windows::Win32::Security::SID* sidGroup, win32::Windows::Win32::Security::ACL* dacl, win32::Windows::Win32::Security::ACL* sacl) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmNetEventSubscribe0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::WindowsFiltering::FWPM_NET_EVENT_SUBSCRIPTION0* subscription, win32::Windows::Win32::WindowsFiltering::FWPM_NET_EVENT_CALLBACK0* callback, void* context, win32::Windows::Win32::SystemServices::HANDLE* eventsHandle) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmNetEventUnsubscribe0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::SystemServices::HANDLE eventsHandle) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmNetEventSubscriptionsGet0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::WindowsFiltering::FWPM_NET_EVENT_SUBSCRIPTION0*** entries, uint32_t* numEntries) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmNetEventSubscribe1(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::WindowsFiltering::FWPM_NET_EVENT_SUBSCRIPTION0* subscription, win32::Windows::Win32::WindowsFiltering::FWPM_NET_EVENT_CALLBACK1* callback, void* context, win32::Windows::Win32::SystemServices::HANDLE* eventsHandle) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmNetEventSubscribe2(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::WindowsFiltering::FWPM_NET_EVENT_SUBSCRIPTION0* subscription, win32::Windows::Win32::WindowsFiltering::FWPM_NET_EVENT_CALLBACK2* callback, void* context, win32::Windows::Win32::SystemServices::HANDLE* eventsHandle) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmNetEventSubscribe3(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::WindowsFiltering::FWPM_NET_EVENT_SUBSCRIPTION0* subscription, win32::Windows::Win32::WindowsFiltering::FWPM_NET_EVENT_CALLBACK3* callback, void* context, win32::Windows::Win32::SystemServices::HANDLE* eventsHandle) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmNetEventSubscribe4(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::WindowsFiltering::FWPM_NET_EVENT_SUBSCRIPTION0* subscription, win32::Windows::Win32::WindowsFiltering::FWPM_NET_EVENT_CALLBACK4* callback, void* context, win32::Windows::Win32::SystemServices::HANDLE* eventsHandle) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmSystemPortsGet0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::WindowsFiltering::FWPM_SYSTEM_PORTS0** sysPorts) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmSystemPortsSubscribe0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, void* reserved, win32::Windows::Win32::WindowsFiltering::FWPM_SYSTEM_PORTS_CALLBACK0* callback, void* context, win32::Windows::Win32::SystemServices::HANDLE* sysPortsHandle) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmSystemPortsUnsubscribe0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::SystemServices::HANDLE sysPortsHandle) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmConnectionGetById0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, uint64_t id, win32::Windows::Win32::WindowsFiltering::FWPM_CONNECTION0** connection) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmConnectionEnum0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::SystemServices::HANDLE enumHandle, uint32_t numEntriesRequested, win32::Windows::Win32::WindowsFiltering::FWPM_CONNECTION0*** entries, uint32_t* numEntriesReturned) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmConnectionCreateEnumHandle0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::WindowsFiltering::FWPM_CONNECTION_ENUM_TEMPLATE0* enumTemplate, win32::Windows::Win32::SystemServices::HANDLE* enumHandle) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmConnectionDestroyEnumHandle0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::SystemServices::HANDLE enumHandle) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmConnectionGetSecurityInfo0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, uint32_t securityInfo, void** sidOwner, void** sidGroup, win32::Windows::Win32::Security::ACL** dacl, win32::Windows::Win32::Security::ACL** sacl, void** securityDescriptor) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmConnectionSetSecurityInfo0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, uint32_t securityInfo, win32::Windows::Win32::Security::SID* sidOwner, win32::Windows::Win32::Security::SID* sidGroup, win32::Windows::Win32::Security::ACL* dacl, win32::Windows::Win32::Security::ACL* sacl) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmConnectionSubscribe0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::WindowsFiltering::FWPM_CONNECTION_SUBSCRIPTION0* subscription, win32::Windows::Win32::WindowsFiltering::FWPM_CONNECTION_CALLBACK0* callback, void* context, win32::Windows::Win32::SystemServices::HANDLE* eventsHandle) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmConnectionUnsubscribe0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::SystemServices::HANDLE eventsHandle) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmvSwitchEventSubscribe0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::WindowsFiltering::FWPM_VSWITCH_EVENT_SUBSCRIPTION0* subscription, win32::Windows::Win32::WindowsFiltering::FWPM_VSWITCH_EVENT_CALLBACK0* callback, void* context, win32::Windows::Win32::SystemServices::HANDLE* subscriptionHandle) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmvSwitchEventUnsubscribe0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, win32::Windows::Win32::SystemServices::HANDLE subscriptionHandle) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmvSwitchEventsGetSecurityInfo0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, uint32_t securityInfo, void** sidOwner, void** sidGroup, win32::Windows::Win32::Security::ACL** dacl, win32::Windows::Win32::Security::ACL** sacl, void** securityDescriptor) noexcept;
    uint32_t __stdcall WIN32_IMPL_FwpmvSwitchEventsSetSecurityInfo0(win32::Windows::Win32::SystemServices::HANDLE engineHandle, uint32_t securityInfo, win32::Windows::Win32::Security::SID* sidOwner, win32::Windows::Win32::Security::SID* sidGroup, win32::Windows::Win32::Security::ACL* dacl, win32::Windows::Win32::Security::ACL* sacl) noexcept;
}
WIN32_IMPL_LINK(FwpmFreeMemory0, 4)
WIN32_IMPL_LINK(FwpmEngineOpen0, 20)
WIN32_IMPL_LINK(FwpmEngineClose0, 4)
WIN32_IMPL_LINK(FwpmEngineGetOption0, 12)
WIN32_IMPL_LINK(FwpmEngineSetOption0, 12)
WIN32_IMPL_LINK(FwpmEngineGetSecurityInfo0, 28)
WIN32_IMPL_LINK(FwpmEngineSetSecurityInfo0, 24)
WIN32_IMPL_LINK(FwpmSessionCreateEnumHandle0, 12)
WIN32_IMPL_LINK(FwpmSessionEnum0, 20)
WIN32_IMPL_LINK(FwpmSessionDestroyEnumHandle0, 8)
WIN32_IMPL_LINK(FwpmTransactionBegin0, 8)
WIN32_IMPL_LINK(FwpmTransactionCommit0, 4)
WIN32_IMPL_LINK(FwpmTransactionAbort0, 4)
WIN32_IMPL_LINK(FwpmProviderAdd0, 12)
WIN32_IMPL_LINK(FwpmProviderDeleteByKey0, 8)
WIN32_IMPL_LINK(FwpmProviderGetByKey0, 12)
WIN32_IMPL_LINK(FwpmProviderCreateEnumHandle0, 12)
WIN32_IMPL_LINK(FwpmProviderEnum0, 20)
WIN32_IMPL_LINK(FwpmProviderDestroyEnumHandle0, 8)
WIN32_IMPL_LINK(FwpmProviderGetSecurityInfoByKey0, 32)
WIN32_IMPL_LINK(FwpmProviderSetSecurityInfoByKey0, 28)
WIN32_IMPL_LINK(FwpmProviderSubscribeChanges0, 20)
WIN32_IMPL_LINK(FwpmProviderUnsubscribeChanges0, 8)
WIN32_IMPL_LINK(FwpmProviderSubscriptionsGet0, 12)
WIN32_IMPL_LINK(FwpmProviderContextAdd0, 16)
WIN32_IMPL_LINK(FwpmProviderContextAdd1, 16)
WIN32_IMPL_LINK(FwpmProviderContextAdd2, 16)
WIN32_IMPL_LINK(FwpmProviderContextAdd3, 16)
WIN32_IMPL_LINK(FwpmProviderContextDeleteById0, 12)
WIN32_IMPL_LINK(FwpmProviderContextDeleteByKey0, 8)
WIN32_IMPL_LINK(FwpmProviderContextGetById0, 16)
WIN32_IMPL_LINK(FwpmProviderContextGetById1, 16)
WIN32_IMPL_LINK(FwpmProviderContextGetById2, 16)
WIN32_IMPL_LINK(FwpmProviderContextGetById3, 16)
WIN32_IMPL_LINK(FwpmProviderContextGetByKey0, 12)
WIN32_IMPL_LINK(FwpmProviderContextGetByKey1, 12)
WIN32_IMPL_LINK(FwpmProviderContextGetByKey2, 12)
WIN32_IMPL_LINK(FwpmProviderContextGetByKey3, 12)
WIN32_IMPL_LINK(FwpmProviderContextCreateEnumHandle0, 12)
WIN32_IMPL_LINK(FwpmProviderContextEnum0, 20)
WIN32_IMPL_LINK(FwpmProviderContextEnum1, 20)
WIN32_IMPL_LINK(FwpmProviderContextEnum2, 20)
WIN32_IMPL_LINK(FwpmProviderContextEnum3, 20)
WIN32_IMPL_LINK(FwpmProviderContextDestroyEnumHandle0, 8)
WIN32_IMPL_LINK(FwpmProviderContextGetSecurityInfoByKey0, 32)
WIN32_IMPL_LINK(FwpmProviderContextSetSecurityInfoByKey0, 28)
WIN32_IMPL_LINK(FwpmProviderContextSubscribeChanges0, 20)
WIN32_IMPL_LINK(FwpmProviderContextUnsubscribeChanges0, 8)
WIN32_IMPL_LINK(FwpmProviderContextSubscriptionsGet0, 12)
WIN32_IMPL_LINK(FwpmSubLayerAdd0, 12)
WIN32_IMPL_LINK(FwpmSubLayerDeleteByKey0, 8)
WIN32_IMPL_LINK(FwpmSubLayerGetByKey0, 12)
WIN32_IMPL_LINK(FwpmSubLayerCreateEnumHandle0, 12)
WIN32_IMPL_LINK(FwpmSubLayerEnum0, 20)
WIN32_IMPL_LINK(FwpmSubLayerDestroyEnumHandle0, 8)
WIN32_IMPL_LINK(FwpmSubLayerGetSecurityInfoByKey0, 32)
WIN32_IMPL_LINK(FwpmSubLayerSetSecurityInfoByKey0, 28)
WIN32_IMPL_LINK(FwpmSubLayerSubscribeChanges0, 20)
WIN32_IMPL_LINK(FwpmSubLayerUnsubscribeChanges0, 8)
WIN32_IMPL_LINK(FwpmSubLayerSubscriptionsGet0, 12)
WIN32_IMPL_LINK(FwpmLayerGetById0, 12)
WIN32_IMPL_LINK(FwpmLayerGetByKey0, 12)
WIN32_IMPL_LINK(FwpmLayerCreateEnumHandle0, 12)
WIN32_IMPL_LINK(FwpmLayerEnum0, 20)
WIN32_IMPL_LINK(FwpmLayerDestroyEnumHandle0, 8)
WIN32_IMPL_LINK(FwpmLayerGetSecurityInfoByKey0, 32)
WIN32_IMPL_LINK(FwpmLayerSetSecurityInfoByKey0, 28)
WIN32_IMPL_LINK(FwpmCalloutAdd0, 16)
WIN32_IMPL_LINK(FwpmCalloutDeleteById0, 8)
WIN32_IMPL_LINK(FwpmCalloutDeleteByKey0, 8)
WIN32_IMPL_LINK(FwpmCalloutGetById0, 12)
WIN32_IMPL_LINK(FwpmCalloutGetByKey0, 12)
WIN32_IMPL_LINK(FwpmCalloutCreateEnumHandle0, 12)
WIN32_IMPL_LINK(FwpmCalloutEnum0, 20)
WIN32_IMPL_LINK(FwpmCalloutDestroyEnumHandle0, 8)
WIN32_IMPL_LINK(FwpmCalloutGetSecurityInfoByKey0, 32)
WIN32_IMPL_LINK(FwpmCalloutSetSecurityInfoByKey0, 28)
WIN32_IMPL_LINK(FwpmCalloutSubscribeChanges0, 20)
WIN32_IMPL_LINK(FwpmCalloutUnsubscribeChanges0, 8)
WIN32_IMPL_LINK(FwpmCalloutSubscriptionsGet0, 12)
WIN32_IMPL_LINK(FwpmFilterAdd0, 16)
WIN32_IMPL_LINK(FwpmFilterDeleteById0, 12)
WIN32_IMPL_LINK(FwpmFilterDeleteByKey0, 8)
WIN32_IMPL_LINK(FwpmFilterGetById0, 16)
WIN32_IMPL_LINK(FwpmFilterGetByKey0, 12)
WIN32_IMPL_LINK(FwpmFilterCreateEnumHandle0, 12)
WIN32_IMPL_LINK(FwpmFilterEnum0, 20)
WIN32_IMPL_LINK(FwpmFilterDestroyEnumHandle0, 8)
WIN32_IMPL_LINK(FwpmFilterGetSecurityInfoByKey0, 32)
WIN32_IMPL_LINK(FwpmFilterSetSecurityInfoByKey0, 28)
WIN32_IMPL_LINK(FwpmFilterSubscribeChanges0, 20)
WIN32_IMPL_LINK(FwpmFilterUnsubscribeChanges0, 8)
WIN32_IMPL_LINK(FwpmFilterSubscriptionsGet0, 12)
WIN32_IMPL_LINK(FwpmGetAppIdFromFileName0, 8)
WIN32_IMPL_LINK(FwpmBitmapIndexGet0, 12)
WIN32_IMPL_LINK(FwpmBitmapIndexFree0, 12)
WIN32_IMPL_LINK(FwpmIPsecTunnelAdd0, 28)
WIN32_IMPL_LINK(FwpmIPsecTunnelAdd1, 32)
WIN32_IMPL_LINK(FwpmIPsecTunnelAdd2, 32)
WIN32_IMPL_LINK(FwpmIPsecTunnelAdd3, 32)
WIN32_IMPL_LINK(FwpmIPsecTunnelDeleteByKey0, 8)
WIN32_IMPL_LINK(IPsecGetStatistics0, 8)
WIN32_IMPL_LINK(IPsecGetStatistics1, 8)
WIN32_IMPL_LINK(IPsecSaContextCreate0, 16)
WIN32_IMPL_LINK(IPsecSaContextCreate1, 20)
WIN32_IMPL_LINK(IPsecSaContextDeleteById0, 12)
WIN32_IMPL_LINK(IPsecSaContextGetById0, 16)
WIN32_IMPL_LINK(IPsecSaContextGetById1, 16)
WIN32_IMPL_LINK(IPsecSaContextGetSpi0, 20)
WIN32_IMPL_LINK(IPsecSaContextGetSpi1, 20)
WIN32_IMPL_LINK(IPsecSaContextSetSpi0, 20)
WIN32_IMPL_LINK(IPsecSaContextAddInbound0, 16)
WIN32_IMPL_LINK(IPsecSaContextAddOutbound0, 16)
WIN32_IMPL_LINK(IPsecSaContextAddInbound1, 16)
WIN32_IMPL_LINK(IPsecSaContextAddOutbound1, 16)
WIN32_IMPL_LINK(IPsecSaContextExpire0, 12)
WIN32_IMPL_LINK(IPsecSaContextUpdate0, 16)
WIN32_IMPL_LINK(IPsecSaContextCreateEnumHandle0, 12)
WIN32_IMPL_LINK(IPsecSaContextEnum0, 20)
WIN32_IMPL_LINK(IPsecSaContextEnum1, 20)
WIN32_IMPL_LINK(IPsecSaContextDestroyEnumHandle0, 8)
WIN32_IMPL_LINK(IPsecSaContextSubscribe0, 20)
WIN32_IMPL_LINK(IPsecSaContextUnsubscribe0, 8)
WIN32_IMPL_LINK(IPsecSaContextSubscriptionsGet0, 12)
WIN32_IMPL_LINK(IPsecSaCreateEnumHandle0, 12)
WIN32_IMPL_LINK(IPsecSaEnum0, 20)
WIN32_IMPL_LINK(IPsecSaEnum1, 20)
WIN32_IMPL_LINK(IPsecSaDestroyEnumHandle0, 8)
WIN32_IMPL_LINK(IPsecSaDbGetSecurityInfo0, 28)
WIN32_IMPL_LINK(IPsecSaDbSetSecurityInfo0, 24)
WIN32_IMPL_LINK(IPsecDospGetStatistics0, 8)
WIN32_IMPL_LINK(IPsecDospStateCreateEnumHandle0, 12)
WIN32_IMPL_LINK(IPsecDospStateEnum0, 20)
WIN32_IMPL_LINK(IPsecDospStateDestroyEnumHandle0, 8)
WIN32_IMPL_LINK(IPsecDospGetSecurityInfo0, 28)
WIN32_IMPL_LINK(IPsecDospSetSecurityInfo0, 24)
WIN32_IMPL_LINK(IPsecKeyManagerAddAndRegister0, 16)
WIN32_IMPL_LINK(IPsecKeyManagerUnregisterAndDelete0, 8)
WIN32_IMPL_LINK(IPsecKeyManagersGet0, 12)
WIN32_IMPL_LINK(IPsecKeyManagerGetSecurityInfoByKey0, 32)
WIN32_IMPL_LINK(IPsecKeyManagerSetSecurityInfoByKey0, 28)
WIN32_IMPL_LINK(IkeextGetStatistics0, 8)
WIN32_IMPL_LINK(IkeextGetStatistics1, 8)
WIN32_IMPL_LINK(IkeextSaDeleteById0, 12)
WIN32_IMPL_LINK(IkeextSaGetById0, 16)
WIN32_IMPL_LINK(IkeextSaGetById1, 20)
WIN32_IMPL_LINK(IkeextSaGetById2, 20)
WIN32_IMPL_LINK(IkeextSaCreateEnumHandle0, 12)
WIN32_IMPL_LINK(IkeextSaEnum0, 20)
WIN32_IMPL_LINK(IkeextSaEnum1, 20)
WIN32_IMPL_LINK(IkeextSaEnum2, 20)
WIN32_IMPL_LINK(IkeextSaDestroyEnumHandle0, 8)
WIN32_IMPL_LINK(IkeextSaDbGetSecurityInfo0, 28)
WIN32_IMPL_LINK(IkeextSaDbSetSecurityInfo0, 24)
WIN32_IMPL_LINK(FwpmNetEventCreateEnumHandle0, 12)
WIN32_IMPL_LINK(FwpmNetEventEnum0, 20)
WIN32_IMPL_LINK(FwpmNetEventEnum1, 20)
WIN32_IMPL_LINK(FwpmNetEventEnum2, 20)
WIN32_IMPL_LINK(FwpmNetEventEnum3, 20)
WIN32_IMPL_LINK(FwpmNetEventEnum4, 20)
WIN32_IMPL_LINK(FwpmNetEventEnum5, 20)
WIN32_IMPL_LINK(FwpmNetEventDestroyEnumHandle0, 8)
WIN32_IMPL_LINK(FwpmNetEventsGetSecurityInfo0, 28)
WIN32_IMPL_LINK(FwpmNetEventsSetSecurityInfo0, 24)
WIN32_IMPL_LINK(FwpmNetEventSubscribe0, 20)
WIN32_IMPL_LINK(FwpmNetEventUnsubscribe0, 8)
WIN32_IMPL_LINK(FwpmNetEventSubscriptionsGet0, 12)
WIN32_IMPL_LINK(FwpmNetEventSubscribe1, 20)
WIN32_IMPL_LINK(FwpmNetEventSubscribe2, 20)
WIN32_IMPL_LINK(FwpmNetEventSubscribe3, 20)
WIN32_IMPL_LINK(FwpmNetEventSubscribe4, 20)
WIN32_IMPL_LINK(FwpmSystemPortsGet0, 8)
WIN32_IMPL_LINK(FwpmSystemPortsSubscribe0, 20)
WIN32_IMPL_LINK(FwpmSystemPortsUnsubscribe0, 8)
WIN32_IMPL_LINK(FwpmConnectionGetById0, 16)
WIN32_IMPL_LINK(FwpmConnectionEnum0, 20)
WIN32_IMPL_LINK(FwpmConnectionCreateEnumHandle0, 12)
WIN32_IMPL_LINK(FwpmConnectionDestroyEnumHandle0, 8)
WIN32_IMPL_LINK(FwpmConnectionGetSecurityInfo0, 28)
WIN32_IMPL_LINK(FwpmConnectionSetSecurityInfo0, 24)
WIN32_IMPL_LINK(FwpmConnectionSubscribe0, 20)
WIN32_IMPL_LINK(FwpmConnectionUnsubscribe0, 8)
WIN32_IMPL_LINK(FwpmvSwitchEventSubscribe0, 20)
WIN32_IMPL_LINK(FwpmvSwitchEventUnsubscribe0, 8)
WIN32_IMPL_LINK(FwpmvSwitchEventsGetSecurityInfo0, 28)
WIN32_IMPL_LINK(FwpmvSwitchEventsSetSecurityInfo0, 24)

#pragma endregion abi_methods

#endif
