// WARNING: Please don't edit this file. It was generated by C++/Win32 v0.0.0.1

#ifndef WIN32_Windows_Win32_KeyboardAndMouseInput_0_H
#define WIN32_Windows_Win32_KeyboardAndMouseInput_0_H
WIN32_EXPORT namespace win32::Windows::Win32::KeyboardAndMouseInput
{
#pragma region enums
#pragma endregion enums

#pragma region forward_declarations
    struct HARDWAREINPUT;
    struct INPUT;
    struct KEYBDINPUT;
    struct LASTINPUTINFO;
    struct MOUSEINPUT;
    struct MOUSEMOVEPOINT;
    struct RAWHID;
    struct RAWINPUT;
    struct RAWINPUTDEVICE;
    struct RAWINPUTDEVICELIST;
    struct RAWINPUTHEADER;
    struct RAWKEYBOARD;
    struct RAWMOUSE;
    struct RID_DEVICE_INFO;
    struct RID_DEVICE_INFO_HID;
    struct RID_DEVICE_INFO_KEYBOARD;
    struct RID_DEVICE_INFO_MOUSE;
    struct TRACKMOUSEEVENT;
#pragma endregion forward_declarations

#pragma region delegates
#pragma endregion delegates

}
namespace win32::_impl_
{
#pragma region guids
#pragma endregion guids

}
#endif
