// WARNING: Please don't edit this file. It was generated by C++/Win32 v0.0.0.1

#ifndef WIN32_Windows_Win32_DataExchange_0_H
#define WIN32_Windows_Win32_DataExchange_0_H
WIN32_EXPORT namespace win32::Windows::Win32::DataExchange
{
#pragma region enums
#pragma endregion enums

#pragma region forward_declarations
    struct CONVCONTEXT;
    struct CONVINFO;
    struct COPYDATASTRUCT;
    struct DDEACK;
    struct DDEADVISE;
    struct DDEDATA;
    struct DDELN;
    struct DDEML_MSG_HOOK_DATA;
    struct DDEPOKE;
    struct DDEUP;
    struct HCONVLIST__;
    struct HCONV__;
    struct HDDEDATA__;
    struct HSZPAIR;
    struct HSZ__;
    struct METAFILEPICT;
    struct MONCBSTRUCT;
    struct MONCONVSTRUCT;
    struct MONERRSTRUCT;
    struct MONHSZSTRUCTA;
    struct MONHSZSTRUCTW;
    struct MONLINKSTRUCT;
    struct MONMSGSTRUCT;
#pragma endregion forward_declarations

#pragma region delegates
    using FNCALLBACK = intptr_t __stdcall(uint32_t, uint32_t, intptr_t, intptr_t, intptr_t, intptr_t, size_t, size_t);
    using PFNCALLBACK = intptr_t __stdcall(uint32_t, uint32_t, intptr_t, intptr_t, intptr_t, intptr_t, size_t, size_t);
#pragma endregion delegates

}
namespace win32::_impl_
{
#pragma region guids
#pragma endregion guids

}
#endif
