// WARNING: Please don't edit this file. It was generated by C++/Win32 v0.0.0.1

#ifndef WIN32_Windows_Win32_Bluetooth_2_H
#define WIN32_Windows_Win32_Bluetooth_2_H
#include "win32/impl/Windows.Win32.Bluetooth.1.h"
#include "win32/impl/complex_interfaces.h"
#pragma region abi_methods
extern "C"
{
    intptr_t __stdcall WIN32_IMPL_BluetoothFindFirstRadio(win32::Windows::Win32::Bluetooth::BLUETOOTH_FIND_RADIO_PARAMS* pbtfrp, win32::Windows::Win32::SystemServices::HANDLE* phRadio) noexcept;
    win32::Windows::Win32::SystemServices::BOOL __stdcall WIN32_IMPL_BluetoothFindNextRadio(intptr_t hFind, win32::Windows::Win32::SystemServices::HANDLE* phRadio) noexcept;
    win32::Windows::Win32::SystemServices::BOOL __stdcall WIN32_IMPL_BluetoothFindRadioClose(intptr_t hFind) noexcept;
    uint32_t __stdcall WIN32_IMPL_BluetoothGetRadioInfo(win32::Windows::Win32::SystemServices::HANDLE hRadio, win32::Windows::Win32::Bluetooth::BLUETOOTH_RADIO_INFO* pRadioInfo) noexcept;
    intptr_t __stdcall WIN32_IMPL_BluetoothFindFirstDevice(win32::Windows::Win32::Bluetooth::BLUETOOTH_DEVICE_SEARCH_PARAMS* pbtsp, win32::Windows::Win32::Bluetooth::BLUETOOTH_DEVICE_INFO_STRUCT* pbtdi) noexcept;
    win32::Windows::Win32::SystemServices::BOOL __stdcall WIN32_IMPL_BluetoothFindNextDevice(intptr_t hFind, win32::Windows::Win32::Bluetooth::BLUETOOTH_DEVICE_INFO_STRUCT* pbtdi) noexcept;
    win32::Windows::Win32::SystemServices::BOOL __stdcall WIN32_IMPL_BluetoothFindDeviceClose(intptr_t hFind) noexcept;
    uint32_t __stdcall WIN32_IMPL_BluetoothGetDeviceInfo(win32::Windows::Win32::SystemServices::HANDLE hRadio, win32::Windows::Win32::Bluetooth::BLUETOOTH_DEVICE_INFO_STRUCT* pbtdi) noexcept;
    uint32_t __stdcall WIN32_IMPL_BluetoothUpdateDeviceRecord(win32::Windows::Win32::Bluetooth::BLUETOOTH_DEVICE_INFO_STRUCT* pbtdi) noexcept;
    uint32_t __stdcall WIN32_IMPL_BluetoothRemoveDevice(win32::Windows::Win32::Bluetooth::BLUETOOTH_ADDRESS_STRUCT* pAddress) noexcept;
    win32::Windows::Win32::SystemServices::BOOL __stdcall WIN32_IMPL_BluetoothSelectDevices(win32::Windows::Win32::Bluetooth::BLUETOOTH_SELECT_DEVICE_PARAMS* pbtsdp) noexcept;
    win32::Windows::Win32::SystemServices::BOOL __stdcall WIN32_IMPL_BluetoothSelectDevicesFree(win32::Windows::Win32::Bluetooth::BLUETOOTH_SELECT_DEVICE_PARAMS* pbtsdp) noexcept;
    win32::Windows::Win32::SystemServices::BOOL __stdcall WIN32_IMPL_BluetoothDisplayDeviceProperties(win32::Windows::Win32::WindowsAndMessaging::HWND hwndParent, win32::Windows::Win32::Bluetooth::BLUETOOTH_DEVICE_INFO_STRUCT* pbtdi) noexcept;
    uint32_t __stdcall WIN32_IMPL_BluetoothAuthenticateDevice(win32::Windows::Win32::WindowsAndMessaging::HWND hwndParent, win32::Windows::Win32::SystemServices::HANDLE hRadio, win32::Windows::Win32::Bluetooth::BLUETOOTH_DEVICE_INFO_STRUCT* pbtbi, uint16_t* pszPasskey, uint32_t ulPasskeyLength) noexcept;
    uint32_t __stdcall WIN32_IMPL_BluetoothAuthenticateDeviceEx(win32::Windows::Win32::WindowsAndMessaging::HWND hwndParentIn, win32::Windows::Win32::SystemServices::HANDLE hRadioIn, win32::Windows::Win32::Bluetooth::BLUETOOTH_DEVICE_INFO_STRUCT* pbtdiInout, win32::Windows::Win32::Bluetooth::BLUETOOTH_OOB_DATA_INFO* pbtOobData, win32::Windows::Win32::Bluetooth::AUTHENTICATION_REQUIREMENTS authenticationRequirement) noexcept;
    uint32_t __stdcall WIN32_IMPL_BluetoothAuthenticateMultipleDevices(win32::Windows::Win32::WindowsAndMessaging::HWND hwndParent, win32::Windows::Win32::SystemServices::HANDLE hRadio, uint32_t cDevices, win32::Windows::Win32::Bluetooth::BLUETOOTH_DEVICE_INFO_STRUCT* rgbtdi) noexcept;
    uint32_t __stdcall WIN32_IMPL_BluetoothSetServiceState(win32::Windows::Win32::SystemServices::HANDLE hRadio, win32::Windows::Win32::Bluetooth::BLUETOOTH_DEVICE_INFO_STRUCT* pbtdi, ::win32::guid* pGuidService, uint32_t dwServiceFlags) noexcept;
    uint32_t __stdcall WIN32_IMPL_BluetoothEnumerateInstalledServices(win32::Windows::Win32::SystemServices::HANDLE hRadio, win32::Windows::Win32::Bluetooth::BLUETOOTH_DEVICE_INFO_STRUCT* pbtdi, uint32_t* pcServiceInout, ::win32::guid* pGuidServices) noexcept;
    win32::Windows::Win32::SystemServices::BOOL __stdcall WIN32_IMPL_BluetoothEnableDiscovery(win32::Windows::Win32::SystemServices::HANDLE hRadio, win32::Windows::Win32::SystemServices::BOOL fEnabled) noexcept;
    win32::Windows::Win32::SystemServices::BOOL __stdcall WIN32_IMPL_BluetoothIsDiscoverable(win32::Windows::Win32::SystemServices::HANDLE hRadio) noexcept;
    win32::Windows::Win32::SystemServices::BOOL __stdcall WIN32_IMPL_BluetoothEnableIncomingConnections(win32::Windows::Win32::SystemServices::HANDLE hRadio, win32::Windows::Win32::SystemServices::BOOL fEnabled) noexcept;
    win32::Windows::Win32::SystemServices::BOOL __stdcall WIN32_IMPL_BluetoothIsConnectable(win32::Windows::Win32::SystemServices::HANDLE hRadio) noexcept;
    uint32_t __stdcall WIN32_IMPL_BluetoothRegisterForAuthentication(win32::Windows::Win32::Bluetooth::BLUETOOTH_DEVICE_INFO_STRUCT* pbtdi, intptr_t* phRegHandle, win32::Windows::Win32::Bluetooth::PFN_AUTHENTICATION_CALLBACK* pfnCallback, void* pvParam) noexcept;
    uint32_t __stdcall WIN32_IMPL_BluetoothRegisterForAuthenticationEx(win32::Windows::Win32::Bluetooth::BLUETOOTH_DEVICE_INFO_STRUCT* pbtdiIn, intptr_t* phRegHandleOut, win32::Windows::Win32::Bluetooth::PFN_AUTHENTICATION_CALLBACK_EX* pfnCallbackIn, void* pvParam) noexcept;
    win32::Windows::Win32::SystemServices::BOOL __stdcall WIN32_IMPL_BluetoothUnregisterAuthentication(intptr_t hRegHandle) noexcept;
    uint32_t __stdcall WIN32_IMPL_BluetoothSendAuthenticationResponse(win32::Windows::Win32::SystemServices::HANDLE hRadio, win32::Windows::Win32::Bluetooth::BLUETOOTH_DEVICE_INFO_STRUCT* pbtdi, uint16_t* pszPasskey) noexcept;
    uint32_t __stdcall WIN32_IMPL_BluetoothSendAuthenticationResponseEx(win32::Windows::Win32::SystemServices::HANDLE hRadioIn, win32::Windows::Win32::Bluetooth::BLUETOOTH_AUTHENTICATE_RESPONSE* pauthResponse) noexcept;
    uint32_t __stdcall WIN32_IMPL_BluetoothSdpGetElementData(uint8_t* pSdpStream, uint32_t cbSdpStreamLength, win32::Windows::Win32::Bluetooth::SDP_ELEMENT_DATA* pData) noexcept;
    uint32_t __stdcall WIN32_IMPL_BluetoothSdpGetContainerElementData(uint8_t* pContainerStream, uint32_t cbContainerLength, intptr_t* pElement, win32::Windows::Win32::Bluetooth::SDP_ELEMENT_DATA* pData) noexcept;
    uint32_t __stdcall WIN32_IMPL_BluetoothSdpGetAttributeValue(uint8_t* pRecordStream, uint32_t cbRecordLength, uint16_t usAttributeId, win32::Windows::Win32::Bluetooth::SDP_ELEMENT_DATA* pAttributeData) noexcept;
    uint32_t __stdcall WIN32_IMPL_BluetoothSdpGetString(uint8_t* pRecordStream, uint32_t cbRecordLength, win32::Windows::Win32::Bluetooth::SDP_STRING_TYPE_DATA* pStringData, uint16_t usStringOffset, uint16_t* pszString, uint32_t* pcchStringLength) noexcept;
    win32::Windows::Win32::SystemServices::BOOL __stdcall WIN32_IMPL_BluetoothSdpEnumAttributes(uint8_t* pSDPStream, uint32_t cbStreamSize, win32::Windows::Win32::Bluetooth::PFN_BLUETOOTH_ENUM_ATTRIBUTES_CALLBACK* pfnCallback, void* pvParam) noexcept;
    uint32_t __stdcall WIN32_IMPL_BluetoothSetLocalServiceInfo(win32::Windows::Win32::SystemServices::HANDLE hRadioIn, ::win32::guid* pClassGuid, uint32_t ulInstance, win32::Windows::Win32::Bluetooth::BLUETOOTH_LOCAL_SERVICE_INFO_STRUCT* pServiceInfoIn) noexcept;
    win32::Windows::Win32::SystemServices::BOOL __stdcall WIN32_IMPL_BluetoothIsVersionAvailable(uint8_t MajorVersion, uint8_t MinorVersion) noexcept;
}
WIN32_IMPL_LINK(BluetoothFindFirstRadio, 8)
WIN32_IMPL_LINK(BluetoothFindNextRadio, 8)
WIN32_IMPL_LINK(BluetoothFindRadioClose, 4)
WIN32_IMPL_LINK(BluetoothGetRadioInfo, 8)
WIN32_IMPL_LINK(BluetoothFindFirstDevice, 8)
WIN32_IMPL_LINK(BluetoothFindNextDevice, 8)
WIN32_IMPL_LINK(BluetoothFindDeviceClose, 4)
WIN32_IMPL_LINK(BluetoothGetDeviceInfo, 8)
WIN32_IMPL_LINK(BluetoothUpdateDeviceRecord, 4)
WIN32_IMPL_LINK(BluetoothRemoveDevice, 4)
WIN32_IMPL_LINK(BluetoothSelectDevices, 4)
WIN32_IMPL_LINK(BluetoothSelectDevicesFree, 4)
WIN32_IMPL_LINK(BluetoothDisplayDeviceProperties, 8)
WIN32_IMPL_LINK(BluetoothAuthenticateDevice, 20)
WIN32_IMPL_LINK(BluetoothAuthenticateDeviceEx, 20)
WIN32_IMPL_LINK(BluetoothAuthenticateMultipleDevices, 16)
WIN32_IMPL_LINK(BluetoothSetServiceState, 16)
WIN32_IMPL_LINK(BluetoothEnumerateInstalledServices, 16)
WIN32_IMPL_LINK(BluetoothEnableDiscovery, 8)
WIN32_IMPL_LINK(BluetoothIsDiscoverable, 4)
WIN32_IMPL_LINK(BluetoothEnableIncomingConnections, 8)
WIN32_IMPL_LINK(BluetoothIsConnectable, 4)
WIN32_IMPL_LINK(BluetoothRegisterForAuthentication, 16)
WIN32_IMPL_LINK(BluetoothRegisterForAuthenticationEx, 16)
WIN32_IMPL_LINK(BluetoothUnregisterAuthentication, 4)
WIN32_IMPL_LINK(BluetoothSendAuthenticationResponse, 12)
WIN32_IMPL_LINK(BluetoothSendAuthenticationResponseEx, 8)
WIN32_IMPL_LINK(BluetoothSdpGetElementData, 12)
WIN32_IMPL_LINK(BluetoothSdpGetContainerElementData, 16)
WIN32_IMPL_LINK(BluetoothSdpGetAttributeValue, 16)
WIN32_IMPL_LINK(BluetoothSdpGetString, 24)
WIN32_IMPL_LINK(BluetoothSdpEnumAttributes, 16)
WIN32_IMPL_LINK(BluetoothSetLocalServiceInfo, 16)
WIN32_IMPL_LINK(BluetoothIsVersionAvailable, 8)

#pragma endregion abi_methods

#endif
