// WARNING: Please don't edit this file. It was generated by C++/Win32 v0.0.0.1

#ifndef WIN32_Windows_Win32_PhotoAcquire_0_H
#define WIN32_Windows_Win32_PhotoAcquire_0_H
WIN32_EXPORT namespace win32::Windows::Win32::PhotoAcquire
{
#pragma region enums
    enum class DEVICE_SELECTION_DEVICE_TYPE : int32_t
    {
        DST_UNKNOWN_DEVICE = 0,
        DST_WPD_DEVICE = 1,
        DST_WIA_DEVICE = 2,
        DST_STI_DEVICE = 3,
        DSF_TWAIN_DEVICE = 4,
        DST_FS_DEVICE = 5,
        DST_DV_DEVICE = 6,
    };
    enum class ERROR_ADVISE_MESSAGE_TYPE : int32_t
    {
        PHOTOACQUIRE_ERROR_SKIPRETRYCANCEL = 0,
        PHOTOACQUIRE_ERROR_RETRYCANCEL = 1,
        PHOTOACQUIRE_ERROR_YESNO = 2,
        PHOTOACQUIRE_ERROR_OK = 3,
    };
    enum class ERROR_ADVISE_RESULT : int32_t
    {
        PHOTOACQUIRE_RESULT_YES = 0,
        PHOTOACQUIRE_RESULT_NO = 1,
        PHOTOACQUIRE_RESULT_OK = 2,
        PHOTOACQUIRE_RESULT_SKIP = 3,
        PHOTOACQUIRE_RESULT_SKIP_ALL = 4,
        PHOTOACQUIRE_RESULT_RETRY = 5,
        PHOTOACQUIRE_RESULT_ABORT = 6,
    };
    enum class PROGRESS_DIALOG_CHECKBOX_ID : int32_t
    {
        PROGRESS_DIALOG_CHECKBOX_ID_DEFAULT = 0,
    };
    enum class PROGRESS_DIALOG_IMAGE_TYPE : int32_t
    {
        PROGRESS_DIALOG_ICON_SMALL = 0,
        PROGRESS_DIALOG_ICON_LARGE = 1,
        PROGRESS_DIALOG_ICON_THUMBNAIL = 2,
        PROGRESS_DIALOG_BITMAP_THUMBNAIL = 3,
    };
    enum class USER_INPUT_STRING_TYPE : int32_t
    {
        USER_INPUT_DEFAULT = 0,
        USER_INPUT_PATH_ELEMENT = 1,
    };
#pragma endregion enums

#pragma region forward_declarations
    struct IPhotoAcquire;
    struct IPhotoAcquireDeviceSelectionDialog;
    struct IPhotoAcquireItem;
    struct IPhotoAcquireOptionsDialog;
    struct IPhotoAcquirePlugin;
    struct IPhotoAcquireProgressCB;
    struct IPhotoAcquireSettings;
    struct IPhotoAcquireSource;
    struct IPhotoProgressActionCB;
    struct IPhotoProgressDialog;
    struct IUserInputString;
    struct PhotoAcquire;
    struct PhotoAcquireAutoPlayDropTarget;
    struct PhotoAcquireAutoPlayHWEventHandler;
    struct PhotoAcquireDeviceSelectionDialog;
    struct PhotoAcquireOptionsDialog;
    struct PhotoProgressDialog;
#pragma endregion forward_declarations

#pragma region delegates
#pragma endregion delegates

}
namespace win32::_impl_
{
#pragma region guids
    template <> inline constexpr guid guid_v<Windows::Win32::PhotoAcquire::IPhotoAcquire>{ 0x00F23353,0xE31B,0x4955,{ 0xA8,0xAD,0xCA,0x5E,0xBF,0x31,0xE2,0xCE } }; // 00F23353-E31B-4955-A8AD-CA5EBF31E2CE
    template <> inline constexpr guid guid_v<Windows::Win32::PhotoAcquire::IPhotoAcquireDeviceSelectionDialog>{ 0x00F28837,0x55DD,0x4F37,{ 0xAA,0xF5,0x68,0x55,0xA9,0x64,0x04,0x67 } }; // 00F28837-55DD-4F37-AAF5-6855A9640467
    template <> inline constexpr guid guid_v<Windows::Win32::PhotoAcquire::IPhotoAcquireItem>{ 0x00F21C97,0x28BF,0x4C02,{ 0xB8,0x42,0x5E,0x4E,0x90,0x13,0x9A,0x30 } }; // 00F21C97-28BF-4C02-B842-5E4E90139A30
    template <> inline constexpr guid guid_v<Windows::Win32::PhotoAcquire::IPhotoAcquireOptionsDialog>{ 0x00F2B3EE,0xBF64,0x47EE,{ 0x89,0xF4,0x4D,0xED,0xD7,0x96,0x43,0xF2 } }; // 00F2B3EE-BF64-47EE-89F4-4DEDD79643F2
    template <> inline constexpr guid guid_v<Windows::Win32::PhotoAcquire::IPhotoAcquirePlugin>{ 0x00F2DCEB,0xECB8,0x4F77,{ 0x8E,0x47,0xE7,0xA9,0x87,0xC8,0x3D,0xD0 } }; // 00F2DCEB-ECB8-4F77-8E47-E7A987C83DD0
    template <> inline constexpr guid guid_v<Windows::Win32::PhotoAcquire::IPhotoAcquireProgressCB>{ 0x00F2CE1E,0x935E,0x4248,{ 0x89,0x2C,0x13,0x0F,0x32,0xC4,0x5C,0xB4 } }; // 00F2CE1E-935E-4248-892C-130F32C45CB4
    template <> inline constexpr guid guid_v<Windows::Win32::PhotoAcquire::IPhotoAcquireSettings>{ 0x00F2B868,0xDD67,0x487C,{ 0x95,0x53,0x04,0x92,0x40,0x76,0x7E,0x91 } }; // 00F2B868-DD67-487C-9553-049240767E91
    template <> inline constexpr guid guid_v<Windows::Win32::PhotoAcquire::IPhotoAcquireSource>{ 0x00F2C703,0x8613,0x4282,{ 0xA5,0x3B,0x6E,0xC5,0x9C,0x58,0x83,0xAC } }; // 00F2C703-8613-4282-A53B-6EC59C5883AC
    template <> inline constexpr guid guid_v<Windows::Win32::PhotoAcquire::IPhotoProgressActionCB>{ 0x00F242D0,0xB206,0x4E7D,{ 0xB4,0xC1,0x47,0x55,0xBC,0xBB,0x9C,0x9F } }; // 00F242D0-B206-4E7D-B4C1-4755BCBB9C9F
    template <> inline constexpr guid guid_v<Windows::Win32::PhotoAcquire::IPhotoProgressDialog>{ 0x00F246F9,0x0750,0x4F08,{ 0x93,0x81,0x2C,0xD8,0xE9,0x06,0xA4,0xAE } }; // 00F246F9-0750-4F08-9381-2CD8E906A4AE
    template <> inline constexpr guid guid_v<Windows::Win32::PhotoAcquire::IUserInputString>{ 0x00F243A1,0x205B,0x45BA,{ 0xAE,0x26,0xAB,0xBC,0x53,0xAA,0x7A,0x6F } }; // 00F243A1-205B-45BA-AE26-ABBC53AA7A6F
    template <> inline constexpr guid guid_v<Windows::Win32::PhotoAcquire::PhotoAcquire>{ 0x00F26E02,0xE9F2,0x4A9F,{ 0x9F,0xDD,0x5A,0x96,0x2F,0xB2,0x6A,0x98 } }; // 00F26E02-E9F2-4A9F-9FDD-5A962FB26A98
    template <> inline constexpr guid guid_v<Windows::Win32::PhotoAcquire::PhotoAcquireAutoPlayDropTarget>{ 0x00F20EB5,0x8FD6,0x4D9D,{ 0xB7,0x5E,0x36,0x80,0x17,0x66,0xC8,0xF1 } }; // 00F20EB5-8FD6-4D9D-B75E-36801766C8F1
    template <> inline constexpr guid guid_v<Windows::Win32::PhotoAcquire::PhotoAcquireAutoPlayHWEventHandler>{ 0x00F2B433,0x44E4,0x4D88,{ 0xB2,0xB0,0x26,0x98,0xA0,0xA9,0x1D,0xBA } }; // 00F2B433-44E4-4D88-B2B0-2698A0A91DBA
    template <> inline constexpr guid guid_v<Windows::Win32::PhotoAcquire::PhotoAcquireDeviceSelectionDialog>{ 0x00F29A34,0xB8A1,0x482C,{ 0xBC,0xF8,0x3A,0xC7,0xB0,0xFE,0x8F,0x62 } }; // 00F29A34-B8A1-482C-BCF8-3AC7B0FE8F62
    template <> inline constexpr guid guid_v<Windows::Win32::PhotoAcquire::PhotoAcquireOptionsDialog>{ 0x00F210A1,0x62F0,0x438B,{ 0x9F,0x7E,0x96,0x18,0xD7,0x2A,0x18,0x31 } }; // 00F210A1-62F0-438B-9F7E-9618D72A1831
    template <> inline constexpr guid guid_v<Windows::Win32::PhotoAcquire::PhotoProgressDialog>{ 0x00F24CA0,0x748F,0x4E8A,{ 0x89,0x4F,0x0E,0x03,0x57,0xC6,0x79,0x9F } }; // 00F24CA0-748F-4E8A-894F-0E0357C6799F
#pragma endregion guids

}
#endif
