// WARNING: Please don't edit this file. It was generated by C++/Win32 v0.0.0.1

#ifndef WIN32_Windows_Win32_DirectComposition_0_H
#define WIN32_Windows_Win32_DirectComposition_0_H
WIN32_EXPORT namespace win32::Windows::Win32::DirectComposition
{
#pragma region enums
    enum class DCOMPOSITION_BACKFACE_VISIBILITY : int32_t
    {
        DCOMPOSITION_BACKFACE_VISIBILITY_VISIBLE = 0,
        DCOMPOSITION_BACKFACE_VISIBILITY_HIDDEN = 1,
        DCOMPOSITION_BACKFACE_VISIBILITY_INHERIT = -1,
    };
    enum class DCOMPOSITION_BITMAP_INTERPOLATION_MODE : int32_t
    {
        DCOMPOSITION_BITMAP_INTERPOLATION_MODE_NEAREST_NEIGHBOR = 0,
        DCOMPOSITION_BITMAP_INTERPOLATION_MODE_LINEAR = 1,
        DCOMPOSITION_BITMAP_INTERPOLATION_MODE_INHERIT = -1,
    };
    enum class DCOMPOSITION_BORDER_MODE : int32_t
    {
        DCOMPOSITION_BORDER_MODE_SOFT = 0,
        DCOMPOSITION_BORDER_MODE_HARD = 1,
        DCOMPOSITION_BORDER_MODE_INHERIT = -1,
    };
    enum class DCOMPOSITION_COMPOSITE_MODE : int32_t
    {
        DCOMPOSITION_COMPOSITE_MODE_SOURCE_OVER = 0,
        DCOMPOSITION_COMPOSITE_MODE_DESTINATION_INVERT = 1,
        DCOMPOSITION_COMPOSITE_MODE_MIN_BLEND = 2,
        DCOMPOSITION_COMPOSITE_MODE_INHERIT = -1,
    };
    enum class DCOMPOSITION_DEPTH_MODE : int32_t
    {
        DCOMPOSITION_DEPTH_MODE_TREE = 0,
        DCOMPOSITION_DEPTH_MODE_SPATIAL = 1,
        DCOMPOSITION_DEPTH_MODE_SORTED = 3,
        DCOMPOSITION_DEPTH_MODE_INHERIT = -1,
    };
    enum class DCOMPOSITION_OPACITY_MODE : int32_t
    {
        DCOMPOSITION_OPACITY_MODE_LAYER = 0,
        DCOMPOSITION_OPACITY_MODE_MULTIPLY = 1,
        DCOMPOSITION_OPACITY_MODE_INHERIT = -1,
    };
#pragma endregion enums

#pragma region forward_declarations
    struct DCOMPOSITION_FRAME_STATISTICS;
    struct IDCompositionAffineTransform2DEffect;
    struct IDCompositionAnimation;
    struct IDCompositionArithmeticCompositeEffect;
    struct IDCompositionBlendEffect;
    struct IDCompositionBrightnessEffect;
    struct IDCompositionClip;
    struct IDCompositionColorMatrixEffect;
    struct IDCompositionCompositeEffect;
    struct IDCompositionDesktopDevice;
    struct IDCompositionDevice;
    struct IDCompositionDevice2;
    struct IDCompositionDevice3;
    struct IDCompositionDeviceDebug;
    struct IDCompositionEffect;
    struct IDCompositionEffectGroup;
    struct IDCompositionFilterEffect;
    struct IDCompositionGaussianBlurEffect;
    struct IDCompositionHueRotationEffect;
    struct IDCompositionLinearTransferEffect;
    struct IDCompositionMatrixTransform;
    struct IDCompositionMatrixTransform3D;
    struct IDCompositionRectangleClip;
    struct IDCompositionRotateTransform;
    struct IDCompositionRotateTransform3D;
    struct IDCompositionSaturationEffect;
    struct IDCompositionScaleTransform;
    struct IDCompositionScaleTransform3D;
    struct IDCompositionShadowEffect;
    struct IDCompositionSkewTransform;
    struct IDCompositionSurface;
    struct IDCompositionSurfaceFactory;
    struct IDCompositionTableTransferEffect;
    struct IDCompositionTarget;
    struct IDCompositionTransform;
    struct IDCompositionTransform3D;
    struct IDCompositionTranslateTransform;
    struct IDCompositionTranslateTransform3D;
    struct IDCompositionTurbulenceEffect;
    struct IDCompositionVirtualSurface;
    struct IDCompositionVisual;
    struct IDCompositionVisual2;
    struct IDCompositionVisual3;
    struct IDCompositionVisualDebug;
#pragma endregion forward_declarations

#pragma region delegates
#pragma endregion delegates

}
namespace win32::_impl_
{
#pragma region guids
    template <> inline constexpr guid guid_v<Windows::Win32::DirectComposition::IDCompositionAffineTransform2DEffect>{ 0x0B74B9E8,0xCDD6,0x492F,{ 0xBB,0xBC,0x5E,0xD3,0x21,0x57,0x02,0x6D } }; // 0B74B9E8-CDD6-492F-BBBC-5ED32157026D
    template <> inline constexpr guid guid_v<Windows::Win32::DirectComposition::IDCompositionAnimation>{ 0xCBFD91D9,0x51B2,0x45E4,{ 0xB3,0xDE,0xD1,0x9C,0xCF,0xB8,0x63,0xC5 } }; // CBFD91D9-51B2-45E4-B3DE-D19CCFB863C5
    template <> inline constexpr guid guid_v<Windows::Win32::DirectComposition::IDCompositionArithmeticCompositeEffect>{ 0x3B67DFA8,0xE3DD,0x4E61,{ 0xB6,0x40,0x46,0xC2,0xF3,0xD7,0x39,0xDC } }; // 3B67DFA8-E3DD-4E61-B640-46C2F3D739DC
    template <> inline constexpr guid guid_v<Windows::Win32::DirectComposition::IDCompositionBlendEffect>{ 0x33ECDC0A,0x578A,0x4A11,{ 0x9C,0x14,0x0C,0xB9,0x05,0x17,0xF9,0xC5 } }; // 33ECDC0A-578A-4A11-9C14-0CB90517F9C5
    template <> inline constexpr guid guid_v<Windows::Win32::DirectComposition::IDCompositionBrightnessEffect>{ 0x6027496E,0xCB3A,0x49AB,{ 0x93,0x4F,0xD7,0x98,0xDA,0x4F,0x7D,0xA6 } }; // 6027496E-CB3A-49AB-934F-D798DA4F7DA6
    template <> inline constexpr guid guid_v<Windows::Win32::DirectComposition::IDCompositionClip>{ 0x64AC3703,0x9D3F,0x45EC,{ 0xA1,0x09,0x7C,0xAC,0x0E,0x7A,0x13,0xA7 } }; // 64AC3703-9D3F-45EC-A109-7CAC0E7A13A7
    template <> inline constexpr guid guid_v<Windows::Win32::DirectComposition::IDCompositionColorMatrixEffect>{ 0xC1170A22,0x3CE2,0x4966,{ 0x90,0xD4,0x55,0x40,0x8B,0xFC,0x84,0xC4 } }; // C1170A22-3CE2-4966-90D4-55408BFC84C4
    template <> inline constexpr guid guid_v<Windows::Win32::DirectComposition::IDCompositionCompositeEffect>{ 0x576616C0,0xA231,0x494D,{ 0xA3,0x8D,0x00,0xFD,0x5E,0xC4,0xDB,0x46 } }; // 576616C0-A231-494D-A38D-00FD5EC4DB46
    template <> inline constexpr guid guid_v<Windows::Win32::DirectComposition::IDCompositionDesktopDevice>{ 0x5F4633FE,0x1E08,0x4CB8,{ 0x8C,0x75,0xCE,0x24,0x33,0x3F,0x56,0x02 } }; // 5F4633FE-1E08-4CB8-8C75-CE24333F5602
    template <> inline constexpr guid guid_v<Windows::Win32::DirectComposition::IDCompositionDevice>{ 0xC37EA93A,0xE7AA,0x450D,{ 0xB1,0x6F,0x97,0x46,0xCB,0x04,0x07,0xF3 } }; // C37EA93A-E7AA-450D-B16F-9746CB0407F3
    template <> inline constexpr guid guid_v<Windows::Win32::DirectComposition::IDCompositionDevice2>{ 0x75F6468D,0x1B8E,0x447C,{ 0x9B,0xC6,0x75,0xFE,0xA8,0x0B,0x5B,0x25 } }; // 75F6468D-1B8E-447C-9BC6-75FEA80B5B25
    template <> inline constexpr guid guid_v<Windows::Win32::DirectComposition::IDCompositionDevice3>{ 0x0987CB06,0xF916,0x48BF,{ 0x8D,0x35,0xCE,0x76,0x41,0x78,0x1B,0xD9 } }; // 0987CB06-F916-48BF-8D35-CE7641781BD9
    template <> inline constexpr guid guid_v<Windows::Win32::DirectComposition::IDCompositionDeviceDebug>{ 0xA1A3C64A,0x224F,0x4A81,{ 0x97,0x73,0x4F,0x03,0xA8,0x9D,0x3C,0x6C } }; // A1A3C64A-224F-4A81-9773-4F03A89D3C6C
    template <> inline constexpr guid guid_v<Windows::Win32::DirectComposition::IDCompositionEffect>{ 0xEC81B08F,0xBFCB,0x4E8D,{ 0xB1,0x93,0xA9,0x15,0x58,0x79,0x99,0xE8 } }; // EC81B08F-BFCB-4E8D-B193-A915587999E8
    template <> inline constexpr guid guid_v<Windows::Win32::DirectComposition::IDCompositionEffectGroup>{ 0xA7929A74,0xE6B2,0x4BD6,{ 0x8B,0x95,0x40,0x40,0x11,0x9C,0xA3,0x4D } }; // A7929A74-E6B2-4BD6-8B95-4040119CA34D
    template <> inline constexpr guid guid_v<Windows::Win32::DirectComposition::IDCompositionFilterEffect>{ 0x30C421D5,0x8CB2,0x4E9F,{ 0xB1,0x33,0x37,0xBE,0x27,0x0D,0x4A,0xC2 } }; // 30C421D5-8CB2-4E9F-B133-37BE270D4AC2
    template <> inline constexpr guid guid_v<Windows::Win32::DirectComposition::IDCompositionGaussianBlurEffect>{ 0x45D4D0B7,0x1BD4,0x454E,{ 0x88,0x94,0x2B,0xFA,0x68,0x44,0x30,0x33 } }; // 45D4D0B7-1BD4-454E-8894-2BFA68443033
    template <> inline constexpr guid guid_v<Windows::Win32::DirectComposition::IDCompositionHueRotationEffect>{ 0x6DB9F920,0x0770,0x4781,{ 0xB0,0xC6,0x38,0x19,0x12,0xF9,0xD1,0x67 } }; // 6DB9F920-0770-4781-B0C6-381912F9D167
    template <> inline constexpr guid guid_v<Windows::Win32::DirectComposition::IDCompositionLinearTransferEffect>{ 0x4305EE5B,0xC4A0,0x4C88,{ 0x93,0x85,0x67,0x12,0x4E,0x01,0x76,0x83 } }; // 4305EE5B-C4A0-4C88-9385-67124E017683
    template <> inline constexpr guid guid_v<Windows::Win32::DirectComposition::IDCompositionMatrixTransform>{ 0x16CDFF07,0xC503,0x419C,{ 0x83,0xF2,0x09,0x65,0xC7,0xAF,0x1F,0xA6 } }; // 16CDFF07-C503-419C-83F2-0965C7AF1FA6
    template <> inline constexpr guid guid_v<Windows::Win32::DirectComposition::IDCompositionMatrixTransform3D>{ 0x4B3363F0,0x643B,0x41B7,{ 0xB6,0xE0,0xCC,0xF2,0x2D,0x34,0x46,0x7C } }; // 4B3363F0-643B-41B7-B6E0-CCF22D34467C
    template <> inline constexpr guid guid_v<Windows::Win32::DirectComposition::IDCompositionRectangleClip>{ 0x9842AD7D,0xD9CF,0x4908,{ 0xAE,0xD7,0x48,0xB5,0x1D,0xA5,0xE7,0xC2 } }; // 9842AD7D-D9CF-4908-AED7-48B51DA5E7C2
    template <> inline constexpr guid guid_v<Windows::Win32::DirectComposition::IDCompositionRotateTransform>{ 0x641ED83C,0xAE96,0x46C5,{ 0x90,0xDC,0x32,0x77,0x4C,0xC5,0xC6,0xD5 } }; // 641ED83C-AE96-46C5-90DC-32774CC5C6D5
    template <> inline constexpr guid guid_v<Windows::Win32::DirectComposition::IDCompositionRotateTransform3D>{ 0xD8F5B23F,0xD429,0x4A91,{ 0xB5,0x5A,0xD2,0xF4,0x5F,0xD7,0x5B,0x18 } }; // D8F5B23F-D429-4A91-B55A-D2F45FD75B18
    template <> inline constexpr guid guid_v<Windows::Win32::DirectComposition::IDCompositionSaturationEffect>{ 0xA08DEBDA,0x3258,0x4FA4,{ 0x9F,0x16,0x91,0x74,0xD3,0xFE,0x93,0xB1 } }; // A08DEBDA-3258-4FA4-9F16-9174D3FE93B1
    template <> inline constexpr guid guid_v<Windows::Win32::DirectComposition::IDCompositionScaleTransform>{ 0x71FDE914,0x40EF,0x45EF,{ 0xBD,0x51,0x68,0xB0,0x37,0xC3,0x39,0xF9 } }; // 71FDE914-40EF-45EF-BD51-68B037C339F9
    template <> inline constexpr guid guid_v<Windows::Win32::DirectComposition::IDCompositionScaleTransform3D>{ 0x2A9E9EAD,0x364B,0x4B15,{ 0xA7,0xC4,0xA1,0x99,0x7F,0x78,0xB3,0x89 } }; // 2A9E9EAD-364B-4B15-A7C4-A1997F78B389
    template <> inline constexpr guid guid_v<Windows::Win32::DirectComposition::IDCompositionShadowEffect>{ 0x4AD18AC0,0xCFD2,0x4C2F,{ 0xBB,0x62,0x96,0xE5,0x4F,0xDB,0x68,0x79 } }; // 4AD18AC0-CFD2-4C2F-BB62-96E54FDB6879
    template <> inline constexpr guid guid_v<Windows::Win32::DirectComposition::IDCompositionSkewTransform>{ 0xE57AA735,0xDCDB,0x4C72,{ 0x9C,0x61,0x05,0x91,0xF5,0x88,0x89,0xEE } }; // E57AA735-DCDB-4C72-9C61-0591F58889EE
    template <> inline constexpr guid guid_v<Windows::Win32::DirectComposition::IDCompositionSurface>{ 0xBB8A4953,0x2C99,0x4F5A,{ 0x96,0xF5,0x48,0x19,0x02,0x7F,0xA3,0xAC } }; // BB8A4953-2C99-4F5A-96F5-4819027FA3AC
    template <> inline constexpr guid guid_v<Windows::Win32::DirectComposition::IDCompositionSurfaceFactory>{ 0xE334BC12,0x3937,0x4E02,{ 0x85,0xEB,0xFC,0xF4,0xEB,0x30,0xD2,0xC8 } }; // E334BC12-3937-4E02-85EB-FCF4EB30D2C8
    template <> inline constexpr guid guid_v<Windows::Win32::DirectComposition::IDCompositionTableTransferEffect>{ 0x9B7E82E2,0x69C5,0x4EB4,{ 0xA5,0xF5,0xA7,0x03,0x3F,0x51,0x32,0xCD } }; // 9B7E82E2-69C5-4EB4-A5F5-A7033F5132CD
    template <> inline constexpr guid guid_v<Windows::Win32::DirectComposition::IDCompositionTarget>{ 0xEACDD04C,0x117E,0x4E17,{ 0x88,0xF4,0xD1,0xB1,0x2B,0x0E,0x3D,0x89 } }; // EACDD04C-117E-4E17-88F4-D1B12B0E3D89
    template <> inline constexpr guid guid_v<Windows::Win32::DirectComposition::IDCompositionTransform>{ 0xFD55FAA7,0x37E0,0x4C20,{ 0x95,0xD2,0x9B,0xE4,0x5B,0xC3,0x3F,0x55 } }; // FD55FAA7-37E0-4C20-95D2-9BE45BC33F55
    template <> inline constexpr guid guid_v<Windows::Win32::DirectComposition::IDCompositionTransform3D>{ 0x71185722,0x246B,0x41F2,{ 0xAA,0xD1,0x04,0x43,0xF7,0xF4,0xBF,0xC2 } }; // 71185722-246B-41F2-AAD1-0443F7F4BFC2
    template <> inline constexpr guid guid_v<Windows::Win32::DirectComposition::IDCompositionTranslateTransform>{ 0x06791122,0xC6F0,0x417D,{ 0x83,0x23,0x26,0x9E,0x98,0x7F,0x59,0x54 } }; // 06791122-C6F0-417D-8323-269E987F5954
    template <> inline constexpr guid guid_v<Windows::Win32::DirectComposition::IDCompositionTranslateTransform3D>{ 0x91636D4B,0x9BA1,0x4532,{ 0xAA,0xF7,0xE3,0x34,0x49,0x94,0xD7,0x88 } }; // 91636D4B-9BA1-4532-AAF7-E3344994D788
    template <> inline constexpr guid guid_v<Windows::Win32::DirectComposition::IDCompositionTurbulenceEffect>{ 0xA6A55BDA,0xC09C,0x49F3,{ 0x91,0x93,0xA4,0x19,0x22,0xC8,0x97,0x15 } }; // A6A55BDA-C09C-49F3-9193-A41922C89715
    template <> inline constexpr guid guid_v<Windows::Win32::DirectComposition::IDCompositionVirtualSurface>{ 0xAE471C51,0x5F53,0x4A24,{ 0x8D,0x3E,0xD0,0xC3,0x9C,0x30,0xB3,0xF0 } }; // AE471C51-5F53-4A24-8D3E-D0C39C30B3F0
    template <> inline constexpr guid guid_v<Windows::Win32::DirectComposition::IDCompositionVisual>{ 0x4D93059D,0x097B,0x4651,{ 0x9A,0x60,0xF0,0xF2,0x51,0x16,0xE2,0xF3 } }; // 4D93059D-097B-4651-9A60-F0F25116E2F3
    template <> inline constexpr guid guid_v<Windows::Win32::DirectComposition::IDCompositionVisual2>{ 0xE8DE1639,0x4331,0x4B26,{ 0xBC,0x5F,0x6A,0x32,0x1D,0x34,0x7A,0x85 } }; // E8DE1639-4331-4B26-BC5F-6A321D347A85
    template <> inline constexpr guid guid_v<Windows::Win32::DirectComposition::IDCompositionVisual3>{ 0x2775F462,0xB6C1,0x4015,{ 0xB0,0xBE,0xB3,0xE7,0xD6,0xA4,0x97,0x6D } }; // 2775F462-B6C1-4015-B0BE-B3E7D6A4976D
    template <> inline constexpr guid guid_v<Windows::Win32::DirectComposition::IDCompositionVisualDebug>{ 0xFED2B808,0x5EB4,0x43A0,{ 0xAE,0xA3,0x35,0xF6,0x52,0x80,0xF9,0x1B } }; // FED2B808-5EB4-43A0-AEA3-35F65280F91B
#pragma endregion guids

}
#endif
