// WARNING: Please don't edit this file. It was generated by C++/Win32 v0.0.0.1

#ifndef WIN32_Windows_Win32_Compression_0_H
#define WIN32_Windows_Win32_Compression_0_H
WIN32_EXPORT namespace win32::Windows::Win32::Compression
{
#pragma region enums
    enum class COMPRESS_INFORMATION_CLASS : int32_t
    {
        COMPRESS_INFORMATION_CLASS_INVALID = 0,
        COMPRESS_INFORMATION_CLASS_BLOCK_SIZE = 1,
        COMPRESS_INFORMATION_CLASS_LEVEL = 2,
    };
#pragma endregion enums

#pragma region forward_declarations
    struct COMPRESSOR_HANDLE;
    struct COMPRESS_ALLOCATION_ROUTINES;
#pragma endregion forward_declarations

#pragma region delegates
    using PFN_COMPRESS_ALLOCATE = void* __stdcall(void*, size_t);
    using PFN_COMPRESS_FREE = void __stdcall(void*, void*);
#pragma endregion delegates

}
namespace win32::_impl_
{
#pragma region guids
#pragma endregion guids

}
#endif
