// WARNING: Please don't edit this file. It was generated by C++/Win32 v0.0.0.1

#ifndef WIN32_Windows_Win32_WindowsSubsystemForLinux_0_H
#define WIN32_Windows_Win32_WindowsSubsystemForLinux_0_H
WIN32_EXPORT namespace win32::Windows::Win32::WindowsSubsystemForLinux
{
#pragma region enums
    enum class WSL_DISTRIBUTION_FLAGS : int32_t
    {
        WSL_DISTRIBUTION_FLAGS_NONE = 0,
        WSL_DISTRIBUTION_FLAGS_ENABLE_INTEROP = 1,
        WSL_DISTRIBUTION_FLAGS_APPEND_NT_PATH = 2,
        WSL_DISTRIBUTION_FLAGS_ENABLE_DRIVE_MOUNTING = 4,
    };
#pragma endregion enums

#pragma region forward_declarations
#pragma endregion forward_declarations

#pragma region delegates
#pragma endregion delegates

}
namespace win32::_impl_
{
#pragma region guids
#pragma endregion guids

}
#endif
