// WARNING: Please don't edit this file. It was generated by C++/Win32 v0.0.0.1

#ifndef WIN32_Windows_Win32_WindowsMediaLibrarySharingServices_0_H
#define WIN32_Windows_Win32_WindowsMediaLibrarySharingServices_0_H
WIN32_EXPORT namespace win32::Windows::Win32::WindowsMediaLibrarySharingServices
{
#pragma region enums
    enum class WindowsMediaLibrarySharingDeviceAuthorizationStatus : int32_t
    {
        DEVICE_AUTHORIZATION_UNKNOWN = 0,
        DEVICE_AUTHORIZATION_ALLOWED = 1,
        DEVICE_AUTHORIZATION_DENIED = 2,
    };
#pragma endregion enums

#pragma region forward_declarations
    struct IWindowsMediaLibrarySharingDevice;
    struct IWindowsMediaLibrarySharingDeviceProperties;
    struct IWindowsMediaLibrarySharingDeviceProperty;
    struct IWindowsMediaLibrarySharingDevices;
    struct IWindowsMediaLibrarySharingServices;
    struct WindowsMediaLibrarySharingServices;
#pragma endregion forward_declarations

#pragma region delegates
#pragma endregion delegates

}
namespace win32::_impl_
{
#pragma region guids
    template <> inline constexpr guid guid_v<Windows::Win32::WindowsMediaLibrarySharingServices::IWindowsMediaLibrarySharingDevice>{ 0x3DCCC293,0x4FD9,0x4191,{ 0xA2,0x5B,0x8E,0x57,0xC5,0xD2,0x7B,0xD4 } }; // 3DCCC293-4FD9-4191-A25B-8E57C5D27BD4
    template <> inline constexpr guid guid_v<Windows::Win32::WindowsMediaLibrarySharingServices::IWindowsMediaLibrarySharingDeviceProperties>{ 0xC4623214,0x6B06,0x40C5,{ 0xA6,0x23,0xB2,0xFF,0x4C,0x07,0x6B,0xFD } }; // C4623214-6B06-40C5-A623-B2FF4C076BFD
    template <> inline constexpr guid guid_v<Windows::Win32::WindowsMediaLibrarySharingServices::IWindowsMediaLibrarySharingDeviceProperty>{ 0x81E26927,0x7A7D,0x40A7,{ 0x81,0xD4,0xBD,0xDC,0x02,0x96,0x0E,0x3E } }; // 81E26927-7A7D-40A7-81D4-BDDC02960E3E
    template <> inline constexpr guid guid_v<Windows::Win32::WindowsMediaLibrarySharingServices::IWindowsMediaLibrarySharingDevices>{ 0x1803F9D6,0xFE6D,0x4546,{ 0xBF,0x5B,0x99,0x2F,0xE8,0xEC,0x12,0xD1 } }; // 1803F9D6-FE6D-4546-BF5B-992FE8EC12D1
    template <> inline constexpr guid guid_v<Windows::Win32::WindowsMediaLibrarySharingServices::IWindowsMediaLibrarySharingServices>{ 0x01F5F85E,0x0A81,0x40DA,{ 0xA7,0xC8,0x21,0xEF,0x3A,0xF8,0x44,0x0C } }; // 01F5F85E-0A81-40DA-A7C8-21EF3AF8440C
    template <> inline constexpr guid guid_v<Windows::Win32::WindowsMediaLibrarySharingServices::WindowsMediaLibrarySharingServices>{ 0xAD581B00,0x7B64,0x4E59,{ 0xA3,0x8D,0xD2,0xC5,0xBF,0x51,0xDD,0xB3 } }; // AD581B00-7B64-4E59-A38D-D2C5BF51DDB3
#pragma endregion guids

}
#endif
