// WARNING: Please don't edit this file. It was generated by C++/Win32 v0.0.0.1

#ifndef WIN32_Windows_Win32_StructuredStorage_2_H
#define WIN32_Windows_Win32_StructuredStorage_2_H
#include "win32/impl/Windows.Win32.StructuredStorage.1.h"
#include "win32/impl/complex_interfaces.h"
#pragma region abi_methods
extern "C"
{
    int32_t __stdcall WIN32_IMPL_CreateStreamOnHGlobal(intptr_t hGlobal, win32::Windows::Win32::SystemServices::BOOL fDeleteOnRelease, win32::Windows::Win32::StructuredStorage::IStream** ppstm) noexcept;
    int32_t __stdcall WIN32_IMPL_GetHGlobalFromStream(win32::Windows::Win32::StructuredStorage::IStream* pstm, intptr_t* phglobal) noexcept;
    int32_t __stdcall WIN32_IMPL_PropVariantCopy(win32::Windows::Win32::StructuredStorage::PROPVARIANT* pvarDest, win32::Windows::Win32::StructuredStorage::PROPVARIANT* pvarSrc) noexcept;
    int32_t __stdcall WIN32_IMPL_PropVariantClear(win32::Windows::Win32::StructuredStorage::PROPVARIANT* pvar) noexcept;
    int32_t __stdcall WIN32_IMPL_FreePropVariantArray(uint32_t cVariants, win32::Windows::Win32::StructuredStorage::PROPVARIANT* rgvars) noexcept;
    int32_t __stdcall WIN32_IMPL_WriteFmtUserTypeStg(win32::Windows::Win32::StructuredStorage::IStorage* pstg, uint16_t cf, uint16_t* lpszUserType) noexcept;
    int32_t __stdcall WIN32_IMPL_ReadFmtUserTypeStg(win32::Windows::Win32::StructuredStorage::IStorage* pstg, uint16_t* pcf, uint16_t** lplpszUserType) noexcept;
    int32_t __stdcall WIN32_IMPL_OleConvertOLESTREAMToIStorage(win32::Windows::Win32::Com::OLESTREAM* lpolestream, win32::Windows::Win32::StructuredStorage::IStorage* pstg, win32::Windows::Win32::Com::DVTARGETDEVICE* ptd) noexcept;
    int32_t __stdcall WIN32_IMPL_OleConvertIStorageToOLESTREAM(win32::Windows::Win32::StructuredStorage::IStorage* pstg, win32::Windows::Win32::Com::OLESTREAM* lpolestream) noexcept;
    int32_t __stdcall WIN32_IMPL_SetConvertStg(win32::Windows::Win32::StructuredStorage::IStorage* pStg, win32::Windows::Win32::SystemServices::BOOL fConvert) noexcept;
    int32_t __stdcall WIN32_IMPL_OleConvertIStorageToOLESTREAMEx(win32::Windows::Win32::StructuredStorage::IStorage* pstg, uint16_t cfFormat, int32_t lWidth, int32_t lHeight, uint32_t dwSize, win32::Windows::Win32::Com::STGMEDIUM* pmedium, win32::Windows::Win32::Com::OLESTREAM* polestm) noexcept;
    int32_t __stdcall WIN32_IMPL_OleConvertOLESTREAMToIStorageEx(win32::Windows::Win32::Com::OLESTREAM* polestm, win32::Windows::Win32::StructuredStorage::IStorage* pstg, uint16_t* pcfFormat, int32_t* plwWidth, int32_t* plHeight, uint32_t* pdwSize, win32::Windows::Win32::Com::STGMEDIUM* pmedium) noexcept;
    int32_t __stdcall WIN32_IMPL_StgSerializePropVariant(win32::Windows::Win32::StructuredStorage::PROPVARIANT* ppropvar, win32::Windows::Win32::Shell::SERIALIZEDPROPERTYVALUE** ppProp, uint32_t* pcb) noexcept;
    int32_t __stdcall WIN32_IMPL_StgDeserializePropVariant(win32::Windows::Win32::Shell::SERIALIZEDPROPERTYVALUE* pprop, uint32_t cbMax, win32::Windows::Win32::StructuredStorage::PROPVARIANT* ppropvar) noexcept;
    int32_t __stdcall WIN32_IMPL_StgCreateDocfile(uint16_t* pwcsName, uint32_t grfMode, uint32_t reserved, win32::Windows::Win32::StructuredStorage::IStorage** ppstgOpen) noexcept;
    int32_t __stdcall WIN32_IMPL_StgCreateDocfileOnILockBytes(win32::Windows::Win32::StructuredStorage::ILockBytes* plkbyt, uint32_t grfMode, uint32_t reserved, win32::Windows::Win32::StructuredStorage::IStorage** ppstgOpen) noexcept;
    int32_t __stdcall WIN32_IMPL_StgOpenStorage(uint16_t* pwcsName, win32::Windows::Win32::StructuredStorage::IStorage* pstgPriority, uint32_t grfMode, uint16_t** snbExclude, uint32_t reserved, win32::Windows::Win32::StructuredStorage::IStorage** ppstgOpen) noexcept;
    int32_t __stdcall WIN32_IMPL_StgOpenStorageOnILockBytes(win32::Windows::Win32::StructuredStorage::ILockBytes* plkbyt, win32::Windows::Win32::StructuredStorage::IStorage* pstgPriority, uint32_t grfMode, uint16_t** snbExclude, uint32_t reserved, win32::Windows::Win32::StructuredStorage::IStorage** ppstgOpen) noexcept;
    int32_t __stdcall WIN32_IMPL_StgIsStorageFile(uint16_t* pwcsName) noexcept;
    int32_t __stdcall WIN32_IMPL_StgIsStorageILockBytes(win32::Windows::Win32::StructuredStorage::ILockBytes* plkbyt) noexcept;
    int32_t __stdcall WIN32_IMPL_StgSetTimes(uint16_t* lpszName, win32::Windows::Win32::WindowsProgramming::FILETIME* pctime, win32::Windows::Win32::WindowsProgramming::FILETIME* patime, win32::Windows::Win32::WindowsProgramming::FILETIME* pmtime) noexcept;
    int32_t __stdcall WIN32_IMPL_StgCreateStorageEx(uint16_t* pwcsName, uint32_t grfMode, uint32_t stgfmt, uint32_t grfAttrs, win32::Windows::Win32::StructuredStorage::STGOPTIONS* pStgOptions, void* pSecurityDescriptor, ::win32::guid* riid, void** ppObjectOpen) noexcept;
    int32_t __stdcall WIN32_IMPL_StgOpenStorageEx(uint16_t* pwcsName, uint32_t grfMode, uint32_t stgfmt, uint32_t grfAttrs, win32::Windows::Win32::StructuredStorage::STGOPTIONS* pStgOptions, void* pSecurityDescriptor, ::win32::guid* riid, void** ppObjectOpen) noexcept;
    int32_t __stdcall WIN32_IMPL_StgCreatePropStg(win32::Windows::Win32::Com::IUnknown* pUnk, ::win32::guid* fmtid, ::win32::guid* pclsid, uint32_t grfFlags, uint32_t dwReserved, win32::Windows::Win32::StructuredStorage::IPropertyStorage** ppPropStg) noexcept;
    int32_t __stdcall WIN32_IMPL_StgOpenPropStg(win32::Windows::Win32::Com::IUnknown* pUnk, ::win32::guid* fmtid, uint32_t grfFlags, uint32_t dwReserved, win32::Windows::Win32::StructuredStorage::IPropertyStorage** ppPropStg) noexcept;
    int32_t __stdcall WIN32_IMPL_StgCreatePropSetStg(win32::Windows::Win32::StructuredStorage::IStorage* pStorage, uint32_t dwReserved, win32::Windows::Win32::StructuredStorage::IPropertySetStorage** ppPropSetStg) noexcept;
    int32_t __stdcall WIN32_IMPL_FmtIdToPropStgName(::win32::guid* pfmtid, uint16_t* oszName) noexcept;
    int32_t __stdcall WIN32_IMPL_PropStgNameToFmtId(uint16_t* oszName, ::win32::guid* pfmtid) noexcept;
    int32_t __stdcall WIN32_IMPL_ReadClassStg(win32::Windows::Win32::StructuredStorage::IStorage* pStg, ::win32::guid* pclsid) noexcept;
    int32_t __stdcall WIN32_IMPL_WriteClassStg(win32::Windows::Win32::StructuredStorage::IStorage* pStg, ::win32::guid* rclsid) noexcept;
    int32_t __stdcall WIN32_IMPL_ReadClassStm(win32::Windows::Win32::StructuredStorage::IStream* pStm, ::win32::guid* pclsid) noexcept;
    int32_t __stdcall WIN32_IMPL_WriteClassStm(win32::Windows::Win32::StructuredStorage::IStream* pStm, ::win32::guid* rclsid) noexcept;
    int32_t __stdcall WIN32_IMPL_GetHGlobalFromILockBytes(win32::Windows::Win32::StructuredStorage::ILockBytes* plkbyt, intptr_t* phglobal) noexcept;
    int32_t __stdcall WIN32_IMPL_CreateILockBytesOnHGlobal(intptr_t hGlobal, win32::Windows::Win32::SystemServices::BOOL fDeleteOnRelease, win32::Windows::Win32::StructuredStorage::ILockBytes** pplkbyt) noexcept;
    int32_t __stdcall WIN32_IMPL_GetConvertStg(win32::Windows::Win32::StructuredStorage::IStorage* pStg) noexcept;
    uint32_t __stdcall WIN32_IMPL_CoBuildVersion() noexcept;
    int32_t __stdcall WIN32_IMPL_DcomChannelSetHResult(void* pvReserved, uint32_t* pulReserved, int32_t appsHR) noexcept;
    int32_t __stdcall WIN32_IMPL_StgOpenAsyncDocfileOnIFillLockBytes(win32::Windows::Win32::StructuredStorage::IFillLockBytes* pflb, uint32_t grfMode, uint32_t asyncFlags, win32::Windows::Win32::StructuredStorage::IStorage** ppstgOpen) noexcept;
    int32_t __stdcall WIN32_IMPL_StgGetIFillLockBytesOnILockBytes(win32::Windows::Win32::StructuredStorage::ILockBytes* pilb, win32::Windows::Win32::StructuredStorage::IFillLockBytes** ppflb) noexcept;
    int32_t __stdcall WIN32_IMPL_StgGetIFillLockBytesOnFile(uint16_t* pwcsName, win32::Windows::Win32::StructuredStorage::IFillLockBytes** ppflb) noexcept;
    int32_t __stdcall WIN32_IMPL_StgOpenLayoutDocfile(uint16_t* pwcsDfName, uint32_t grfMode, uint32_t reserved, win32::Windows::Win32::StructuredStorage::IStorage** ppstgOpen) noexcept;
    win32::Windows::Win32::Shell::SERIALIZEDPROPERTYVALUE* __stdcall WIN32_IMPL_StgConvertVariantToProperty(win32::Windows::Win32::StructuredStorage::PROPVARIANT* pvar, uint16_t CodePage, win32::Windows::Win32::Shell::SERIALIZEDPROPERTYVALUE* pprop, uint32_t* pcb, uint32_t pid, uint8_t fReserved, uint32_t* pcIndirect) noexcept;
    uint8_t __stdcall WIN32_IMPL_StgConvertPropertyToVariant(win32::Windows::Win32::Shell::SERIALIZEDPROPERTYVALUE* pprop, uint16_t CodePage, win32::Windows::Win32::StructuredStorage::PROPVARIANT* pvar, win32::Windows::Win32::StructuredStorage::PMemoryAllocator* pma) noexcept;
    int32_t __stdcall WIN32_IMPL_CreateStdProgressIndicator(win32::Windows::Win32::WindowsAndMessaging::HWND hwndParent, uint16_t* pszTitle, win32::Windows::Win32::Com::IBindStatusCallback* pIbscCaller, win32::Windows::Win32::Com::IBindStatusCallback** ppIbsc) noexcept;
    uint32_t __stdcall WIN32_IMPL_StgPropertyLengthAsVariant(win32::Windows::Win32::Shell::SERIALIZEDPROPERTYVALUE* pProp, uint32_t cbProp, uint16_t CodePage, uint8_t bReserved) noexcept;
    int32_t __stdcall WIN32_IMPL_JetInit(uint32_t* pinstance) noexcept;
    int32_t __stdcall WIN32_IMPL_JetInit2(uint32_t* pinstance, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetInit3A(uint32_t* pinstance, win32::Windows::Win32::StructuredStorage::JET_RSTINFO_A* prstInfo, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetInit3W(uint32_t* pinstance, win32::Windows::Win32::StructuredStorage::JET_RSTINFO_W* prstInfo, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetCreateInstanceA(uint32_t* pinstance, int8_t* szInstanceName) noexcept;
    int32_t __stdcall WIN32_IMPL_JetCreateInstanceW(uint32_t* pinstance, uint16_t* szInstanceName) noexcept;
    int32_t __stdcall WIN32_IMPL_JetCreateInstance2A(uint32_t* pinstance, int8_t* szInstanceName, int8_t* szDisplayName, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetCreateInstance2W(uint32_t* pinstance, uint16_t* szInstanceName, uint16_t* szDisplayName, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetGetInstanceMiscInfo(uint32_t instance, void* pvResult, uint32_t cbMax, uint32_t InfoLevel) noexcept;
    int32_t __stdcall WIN32_IMPL_JetTerm(uint32_t instance) noexcept;
    int32_t __stdcall WIN32_IMPL_JetTerm2(uint32_t instance, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetStopService() noexcept;
    int32_t __stdcall WIN32_IMPL_JetStopServiceInstance(uint32_t instance) noexcept;
    int32_t __stdcall WIN32_IMPL_JetStopServiceInstance2(uint32_t instance, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetStopBackup() noexcept;
    int32_t __stdcall WIN32_IMPL_JetStopBackupInstance(uint32_t instance) noexcept;
    int32_t __stdcall WIN32_IMPL_JetSetSystemParameterA(uint32_t* pinstance, uint32_t sesid, uint32_t paramid, uint32_t lParam, int8_t* szParam) noexcept;
    int32_t __stdcall WIN32_IMPL_JetSetSystemParameterW(uint32_t* pinstance, uint32_t sesid, uint32_t paramid, uint32_t lParam, uint16_t* szParam) noexcept;
    int32_t __stdcall WIN32_IMPL_JetGetSystemParameterA(uint32_t instance, uint32_t sesid, uint32_t paramid, uint32_t* plParam, int8_t* szParam, uint32_t cbMax) noexcept;
    int32_t __stdcall WIN32_IMPL_JetGetSystemParameterW(uint32_t instance, uint32_t sesid, uint32_t paramid, uint32_t* plParam, uint16_t* szParam, uint32_t cbMax) noexcept;
    int32_t __stdcall WIN32_IMPL_JetEnableMultiInstanceA(win32::Windows::Win32::StructuredStorage::JET_SETSYSPARAM_A* psetsysparam, uint32_t csetsysparam, uint32_t* pcsetsucceed) noexcept;
    int32_t __stdcall WIN32_IMPL_JetEnableMultiInstanceW(win32::Windows::Win32::StructuredStorage::JET_SETSYSPARAM_W* psetsysparam, uint32_t csetsysparam, uint32_t* pcsetsucceed) noexcept;
    int32_t __stdcall WIN32_IMPL_JetGetThreadStats(void* pvResult, uint32_t cbMax) noexcept;
    int32_t __stdcall WIN32_IMPL_JetBeginSessionA(uint32_t instance, uint32_t* psesid, int8_t* szUserName, int8_t* szPassword) noexcept;
    int32_t __stdcall WIN32_IMPL_JetBeginSessionW(uint32_t instance, uint32_t* psesid, uint16_t* szUserName, uint16_t* szPassword) noexcept;
    int32_t __stdcall WIN32_IMPL_JetDupSession(uint32_t sesid, uint32_t* psesid) noexcept;
    int32_t __stdcall WIN32_IMPL_JetEndSession(uint32_t sesid, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetGetVersion(uint32_t sesid, uint32_t* pwVersion) noexcept;
    int32_t __stdcall WIN32_IMPL_JetIdle(uint32_t sesid, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetCreateDatabaseA(uint32_t sesid, int8_t* szFilename, int8_t* szConnect, uint32_t* pdbid, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetCreateDatabaseW(uint32_t sesid, uint16_t* szFilename, uint16_t* szConnect, uint32_t* pdbid, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetCreateDatabase2A(uint32_t sesid, int8_t* szFilename, uint32_t cpgDatabaseSizeMax, uint32_t* pdbid, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetCreateDatabase2W(uint32_t sesid, uint16_t* szFilename, uint32_t cpgDatabaseSizeMax, uint32_t* pdbid, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetAttachDatabaseA(uint32_t sesid, int8_t* szFilename, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetAttachDatabaseW(uint32_t sesid, uint16_t* szFilename, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetAttachDatabase2A(uint32_t sesid, int8_t* szFilename, uint32_t cpgDatabaseSizeMax, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetAttachDatabase2W(uint32_t sesid, uint16_t* szFilename, uint32_t cpgDatabaseSizeMax, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetDetachDatabaseA(uint32_t sesid, int8_t* szFilename) noexcept;
    int32_t __stdcall WIN32_IMPL_JetDetachDatabaseW(uint32_t sesid, uint16_t* szFilename) noexcept;
    int32_t __stdcall WIN32_IMPL_JetDetachDatabase2A(uint32_t sesid, int8_t* szFilename, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetDetachDatabase2W(uint32_t sesid, uint16_t* szFilename, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetGetObjectInfoA(uint32_t sesid, uint32_t dbid, uint32_t objtyp, int8_t* szContainerName, int8_t* szObjectName, void* pvResult, uint32_t cbMax, uint32_t InfoLevel) noexcept;
    int32_t __stdcall WIN32_IMPL_JetGetObjectInfoW(uint32_t sesid, uint32_t dbid, uint32_t objtyp, uint16_t* szContainerName, uint16_t* szObjectName, void* pvResult, uint32_t cbMax, uint32_t InfoLevel) noexcept;
    int32_t __stdcall WIN32_IMPL_JetGetTableInfoA(uint32_t sesid, uint32_t tableid, void* pvResult, uint32_t cbMax, uint32_t InfoLevel) noexcept;
    int32_t __stdcall WIN32_IMPL_JetGetTableInfoW(uint32_t sesid, uint32_t tableid, void* pvResult, uint32_t cbMax, uint32_t InfoLevel) noexcept;
    int32_t __stdcall WIN32_IMPL_JetCreateTableA(uint32_t sesid, uint32_t dbid, int8_t* szTableName, uint32_t lPages, uint32_t lDensity, uint32_t* ptableid) noexcept;
    int32_t __stdcall WIN32_IMPL_JetCreateTableW(uint32_t sesid, uint32_t dbid, uint16_t* szTableName, uint32_t lPages, uint32_t lDensity, uint32_t* ptableid) noexcept;
    int32_t __stdcall WIN32_IMPL_JetCreateTableColumnIndexA(uint32_t sesid, uint32_t dbid, win32::Windows::Win32::StructuredStorage::JET_TABLECREATE_A* ptablecreate) noexcept;
    int32_t __stdcall WIN32_IMPL_JetCreateTableColumnIndexW(uint32_t sesid, uint32_t dbid, win32::Windows::Win32::StructuredStorage::JET_TABLECREATE_W* ptablecreate) noexcept;
    int32_t __stdcall WIN32_IMPL_JetCreateTableColumnIndex2A(uint32_t sesid, uint32_t dbid, win32::Windows::Win32::StructuredStorage::JET_TABLECREATE2_A* ptablecreate) noexcept;
    int32_t __stdcall WIN32_IMPL_JetCreateTableColumnIndex2W(uint32_t sesid, uint32_t dbid, win32::Windows::Win32::StructuredStorage::JET_TABLECREATE2_W* ptablecreate) noexcept;
    int32_t __stdcall WIN32_IMPL_JetCreateTableColumnIndex3A(uint32_t sesid, uint32_t dbid, win32::Windows::Win32::StructuredStorage::JET_TABLECREATE3_A* ptablecreate) noexcept;
    int32_t __stdcall WIN32_IMPL_JetCreateTableColumnIndex3W(uint32_t sesid, uint32_t dbid, win32::Windows::Win32::StructuredStorage::JET_TABLECREATE3_W* ptablecreate) noexcept;
    int32_t __stdcall WIN32_IMPL_JetCreateTableColumnIndex4A(uint32_t sesid, uint32_t dbid, win32::Windows::Win32::StructuredStorage::JET_TABLECREATE4_A* ptablecreate) noexcept;
    int32_t __stdcall WIN32_IMPL_JetCreateTableColumnIndex4W(uint32_t sesid, uint32_t dbid, win32::Windows::Win32::StructuredStorage::JET_TABLECREATE4_W* ptablecreate) noexcept;
    int32_t __stdcall WIN32_IMPL_JetDeleteTableA(uint32_t sesid, uint32_t dbid, int8_t* szTableName) noexcept;
    int32_t __stdcall WIN32_IMPL_JetDeleteTableW(uint32_t sesid, uint32_t dbid, uint16_t* szTableName) noexcept;
    int32_t __stdcall WIN32_IMPL_JetRenameTableA(uint32_t sesid, uint32_t dbid, int8_t* szName, int8_t* szNameNew) noexcept;
    int32_t __stdcall WIN32_IMPL_JetRenameTableW(uint32_t sesid, uint32_t dbid, uint16_t* szName, uint16_t* szNameNew) noexcept;
    int32_t __stdcall WIN32_IMPL_JetGetTableColumnInfoA(uint32_t sesid, uint32_t tableid, int8_t* szColumnName, void* pvResult, uint32_t cbMax, uint32_t InfoLevel) noexcept;
    int32_t __stdcall WIN32_IMPL_JetGetTableColumnInfoW(uint32_t sesid, uint32_t tableid, uint16_t* szColumnName, void* pvResult, uint32_t cbMax, uint32_t InfoLevel) noexcept;
    int32_t __stdcall WIN32_IMPL_JetGetColumnInfoA(uint32_t sesid, uint32_t dbid, int8_t* szTableName, int8_t* pColumnNameOrId, void* pvResult, uint32_t cbMax, uint32_t InfoLevel) noexcept;
    int32_t __stdcall WIN32_IMPL_JetGetColumnInfoW(uint32_t sesid, uint32_t dbid, uint16_t* szTableName, uint16_t* pwColumnNameOrId, void* pvResult, uint32_t cbMax, uint32_t InfoLevel) noexcept;
    int32_t __stdcall WIN32_IMPL_JetAddColumnA(uint32_t sesid, uint32_t tableid, int8_t* szColumnName, win32::Windows::Win32::StructuredStorage::JET_COLUMNDEF* pcolumndef, void* pvDefault, uint32_t cbDefault, uint32_t* pcolumnid) noexcept;
    int32_t __stdcall WIN32_IMPL_JetAddColumnW(uint32_t sesid, uint32_t tableid, uint16_t* szColumnName, win32::Windows::Win32::StructuredStorage::JET_COLUMNDEF* pcolumndef, void* pvDefault, uint32_t cbDefault, uint32_t* pcolumnid) noexcept;
    int32_t __stdcall WIN32_IMPL_JetDeleteColumnA(uint32_t sesid, uint32_t tableid, int8_t* szColumnName) noexcept;
    int32_t __stdcall WIN32_IMPL_JetDeleteColumnW(uint32_t sesid, uint32_t tableid, uint16_t* szColumnName) noexcept;
    int32_t __stdcall WIN32_IMPL_JetDeleteColumn2A(uint32_t sesid, uint32_t tableid, int8_t* szColumnName, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetDeleteColumn2W(uint32_t sesid, uint32_t tableid, uint16_t* szColumnName, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetRenameColumnA(uint32_t sesid, uint32_t tableid, int8_t* szName, int8_t* szNameNew, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetRenameColumnW(uint32_t sesid, uint32_t tableid, uint16_t* szName, uint16_t* szNameNew, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetSetColumnDefaultValueA(uint32_t sesid, uint32_t dbid, int8_t* szTableName, int8_t* szColumnName, void* pvData, uint32_t cbData, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetSetColumnDefaultValueW(uint32_t sesid, uint32_t dbid, uint16_t* szTableName, uint16_t* szColumnName, void* pvData, uint32_t cbData, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetGetTableIndexInfoA(uint32_t sesid, uint32_t tableid, int8_t* szIndexName, void* pvResult, uint32_t cbResult, uint32_t InfoLevel) noexcept;
    int32_t __stdcall WIN32_IMPL_JetGetTableIndexInfoW(uint32_t sesid, uint32_t tableid, uint16_t* szIndexName, void* pvResult, uint32_t cbResult, uint32_t InfoLevel) noexcept;
    int32_t __stdcall WIN32_IMPL_JetGetIndexInfoA(uint32_t sesid, uint32_t dbid, int8_t* szTableName, int8_t* szIndexName, void* pvResult, uint32_t cbResult, uint32_t InfoLevel) noexcept;
    int32_t __stdcall WIN32_IMPL_JetGetIndexInfoW(uint32_t sesid, uint32_t dbid, uint16_t* szTableName, uint16_t* szIndexName, void* pvResult, uint32_t cbResult, uint32_t InfoLevel) noexcept;
    int32_t __stdcall WIN32_IMPL_JetCreateIndexA(uint32_t sesid, uint32_t tableid, int8_t* szIndexName, uint32_t grbit, int8_t* szKey, uint32_t cbKey, uint32_t lDensity) noexcept;
    int32_t __stdcall WIN32_IMPL_JetCreateIndexW(uint32_t sesid, uint32_t tableid, uint16_t* szIndexName, uint32_t grbit, uint16_t* szKey, uint32_t cbKey, uint32_t lDensity) noexcept;
    int32_t __stdcall WIN32_IMPL_JetCreateIndex2A(uint32_t sesid, uint32_t tableid, win32::Windows::Win32::StructuredStorage::JET_INDEXCREATE_A* pindexcreate, uint32_t cIndexCreate) noexcept;
    int32_t __stdcall WIN32_IMPL_JetCreateIndex2W(uint32_t sesid, uint32_t tableid, win32::Windows::Win32::StructuredStorage::JET_INDEXCREATE_W* pindexcreate, uint32_t cIndexCreate) noexcept;
    int32_t __stdcall WIN32_IMPL_JetCreateIndex3A(uint32_t sesid, uint32_t tableid, win32::Windows::Win32::StructuredStorage::JET_INDEXCREATE2_A* pindexcreate, uint32_t cIndexCreate) noexcept;
    int32_t __stdcall WIN32_IMPL_JetCreateIndex3W(uint32_t sesid, uint32_t tableid, win32::Windows::Win32::StructuredStorage::JET_INDEXCREATE2_W* pindexcreate, uint32_t cIndexCreate) noexcept;
    int32_t __stdcall WIN32_IMPL_JetCreateIndex4A(uint32_t sesid, uint32_t tableid, win32::Windows::Win32::StructuredStorage::JET_INDEXCREATE3_A* pindexcreate, uint32_t cIndexCreate) noexcept;
    int32_t __stdcall WIN32_IMPL_JetCreateIndex4W(uint32_t sesid, uint32_t tableid, win32::Windows::Win32::StructuredStorage::JET_INDEXCREATE3_W* pindexcreate, uint32_t cIndexCreate) noexcept;
    int32_t __stdcall WIN32_IMPL_JetDeleteIndexA(uint32_t sesid, uint32_t tableid, int8_t* szIndexName) noexcept;
    int32_t __stdcall WIN32_IMPL_JetDeleteIndexW(uint32_t sesid, uint32_t tableid, uint16_t* szIndexName) noexcept;
    int32_t __stdcall WIN32_IMPL_JetBeginTransaction(uint32_t sesid) noexcept;
    int32_t __stdcall WIN32_IMPL_JetBeginTransaction2(uint32_t sesid, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetBeginTransaction3(uint32_t sesid, int64_t trxid, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetCommitTransaction(uint32_t sesid, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetCommitTransaction2(uint32_t sesid, uint32_t grbit, uint32_t cmsecDurableCommit, win32::Windows::Win32::StructuredStorage::JET_COMMIT_ID* pCommitId) noexcept;
    int32_t __stdcall WIN32_IMPL_JetRollback(uint32_t sesid, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetGetDatabaseInfoA(uint32_t sesid, uint32_t dbid, void* pvResult, uint32_t cbMax, uint32_t InfoLevel) noexcept;
    int32_t __stdcall WIN32_IMPL_JetGetDatabaseInfoW(uint32_t sesid, uint32_t dbid, void* pvResult, uint32_t cbMax, uint32_t InfoLevel) noexcept;
    int32_t __stdcall WIN32_IMPL_JetGetDatabaseFileInfoA(int8_t* szDatabaseName, void* pvResult, uint32_t cbMax, uint32_t InfoLevel) noexcept;
    int32_t __stdcall WIN32_IMPL_JetGetDatabaseFileInfoW(uint16_t* szDatabaseName, void* pvResult, uint32_t cbMax, uint32_t InfoLevel) noexcept;
    int32_t __stdcall WIN32_IMPL_JetOpenDatabaseA(uint32_t sesid, int8_t* szFilename, int8_t* szConnect, uint32_t* pdbid, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetOpenDatabaseW(uint32_t sesid, uint16_t* szFilename, uint16_t* szConnect, uint32_t* pdbid, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetCloseDatabase(uint32_t sesid, uint32_t dbid, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetOpenTableA(uint32_t sesid, uint32_t dbid, int8_t* szTableName, void* pvParameters, uint32_t cbParameters, uint32_t grbit, uint32_t* ptableid) noexcept;
    int32_t __stdcall WIN32_IMPL_JetOpenTableW(uint32_t sesid, uint32_t dbid, uint16_t* szTableName, void* pvParameters, uint32_t cbParameters, uint32_t grbit, uint32_t* ptableid) noexcept;
    int32_t __stdcall WIN32_IMPL_JetSetTableSequential(uint32_t sesid, uint32_t tableid, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetResetTableSequential(uint32_t sesid, uint32_t tableid, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetCloseTable(uint32_t sesid, uint32_t tableid) noexcept;
    int32_t __stdcall WIN32_IMPL_JetDelete(uint32_t sesid, uint32_t tableid) noexcept;
    int32_t __stdcall WIN32_IMPL_JetUpdate(uint32_t sesid, uint32_t tableid, void* pvBookmark, uint32_t cbBookmark, uint32_t* pcbActual) noexcept;
    int32_t __stdcall WIN32_IMPL_JetUpdate2(uint32_t sesid, uint32_t tableid, void* pvBookmark, uint32_t cbBookmark, uint32_t* pcbActual, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetEscrowUpdate(uint32_t sesid, uint32_t tableid, uint32_t columnid, void* pv, uint32_t cbMax, void* pvOld, uint32_t cbOldMax, uint32_t* pcbOldActual, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetRetrieveColumn(uint32_t sesid, uint32_t tableid, uint32_t columnid, void* pvData, uint32_t cbData, uint32_t* pcbActual, uint32_t grbit, win32::Windows::Win32::StructuredStorage::JET_RETINFO* pretinfo) noexcept;
    int32_t __stdcall WIN32_IMPL_JetRetrieveColumns(uint32_t sesid, uint32_t tableid, win32::Windows::Win32::StructuredStorage::JET_RETRIEVECOLUMN* pretrievecolumn, uint32_t cretrievecolumn) noexcept;
    int32_t __stdcall WIN32_IMPL_JetEnumerateColumns(uint32_t sesid, uint32_t tableid, uint32_t cEnumColumnId, win32::Windows::Win32::StructuredStorage::JET_ENUMCOLUMNID* rgEnumColumnId, uint32_t* pcEnumColumn, win32::Windows::Win32::StructuredStorage::JET_ENUMCOLUMN** prgEnumColumn, win32::Windows::Win32::StructuredStorage::JET_PFNREALLOC* pfnRealloc, void* pvReallocContext, uint32_t cbDataMost, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetGetRecordSize(uint32_t sesid, uint32_t tableid, win32::Windows::Win32::StructuredStorage::JET_RECSIZE* precsize, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetGetRecordSize2(uint32_t sesid, uint32_t tableid, win32::Windows::Win32::StructuredStorage::JET_RECSIZE2* precsize, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetSetColumn(uint32_t sesid, uint32_t tableid, uint32_t columnid, void* pvData, uint32_t cbData, uint32_t grbit, win32::Windows::Win32::StructuredStorage::JET_SETINFO* psetinfo) noexcept;
    int32_t __stdcall WIN32_IMPL_JetSetColumns(uint32_t sesid, uint32_t tableid, win32::Windows::Win32::StructuredStorage::JET_SETCOLUMN* psetcolumn, uint32_t csetcolumn) noexcept;
    int32_t __stdcall WIN32_IMPL_JetPrepareUpdate(uint32_t sesid, uint32_t tableid, uint32_t prep) noexcept;
    int32_t __stdcall WIN32_IMPL_JetGetRecordPosition(uint32_t sesid, uint32_t tableid, win32::Windows::Win32::StructuredStorage::JET_RECPOS* precpos, uint32_t cbRecpos) noexcept;
    int32_t __stdcall WIN32_IMPL_JetGotoPosition(uint32_t sesid, uint32_t tableid, win32::Windows::Win32::StructuredStorage::JET_RECPOS* precpos) noexcept;
    int32_t __stdcall WIN32_IMPL_JetGetCursorInfo(uint32_t sesid, uint32_t tableid, void* pvResult, uint32_t cbMax, uint32_t InfoLevel) noexcept;
    int32_t __stdcall WIN32_IMPL_JetDupCursor(uint32_t sesid, uint32_t tableid, uint32_t* ptableid, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetGetCurrentIndexA(uint32_t sesid, uint32_t tableid, int8_t* szIndexName, uint32_t cbIndexName) noexcept;
    int32_t __stdcall WIN32_IMPL_JetGetCurrentIndexW(uint32_t sesid, uint32_t tableid, uint16_t* szIndexName, uint32_t cbIndexName) noexcept;
    int32_t __stdcall WIN32_IMPL_JetSetCurrentIndexA(uint32_t sesid, uint32_t tableid, int8_t* szIndexName) noexcept;
    int32_t __stdcall WIN32_IMPL_JetSetCurrentIndexW(uint32_t sesid, uint32_t tableid, uint16_t* szIndexName) noexcept;
    int32_t __stdcall WIN32_IMPL_JetSetCurrentIndex2A(uint32_t sesid, uint32_t tableid, int8_t* szIndexName, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetSetCurrentIndex2W(uint32_t sesid, uint32_t tableid, uint16_t* szIndexName, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetSetCurrentIndex3A(uint32_t sesid, uint32_t tableid, int8_t* szIndexName, uint32_t grbit, uint32_t itagSequence) noexcept;
    int32_t __stdcall WIN32_IMPL_JetSetCurrentIndex3W(uint32_t sesid, uint32_t tableid, uint16_t* szIndexName, uint32_t grbit, uint32_t itagSequence) noexcept;
    int32_t __stdcall WIN32_IMPL_JetSetCurrentIndex4A(uint32_t sesid, uint32_t tableid, int8_t* szIndexName, win32::Windows::Win32::StructuredStorage::JET_INDEXID* pindexid, uint32_t grbit, uint32_t itagSequence) noexcept;
    int32_t __stdcall WIN32_IMPL_JetSetCurrentIndex4W(uint32_t sesid, uint32_t tableid, uint16_t* szIndexName, win32::Windows::Win32::StructuredStorage::JET_INDEXID* pindexid, uint32_t grbit, uint32_t itagSequence) noexcept;
    int32_t __stdcall WIN32_IMPL_JetMove(uint32_t sesid, uint32_t tableid, int32_t cRow, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetSetCursorFilter(uint32_t sesid, uint32_t tableid, win32::Windows::Win32::StructuredStorage::JET_INDEX_COLUMN* rgColumnFilters, uint32_t cColumnFilters, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetGetLock(uint32_t sesid, uint32_t tableid, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetMakeKey(uint32_t sesid, uint32_t tableid, void* pvData, uint32_t cbData, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetSeek(uint32_t sesid, uint32_t tableid, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetPrereadKeys(uint32_t sesid, uint32_t tableid, void** rgpvKeys, uint32_t* rgcbKeys, int32_t ckeys, int32_t* pckeysPreread, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetPrereadIndexRanges(uint32_t sesid, uint32_t tableid, win32::Windows::Win32::StructuredStorage::JET_INDEX_RANGE* rgIndexRanges, uint32_t cIndexRanges, uint32_t* pcRangesPreread, uint32_t* rgcolumnidPreread, uint32_t ccolumnidPreread, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetGetBookmark(uint32_t sesid, uint32_t tableid, void* pvBookmark, uint32_t cbMax, uint32_t* pcbActual) noexcept;
    int32_t __stdcall WIN32_IMPL_JetGetSecondaryIndexBookmark(uint32_t sesid, uint32_t tableid, void* pvSecondaryKey, uint32_t cbSecondaryKeyMax, uint32_t* pcbSecondaryKeyActual, void* pvPrimaryBookmark, uint32_t cbPrimaryBookmarkMax, uint32_t* pcbPrimaryBookmarkActual, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetCompactA(uint32_t sesid, int8_t* szDatabaseSrc, int8_t* szDatabaseDest, win32::Windows::Win32::StructuredStorage::JET_PFNSTATUS* pfnStatus, win32::Windows::Win32::StructuredStorage::tagCONVERT_A* pconvert, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetCompactW(uint32_t sesid, uint16_t* szDatabaseSrc, uint16_t* szDatabaseDest, win32::Windows::Win32::StructuredStorage::JET_PFNSTATUS* pfnStatus, win32::Windows::Win32::StructuredStorage::tagCONVERT_W* pconvert, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetDefragmentA(uint32_t sesid, uint32_t dbid, int8_t* szTableName, uint32_t* pcPasses, uint32_t* pcSeconds, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetDefragmentW(uint32_t sesid, uint32_t dbid, uint16_t* szTableName, uint32_t* pcPasses, uint32_t* pcSeconds, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetDefragment2A(uint32_t sesid, uint32_t dbid, int8_t* szTableName, uint32_t* pcPasses, uint32_t* pcSeconds, win32::Windows::Win32::StructuredStorage::JET_CALLBACK* callback, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetDefragment2W(uint32_t sesid, uint32_t dbid, uint16_t* szTableName, uint32_t* pcPasses, uint32_t* pcSeconds, win32::Windows::Win32::StructuredStorage::JET_CALLBACK* callback, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetDefragment3A(uint32_t sesid, int8_t* szDatabaseName, int8_t* szTableName, uint32_t* pcPasses, uint32_t* pcSeconds, win32::Windows::Win32::StructuredStorage::JET_CALLBACK* callback, void* pvContext, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetDefragment3W(uint32_t sesid, uint16_t* szDatabaseName, uint16_t* szTableName, uint32_t* pcPasses, uint32_t* pcSeconds, win32::Windows::Win32::StructuredStorage::JET_CALLBACK* callback, void* pvContext, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetSetDatabaseSizeA(uint32_t sesid, int8_t* szDatabaseName, uint32_t cpg, uint32_t* pcpgReal) noexcept;
    int32_t __stdcall WIN32_IMPL_JetSetDatabaseSizeW(uint32_t sesid, uint16_t* szDatabaseName, uint32_t cpg, uint32_t* pcpgReal) noexcept;
    int32_t __stdcall WIN32_IMPL_JetGrowDatabase(uint32_t sesid, uint32_t dbid, uint32_t cpg, uint32_t* pcpgReal) noexcept;
    int32_t __stdcall WIN32_IMPL_JetResizeDatabase(uint32_t sesid, uint32_t dbid, uint32_t cpgTarget, uint32_t* pcpgActual, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetSetSessionContext(uint32_t sesid, uint32_t ulContext) noexcept;
    int32_t __stdcall WIN32_IMPL_JetResetSessionContext(uint32_t sesid) noexcept;
    int32_t __stdcall WIN32_IMPL_JetGotoBookmark(uint32_t sesid, uint32_t tableid, void* pvBookmark, uint32_t cbBookmark) noexcept;
    int32_t __stdcall WIN32_IMPL_JetGotoSecondaryIndexBookmark(uint32_t sesid, uint32_t tableid, void* pvSecondaryKey, uint32_t cbSecondaryKey, void* pvPrimaryBookmark, uint32_t cbPrimaryBookmark, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetIntersectIndexes(uint32_t sesid, win32::Windows::Win32::StructuredStorage::JET_INDEXRANGE* rgindexrange, uint32_t cindexrange, win32::Windows::Win32::StructuredStorage::JET_RECORDLIST* precordlist, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetComputeStats(uint32_t sesid, uint32_t tableid) noexcept;
    int32_t __stdcall WIN32_IMPL_JetOpenTempTable(uint32_t sesid, win32::Windows::Win32::StructuredStorage::JET_COLUMNDEF* prgcolumndef, uint32_t ccolumn, uint32_t grbit, uint32_t* ptableid, uint32_t* prgcolumnid) noexcept;
    int32_t __stdcall WIN32_IMPL_JetOpenTempTable2(uint32_t sesid, win32::Windows::Win32::StructuredStorage::JET_COLUMNDEF* prgcolumndef, uint32_t ccolumn, uint32_t lcid, uint32_t grbit, uint32_t* ptableid, uint32_t* prgcolumnid) noexcept;
    int32_t __stdcall WIN32_IMPL_JetOpenTempTable3(uint32_t sesid, win32::Windows::Win32::StructuredStorage::JET_COLUMNDEF* prgcolumndef, uint32_t ccolumn, win32::Windows::Win32::StructuredStorage::JET_UNICODEINDEX* pidxunicode, uint32_t grbit, uint32_t* ptableid, uint32_t* prgcolumnid) noexcept;
    int32_t __stdcall WIN32_IMPL_JetOpenTemporaryTable(uint32_t sesid, win32::Windows::Win32::StructuredStorage::JET_OPENTEMPORARYTABLE* popentemporarytable) noexcept;
    int32_t __stdcall WIN32_IMPL_JetOpenTemporaryTable2(uint32_t sesid, win32::Windows::Win32::StructuredStorage::JET_OPENTEMPORARYTABLE2* popentemporarytable) noexcept;
    int32_t __stdcall WIN32_IMPL_JetBackupA(int8_t* szBackupPath, uint32_t grbit, win32::Windows::Win32::StructuredStorage::JET_PFNSTATUS* pfnStatus) noexcept;
    int32_t __stdcall WIN32_IMPL_JetBackupW(uint16_t* szBackupPath, uint32_t grbit, win32::Windows::Win32::StructuredStorage::JET_PFNSTATUS* pfnStatus) noexcept;
    int32_t __stdcall WIN32_IMPL_JetBackupInstanceA(uint32_t instance, int8_t* szBackupPath, uint32_t grbit, win32::Windows::Win32::StructuredStorage::JET_PFNSTATUS* pfnStatus) noexcept;
    int32_t __stdcall WIN32_IMPL_JetBackupInstanceW(uint32_t instance, uint16_t* szBackupPath, uint32_t grbit, win32::Windows::Win32::StructuredStorage::JET_PFNSTATUS* pfnStatus) noexcept;
    int32_t __stdcall WIN32_IMPL_JetRestoreA(int8_t* szSource, win32::Windows::Win32::StructuredStorage::JET_PFNSTATUS* pfn) noexcept;
    int32_t __stdcall WIN32_IMPL_JetRestoreW(uint16_t* szSource, win32::Windows::Win32::StructuredStorage::JET_PFNSTATUS* pfn) noexcept;
    int32_t __stdcall WIN32_IMPL_JetRestore2A(int8_t* sz, int8_t* szDest, win32::Windows::Win32::StructuredStorage::JET_PFNSTATUS* pfn) noexcept;
    int32_t __stdcall WIN32_IMPL_JetRestore2W(uint16_t* sz, uint16_t* szDest, win32::Windows::Win32::StructuredStorage::JET_PFNSTATUS* pfn) noexcept;
    int32_t __stdcall WIN32_IMPL_JetRestoreInstanceA(uint32_t instance, int8_t* sz, int8_t* szDest, win32::Windows::Win32::StructuredStorage::JET_PFNSTATUS* pfn) noexcept;
    int32_t __stdcall WIN32_IMPL_JetRestoreInstanceW(uint32_t instance, uint16_t* sz, uint16_t* szDest, win32::Windows::Win32::StructuredStorage::JET_PFNSTATUS* pfn) noexcept;
    int32_t __stdcall WIN32_IMPL_JetSetIndexRange(uint32_t sesid, uint32_t tableidSrc, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetIndexRecordCount(uint32_t sesid, uint32_t tableid, uint32_t* pcrec, uint32_t crecMax) noexcept;
    int32_t __stdcall WIN32_IMPL_JetRetrieveKey(uint32_t sesid, uint32_t tableid, void* pvKey, uint32_t cbMax, uint32_t* pcbActual, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetBeginExternalBackup(uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetBeginExternalBackupInstance(uint32_t instance, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetGetAttachInfoA(int8_t* szzDatabases, uint32_t cbMax, uint32_t* pcbActual) noexcept;
    int32_t __stdcall WIN32_IMPL_JetGetAttachInfoW(uint16_t* wszzDatabases, uint32_t cbMax, uint32_t* pcbActual) noexcept;
    int32_t __stdcall WIN32_IMPL_JetGetAttachInfoInstanceA(uint32_t instance, int8_t* szzDatabases, uint32_t cbMax, uint32_t* pcbActual) noexcept;
    int32_t __stdcall WIN32_IMPL_JetGetAttachInfoInstanceW(uint32_t instance, uint16_t* szzDatabases, uint32_t cbMax, uint32_t* pcbActual) noexcept;
    int32_t __stdcall WIN32_IMPL_JetOpenFileA(int8_t* szFileName, uint32_t* phfFile, uint32_t* pulFileSizeLow, uint32_t* pulFileSizeHigh) noexcept;
    int32_t __stdcall WIN32_IMPL_JetOpenFileW(uint16_t* szFileName, uint32_t* phfFile, uint32_t* pulFileSizeLow, uint32_t* pulFileSizeHigh) noexcept;
    int32_t __stdcall WIN32_IMPL_JetOpenFileInstanceA(uint32_t instance, int8_t* szFileName, uint32_t* phfFile, uint32_t* pulFileSizeLow, uint32_t* pulFileSizeHigh) noexcept;
    int32_t __stdcall WIN32_IMPL_JetOpenFileInstanceW(uint32_t instance, uint16_t* szFileName, uint32_t* phfFile, uint32_t* pulFileSizeLow, uint32_t* pulFileSizeHigh) noexcept;
    int32_t __stdcall WIN32_IMPL_JetReadFile(uint32_t hfFile, void* pv, uint32_t cb, uint32_t* pcbActual) noexcept;
    int32_t __stdcall WIN32_IMPL_JetReadFileInstance(uint32_t instance, uint32_t hfFile, void* pv, uint32_t cb, uint32_t* pcbActual) noexcept;
    int32_t __stdcall WIN32_IMPL_JetCloseFile(uint32_t hfFile) noexcept;
    int32_t __stdcall WIN32_IMPL_JetCloseFileInstance(uint32_t instance, uint32_t hfFile) noexcept;
    int32_t __stdcall WIN32_IMPL_JetGetLogInfoA(int8_t* szzLogs, uint32_t cbMax, uint32_t* pcbActual) noexcept;
    int32_t __stdcall WIN32_IMPL_JetGetLogInfoW(uint16_t* szzLogs, uint32_t cbMax, uint32_t* pcbActual) noexcept;
    int32_t __stdcall WIN32_IMPL_JetGetLogInfoInstanceA(uint32_t instance, int8_t* szzLogs, uint32_t cbMax, uint32_t* pcbActual) noexcept;
    int32_t __stdcall WIN32_IMPL_JetGetLogInfoInstanceW(uint32_t instance, uint16_t* wszzLogs, uint32_t cbMax, uint32_t* pcbActual) noexcept;
    int32_t __stdcall WIN32_IMPL_JetGetLogInfoInstance2A(uint32_t instance, int8_t* szzLogs, uint32_t cbMax, uint32_t* pcbActual, win32::Windows::Win32::StructuredStorage::JET_LOGINFO_A* pLogInfo) noexcept;
    int32_t __stdcall WIN32_IMPL_JetGetLogInfoInstance2W(uint32_t instance, uint16_t* wszzLogs, uint32_t cbMax, uint32_t* pcbActual, win32::Windows::Win32::StructuredStorage::JET_LOGINFO_W* pLogInfo) noexcept;
    int32_t __stdcall WIN32_IMPL_JetGetTruncateLogInfoInstanceA(uint32_t instance, int8_t* szzLogs, uint32_t cbMax, uint32_t* pcbActual) noexcept;
    int32_t __stdcall WIN32_IMPL_JetGetTruncateLogInfoInstanceW(uint32_t instance, uint16_t* wszzLogs, uint32_t cbMax, uint32_t* pcbActual) noexcept;
    int32_t __stdcall WIN32_IMPL_JetTruncateLog() noexcept;
    int32_t __stdcall WIN32_IMPL_JetTruncateLogInstance(uint32_t instance) noexcept;
    int32_t __stdcall WIN32_IMPL_JetEndExternalBackup() noexcept;
    int32_t __stdcall WIN32_IMPL_JetEndExternalBackupInstance(uint32_t instance) noexcept;
    int32_t __stdcall WIN32_IMPL_JetEndExternalBackupInstance2(uint32_t instance, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetExternalRestoreA(int8_t* szCheckpointFilePath, int8_t* szLogPath, win32::Windows::Win32::StructuredStorage::JET_RSTMAP_A* rgrstmap, int32_t crstfilemap, int8_t* szBackupLogPath, int32_t genLow, int32_t genHigh, win32::Windows::Win32::StructuredStorage::JET_PFNSTATUS* pfn) noexcept;
    int32_t __stdcall WIN32_IMPL_JetExternalRestoreW(uint16_t* szCheckpointFilePath, uint16_t* szLogPath, win32::Windows::Win32::StructuredStorage::JET_RSTMAP_W* rgrstmap, int32_t crstfilemap, uint16_t* szBackupLogPath, int32_t genLow, int32_t genHigh, win32::Windows::Win32::StructuredStorage::JET_PFNSTATUS* pfn) noexcept;
    int32_t __stdcall WIN32_IMPL_JetExternalRestore2A(int8_t* szCheckpointFilePath, int8_t* szLogPath, win32::Windows::Win32::StructuredStorage::JET_RSTMAP_A* rgrstmap, int32_t crstfilemap, int8_t* szBackupLogPath, win32::Windows::Win32::StructuredStorage::JET_LOGINFO_A* pLogInfo, int8_t* szTargetInstanceName, int8_t* szTargetInstanceLogPath, int8_t* szTargetInstanceCheckpointPath, win32::Windows::Win32::StructuredStorage::JET_PFNSTATUS* pfn) noexcept;
    int32_t __stdcall WIN32_IMPL_JetExternalRestore2W(uint16_t* szCheckpointFilePath, uint16_t* szLogPath, win32::Windows::Win32::StructuredStorage::JET_RSTMAP_W* rgrstmap, int32_t crstfilemap, uint16_t* szBackupLogPath, win32::Windows::Win32::StructuredStorage::JET_LOGINFO_W* pLogInfo, uint16_t* szTargetInstanceName, uint16_t* szTargetInstanceLogPath, uint16_t* szTargetInstanceCheckpointPath, win32::Windows::Win32::StructuredStorage::JET_PFNSTATUS* pfn) noexcept;
    int32_t __stdcall WIN32_IMPL_JetRegisterCallback(uint32_t sesid, uint32_t tableid, uint32_t cbtyp, win32::Windows::Win32::StructuredStorage::JET_CALLBACK* pCallback, void* pvContext, uint32_t* phCallbackId) noexcept;
    int32_t __stdcall WIN32_IMPL_JetUnregisterCallback(uint32_t sesid, uint32_t tableid, uint32_t cbtyp, uint32_t hCallbackId) noexcept;
    int32_t __stdcall WIN32_IMPL_JetGetInstanceInfoA(uint32_t* pcInstanceInfo, win32::Windows::Win32::StructuredStorage::JET_INSTANCE_INFO_A** paInstanceInfo) noexcept;
    int32_t __stdcall WIN32_IMPL_JetGetInstanceInfoW(uint32_t* pcInstanceInfo, win32::Windows::Win32::StructuredStorage::JET_INSTANCE_INFO_W** paInstanceInfo) noexcept;
    int32_t __stdcall WIN32_IMPL_JetFreeBuffer(int8_t* pbBuf) noexcept;
    int32_t __stdcall WIN32_IMPL_JetSetLS(uint32_t sesid, uint32_t tableid, uint32_t ls, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetGetLS(uint32_t sesid, uint32_t tableid, uint32_t* pls, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetOSSnapshotPrepare(uint32_t* psnapId, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetOSSnapshotPrepareInstance(uint32_t snapId, uint32_t instance, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetOSSnapshotFreezeA(uint32_t snapId, uint32_t* pcInstanceInfo, win32::Windows::Win32::StructuredStorage::JET_INSTANCE_INFO_A** paInstanceInfo, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetOSSnapshotFreezeW(uint32_t snapId, uint32_t* pcInstanceInfo, win32::Windows::Win32::StructuredStorage::JET_INSTANCE_INFO_W** paInstanceInfo, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetOSSnapshotThaw(uint32_t snapId, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetOSSnapshotAbort(uint32_t snapId, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetOSSnapshotTruncateLog(uint32_t snapId, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetOSSnapshotTruncateLogInstance(uint32_t snapId, uint32_t instance, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetOSSnapshotGetFreezeInfoA(uint32_t snapId, uint32_t* pcInstanceInfo, win32::Windows::Win32::StructuredStorage::JET_INSTANCE_INFO_A** paInstanceInfo, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetOSSnapshotGetFreezeInfoW(uint32_t snapId, uint32_t* pcInstanceInfo, win32::Windows::Win32::StructuredStorage::JET_INSTANCE_INFO_W** paInstanceInfo, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetOSSnapshotEnd(uint32_t snapId, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetConfigureProcessForCrashDump(uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetGetErrorInfoW(void* pvContext, void* pvResult, uint32_t cbMax, uint32_t InfoLevel, uint32_t grbit) noexcept;
    int32_t __stdcall WIN32_IMPL_JetSetSessionParameter(uint32_t sesid, uint32_t sesparamid, void* pvParam, uint32_t cbParam) noexcept;
    int32_t __stdcall WIN32_IMPL_JetGetSessionParameter(uint32_t sesid, uint32_t sesparamid, void* pvParam, uint32_t cbParamMax, uint32_t* pcbParamActual) noexcept;
}
WIN32_IMPL_LINK(CreateStreamOnHGlobal, 12)
WIN32_IMPL_LINK(GetHGlobalFromStream, 8)
WIN32_IMPL_LINK(PropVariantCopy, 8)
WIN32_IMPL_LINK(PropVariantClear, 4)
WIN32_IMPL_LINK(FreePropVariantArray, 8)
WIN32_IMPL_LINK(WriteFmtUserTypeStg, 12)
WIN32_IMPL_LINK(ReadFmtUserTypeStg, 12)
WIN32_IMPL_LINK(OleConvertOLESTREAMToIStorage, 12)
WIN32_IMPL_LINK(OleConvertIStorageToOLESTREAM, 8)
WIN32_IMPL_LINK(SetConvertStg, 8)
WIN32_IMPL_LINK(OleConvertIStorageToOLESTREAMEx, 28)
WIN32_IMPL_LINK(OleConvertOLESTREAMToIStorageEx, 28)
WIN32_IMPL_LINK(StgSerializePropVariant, 12)
WIN32_IMPL_LINK(StgDeserializePropVariant, 12)
WIN32_IMPL_LINK(StgCreateDocfile, 16)
WIN32_IMPL_LINK(StgCreateDocfileOnILockBytes, 16)
WIN32_IMPL_LINK(StgOpenStorage, 24)
WIN32_IMPL_LINK(StgOpenStorageOnILockBytes, 24)
WIN32_IMPL_LINK(StgIsStorageFile, 4)
WIN32_IMPL_LINK(StgIsStorageILockBytes, 4)
WIN32_IMPL_LINK(StgSetTimes, 16)
WIN32_IMPL_LINK(StgCreateStorageEx, 32)
WIN32_IMPL_LINK(StgOpenStorageEx, 32)
WIN32_IMPL_LINK(StgCreatePropStg, 24)
WIN32_IMPL_LINK(StgOpenPropStg, 20)
WIN32_IMPL_LINK(StgCreatePropSetStg, 12)
WIN32_IMPL_LINK(FmtIdToPropStgName, 8)
WIN32_IMPL_LINK(PropStgNameToFmtId, 8)
WIN32_IMPL_LINK(ReadClassStg, 8)
WIN32_IMPL_LINK(WriteClassStg, 8)
WIN32_IMPL_LINK(ReadClassStm, 8)
WIN32_IMPL_LINK(WriteClassStm, 8)
WIN32_IMPL_LINK(GetHGlobalFromILockBytes, 8)
WIN32_IMPL_LINK(CreateILockBytesOnHGlobal, 12)
WIN32_IMPL_LINK(GetConvertStg, 4)
WIN32_IMPL_LINK(CoBuildVersion, 0)
WIN32_IMPL_LINK(DcomChannelSetHResult, 12)
WIN32_IMPL_LINK(StgOpenAsyncDocfileOnIFillLockBytes, 16)
WIN32_IMPL_LINK(StgGetIFillLockBytesOnILockBytes, 8)
WIN32_IMPL_LINK(StgGetIFillLockBytesOnFile, 8)
WIN32_IMPL_LINK(StgOpenLayoutDocfile, 16)
WIN32_IMPL_LINK(StgConvertVariantToProperty, 28)
WIN32_IMPL_LINK(StgConvertPropertyToVariant, 16)
WIN32_IMPL_LINK(CreateStdProgressIndicator, 16)
WIN32_IMPL_LINK(StgPropertyLengthAsVariant, 16)
WIN32_IMPL_LINK(JetInit, 4)
WIN32_IMPL_LINK(JetInit2, 8)
WIN32_IMPL_LINK(JetInit3A, 12)
WIN32_IMPL_LINK(JetInit3W, 12)
WIN32_IMPL_LINK(JetCreateInstanceA, 8)
WIN32_IMPL_LINK(JetCreateInstanceW, 8)
WIN32_IMPL_LINK(JetCreateInstance2A, 16)
WIN32_IMPL_LINK(JetCreateInstance2W, 16)
WIN32_IMPL_LINK(JetGetInstanceMiscInfo, 16)
WIN32_IMPL_LINK(JetTerm, 4)
WIN32_IMPL_LINK(JetTerm2, 8)
WIN32_IMPL_LINK(JetStopService, 0)
WIN32_IMPL_LINK(JetStopServiceInstance, 4)
WIN32_IMPL_LINK(JetStopServiceInstance2, 8)
WIN32_IMPL_LINK(JetStopBackup, 0)
WIN32_IMPL_LINK(JetStopBackupInstance, 4)
WIN32_IMPL_LINK(JetSetSystemParameterA, 20)
WIN32_IMPL_LINK(JetSetSystemParameterW, 20)
WIN32_IMPL_LINK(JetGetSystemParameterA, 24)
WIN32_IMPL_LINK(JetGetSystemParameterW, 24)
WIN32_IMPL_LINK(JetEnableMultiInstanceA, 12)
WIN32_IMPL_LINK(JetEnableMultiInstanceW, 12)
WIN32_IMPL_LINK(JetGetThreadStats, 8)
WIN32_IMPL_LINK(JetBeginSessionA, 16)
WIN32_IMPL_LINK(JetBeginSessionW, 16)
WIN32_IMPL_LINK(JetDupSession, 8)
WIN32_IMPL_LINK(JetEndSession, 8)
WIN32_IMPL_LINK(JetGetVersion, 8)
WIN32_IMPL_LINK(JetIdle, 8)
WIN32_IMPL_LINK(JetCreateDatabaseA, 20)
WIN32_IMPL_LINK(JetCreateDatabaseW, 20)
WIN32_IMPL_LINK(JetCreateDatabase2A, 20)
WIN32_IMPL_LINK(JetCreateDatabase2W, 20)
WIN32_IMPL_LINK(JetAttachDatabaseA, 12)
WIN32_IMPL_LINK(JetAttachDatabaseW, 12)
WIN32_IMPL_LINK(JetAttachDatabase2A, 16)
WIN32_IMPL_LINK(JetAttachDatabase2W, 16)
WIN32_IMPL_LINK(JetDetachDatabaseA, 8)
WIN32_IMPL_LINK(JetDetachDatabaseW, 8)
WIN32_IMPL_LINK(JetDetachDatabase2A, 12)
WIN32_IMPL_LINK(JetDetachDatabase2W, 12)
WIN32_IMPL_LINK(JetGetObjectInfoA, 32)
WIN32_IMPL_LINK(JetGetObjectInfoW, 32)
WIN32_IMPL_LINK(JetGetTableInfoA, 20)
WIN32_IMPL_LINK(JetGetTableInfoW, 20)
WIN32_IMPL_LINK(JetCreateTableA, 24)
WIN32_IMPL_LINK(JetCreateTableW, 24)
WIN32_IMPL_LINK(JetCreateTableColumnIndexA, 12)
WIN32_IMPL_LINK(JetCreateTableColumnIndexW, 12)
WIN32_IMPL_LINK(JetCreateTableColumnIndex2A, 12)
WIN32_IMPL_LINK(JetCreateTableColumnIndex2W, 12)
WIN32_IMPL_LINK(JetCreateTableColumnIndex3A, 12)
WIN32_IMPL_LINK(JetCreateTableColumnIndex3W, 12)
WIN32_IMPL_LINK(JetCreateTableColumnIndex4A, 12)
WIN32_IMPL_LINK(JetCreateTableColumnIndex4W, 12)
WIN32_IMPL_LINK(JetDeleteTableA, 12)
WIN32_IMPL_LINK(JetDeleteTableW, 12)
WIN32_IMPL_LINK(JetRenameTableA, 16)
WIN32_IMPL_LINK(JetRenameTableW, 16)
WIN32_IMPL_LINK(JetGetTableColumnInfoA, 24)
WIN32_IMPL_LINK(JetGetTableColumnInfoW, 24)
WIN32_IMPL_LINK(JetGetColumnInfoA, 28)
WIN32_IMPL_LINK(JetGetColumnInfoW, 28)
WIN32_IMPL_LINK(JetAddColumnA, 28)
WIN32_IMPL_LINK(JetAddColumnW, 28)
WIN32_IMPL_LINK(JetDeleteColumnA, 12)
WIN32_IMPL_LINK(JetDeleteColumnW, 12)
WIN32_IMPL_LINK(JetDeleteColumn2A, 16)
WIN32_IMPL_LINK(JetDeleteColumn2W, 16)
WIN32_IMPL_LINK(JetRenameColumnA, 20)
WIN32_IMPL_LINK(JetRenameColumnW, 20)
WIN32_IMPL_LINK(JetSetColumnDefaultValueA, 28)
WIN32_IMPL_LINK(JetSetColumnDefaultValueW, 28)
WIN32_IMPL_LINK(JetGetTableIndexInfoA, 24)
WIN32_IMPL_LINK(JetGetTableIndexInfoW, 24)
WIN32_IMPL_LINK(JetGetIndexInfoA, 28)
WIN32_IMPL_LINK(JetGetIndexInfoW, 28)
WIN32_IMPL_LINK(JetCreateIndexA, 28)
WIN32_IMPL_LINK(JetCreateIndexW, 28)
WIN32_IMPL_LINK(JetCreateIndex2A, 16)
WIN32_IMPL_LINK(JetCreateIndex2W, 16)
WIN32_IMPL_LINK(JetCreateIndex3A, 16)
WIN32_IMPL_LINK(JetCreateIndex3W, 16)
WIN32_IMPL_LINK(JetCreateIndex4A, 16)
WIN32_IMPL_LINK(JetCreateIndex4W, 16)
WIN32_IMPL_LINK(JetDeleteIndexA, 12)
WIN32_IMPL_LINK(JetDeleteIndexW, 12)
WIN32_IMPL_LINK(JetBeginTransaction, 4)
WIN32_IMPL_LINK(JetBeginTransaction2, 8)
WIN32_IMPL_LINK(JetBeginTransaction3, 16)
WIN32_IMPL_LINK(JetCommitTransaction, 8)
WIN32_IMPL_LINK(JetCommitTransaction2, 16)
WIN32_IMPL_LINK(JetRollback, 8)
WIN32_IMPL_LINK(JetGetDatabaseInfoA, 20)
WIN32_IMPL_LINK(JetGetDatabaseInfoW, 20)
WIN32_IMPL_LINK(JetGetDatabaseFileInfoA, 16)
WIN32_IMPL_LINK(JetGetDatabaseFileInfoW, 16)
WIN32_IMPL_LINK(JetOpenDatabaseA, 20)
WIN32_IMPL_LINK(JetOpenDatabaseW, 20)
WIN32_IMPL_LINK(JetCloseDatabase, 12)
WIN32_IMPL_LINK(JetOpenTableA, 28)
WIN32_IMPL_LINK(JetOpenTableW, 28)
WIN32_IMPL_LINK(JetSetTableSequential, 12)
WIN32_IMPL_LINK(JetResetTableSequential, 12)
WIN32_IMPL_LINK(JetCloseTable, 8)
WIN32_IMPL_LINK(JetDelete, 8)
WIN32_IMPL_LINK(JetUpdate, 20)
WIN32_IMPL_LINK(JetUpdate2, 24)
WIN32_IMPL_LINK(JetEscrowUpdate, 36)
WIN32_IMPL_LINK(JetRetrieveColumn, 32)
WIN32_IMPL_LINK(JetRetrieveColumns, 16)
WIN32_IMPL_LINK(JetEnumerateColumns, 40)
WIN32_IMPL_LINK(JetGetRecordSize, 16)
WIN32_IMPL_LINK(JetGetRecordSize2, 16)
WIN32_IMPL_LINK(JetSetColumn, 28)
WIN32_IMPL_LINK(JetSetColumns, 16)
WIN32_IMPL_LINK(JetPrepareUpdate, 12)
WIN32_IMPL_LINK(JetGetRecordPosition, 16)
WIN32_IMPL_LINK(JetGotoPosition, 12)
WIN32_IMPL_LINK(JetGetCursorInfo, 20)
WIN32_IMPL_LINK(JetDupCursor, 16)
WIN32_IMPL_LINK(JetGetCurrentIndexA, 16)
WIN32_IMPL_LINK(JetGetCurrentIndexW, 16)
WIN32_IMPL_LINK(JetSetCurrentIndexA, 12)
WIN32_IMPL_LINK(JetSetCurrentIndexW, 12)
WIN32_IMPL_LINK(JetSetCurrentIndex2A, 16)
WIN32_IMPL_LINK(JetSetCurrentIndex2W, 16)
WIN32_IMPL_LINK(JetSetCurrentIndex3A, 20)
WIN32_IMPL_LINK(JetSetCurrentIndex3W, 20)
WIN32_IMPL_LINK(JetSetCurrentIndex4A, 24)
WIN32_IMPL_LINK(JetSetCurrentIndex4W, 24)
WIN32_IMPL_LINK(JetMove, 16)
WIN32_IMPL_LINK(JetSetCursorFilter, 20)
WIN32_IMPL_LINK(JetGetLock, 12)
WIN32_IMPL_LINK(JetMakeKey, 20)
WIN32_IMPL_LINK(JetSeek, 12)
WIN32_IMPL_LINK(JetPrereadKeys, 28)
WIN32_IMPL_LINK(JetPrereadIndexRanges, 32)
WIN32_IMPL_LINK(JetGetBookmark, 20)
WIN32_IMPL_LINK(JetGetSecondaryIndexBookmark, 36)
WIN32_IMPL_LINK(JetCompactA, 24)
WIN32_IMPL_LINK(JetCompactW, 24)
WIN32_IMPL_LINK(JetDefragmentA, 24)
WIN32_IMPL_LINK(JetDefragmentW, 24)
WIN32_IMPL_LINK(JetDefragment2A, 28)
WIN32_IMPL_LINK(JetDefragment2W, 28)
WIN32_IMPL_LINK(JetDefragment3A, 32)
WIN32_IMPL_LINK(JetDefragment3W, 32)
WIN32_IMPL_LINK(JetSetDatabaseSizeA, 16)
WIN32_IMPL_LINK(JetSetDatabaseSizeW, 16)
WIN32_IMPL_LINK(JetGrowDatabase, 16)
WIN32_IMPL_LINK(JetResizeDatabase, 20)
WIN32_IMPL_LINK(JetSetSessionContext, 8)
WIN32_IMPL_LINK(JetResetSessionContext, 4)
WIN32_IMPL_LINK(JetGotoBookmark, 16)
WIN32_IMPL_LINK(JetGotoSecondaryIndexBookmark, 28)
WIN32_IMPL_LINK(JetIntersectIndexes, 20)
WIN32_IMPL_LINK(JetComputeStats, 8)
WIN32_IMPL_LINK(JetOpenTempTable, 24)
WIN32_IMPL_LINK(JetOpenTempTable2, 28)
WIN32_IMPL_LINK(JetOpenTempTable3, 28)
WIN32_IMPL_LINK(JetOpenTemporaryTable, 8)
WIN32_IMPL_LINK(JetOpenTemporaryTable2, 8)
WIN32_IMPL_LINK(JetBackupA, 12)
WIN32_IMPL_LINK(JetBackupW, 12)
WIN32_IMPL_LINK(JetBackupInstanceA, 16)
WIN32_IMPL_LINK(JetBackupInstanceW, 16)
WIN32_IMPL_LINK(JetRestoreA, 8)
WIN32_IMPL_LINK(JetRestoreW, 8)
WIN32_IMPL_LINK(JetRestore2A, 12)
WIN32_IMPL_LINK(JetRestore2W, 12)
WIN32_IMPL_LINK(JetRestoreInstanceA, 16)
WIN32_IMPL_LINK(JetRestoreInstanceW, 16)
WIN32_IMPL_LINK(JetSetIndexRange, 12)
WIN32_IMPL_LINK(JetIndexRecordCount, 16)
WIN32_IMPL_LINK(JetRetrieveKey, 24)
WIN32_IMPL_LINK(JetBeginExternalBackup, 4)
WIN32_IMPL_LINK(JetBeginExternalBackupInstance, 8)
WIN32_IMPL_LINK(JetGetAttachInfoA, 12)
WIN32_IMPL_LINK(JetGetAttachInfoW, 12)
WIN32_IMPL_LINK(JetGetAttachInfoInstanceA, 16)
WIN32_IMPL_LINK(JetGetAttachInfoInstanceW, 16)
WIN32_IMPL_LINK(JetOpenFileA, 16)
WIN32_IMPL_LINK(JetOpenFileW, 16)
WIN32_IMPL_LINK(JetOpenFileInstanceA, 20)
WIN32_IMPL_LINK(JetOpenFileInstanceW, 20)
WIN32_IMPL_LINK(JetReadFile, 16)
WIN32_IMPL_LINK(JetReadFileInstance, 20)
WIN32_IMPL_LINK(JetCloseFile, 4)
WIN32_IMPL_LINK(JetCloseFileInstance, 8)
WIN32_IMPL_LINK(JetGetLogInfoA, 12)
WIN32_IMPL_LINK(JetGetLogInfoW, 12)
WIN32_IMPL_LINK(JetGetLogInfoInstanceA, 16)
WIN32_IMPL_LINK(JetGetLogInfoInstanceW, 16)
WIN32_IMPL_LINK(JetGetLogInfoInstance2A, 20)
WIN32_IMPL_LINK(JetGetLogInfoInstance2W, 20)
WIN32_IMPL_LINK(JetGetTruncateLogInfoInstanceA, 16)
WIN32_IMPL_LINK(JetGetTruncateLogInfoInstanceW, 16)
WIN32_IMPL_LINK(JetTruncateLog, 0)
WIN32_IMPL_LINK(JetTruncateLogInstance, 4)
WIN32_IMPL_LINK(JetEndExternalBackup, 0)
WIN32_IMPL_LINK(JetEndExternalBackupInstance, 4)
WIN32_IMPL_LINK(JetEndExternalBackupInstance2, 8)
WIN32_IMPL_LINK(JetExternalRestoreA, 32)
WIN32_IMPL_LINK(JetExternalRestoreW, 32)
WIN32_IMPL_LINK(JetExternalRestore2A, 40)
WIN32_IMPL_LINK(JetExternalRestore2W, 40)
WIN32_IMPL_LINK(JetRegisterCallback, 24)
WIN32_IMPL_LINK(JetUnregisterCallback, 16)
WIN32_IMPL_LINK(JetGetInstanceInfoA, 8)
WIN32_IMPL_LINK(JetGetInstanceInfoW, 8)
WIN32_IMPL_LINK(JetFreeBuffer, 4)
WIN32_IMPL_LINK(JetSetLS, 16)
WIN32_IMPL_LINK(JetGetLS, 16)
WIN32_IMPL_LINK(JetOSSnapshotPrepare, 8)
WIN32_IMPL_LINK(JetOSSnapshotPrepareInstance, 12)
WIN32_IMPL_LINK(JetOSSnapshotFreezeA, 16)
WIN32_IMPL_LINK(JetOSSnapshotFreezeW, 16)
WIN32_IMPL_LINK(JetOSSnapshotThaw, 8)
WIN32_IMPL_LINK(JetOSSnapshotAbort, 8)
WIN32_IMPL_LINK(JetOSSnapshotTruncateLog, 8)
WIN32_IMPL_LINK(JetOSSnapshotTruncateLogInstance, 12)
WIN32_IMPL_LINK(JetOSSnapshotGetFreezeInfoA, 16)
WIN32_IMPL_LINK(JetOSSnapshotGetFreezeInfoW, 16)
WIN32_IMPL_LINK(JetOSSnapshotEnd, 8)
WIN32_IMPL_LINK(JetConfigureProcessForCrashDump, 4)
WIN32_IMPL_LINK(JetGetErrorInfoW, 20)
WIN32_IMPL_LINK(JetSetSessionParameter, 16)
WIN32_IMPL_LINK(JetGetSessionParameter, 20)

#pragma endregion abi_methods

#endif
