// WARNING: Please don't edit this file. It was generated by C++/Win32 v0.0.0.1

#ifndef WIN32_Windows_Win32_IMapi_0_H
#define WIN32_Windows_Win32_IMapi_0_H
WIN32_EXPORT namespace win32::Windows::Win32::IMapi
{
#pragma region enums
    enum class EmulationType : int32_t
    {
        EmulationNone = 0,
        Emulation12MFloppy = 1,
        Emulation144MFloppy = 2,
        Emulation288MFloppy = 3,
        EmulationHardDisk = 4,
    };
    enum class FsiFileSystems : int32_t
    {
        FsiFileSystemNone = 0,
        FsiFileSystemISO9660 = 1,
        FsiFileSystemJoliet = 2,
        FsiFileSystemUDF = 4,
        FsiFileSystemUnknown = 1073741824,
    };
    enum class FsiItemType : int32_t
    {
        FsiItemNotFound = 0,
        FsiItemDirectory = 1,
        FsiItemFile = 2,
    };
    enum class IMAPI_BURN_VERIFICATION_LEVEL : int32_t
    {
        IMAPI_BURN_VERIFICATION_NONE = 0,
        IMAPI_BURN_VERIFICATION_QUICK = 1,
        IMAPI_BURN_VERIFICATION_FULL = 2,
    };
    enum class IMAPI_CD_SECTOR_TYPE : int32_t
    {
        IMAPI_CD_SECTOR_AUDIO = 0,
        IMAPI_CD_SECTOR_MODE_ZERO = 1,
        IMAPI_CD_SECTOR_MODE1 = 2,
        IMAPI_CD_SECTOR_MODE2FORM0 = 3,
        IMAPI_CD_SECTOR_MODE2FORM1 = 4,
        IMAPI_CD_SECTOR_MODE2FORM2 = 5,
        IMAPI_CD_SECTOR_MODE1RAW = 6,
        IMAPI_CD_SECTOR_MODE2FORM0RAW = 7,
        IMAPI_CD_SECTOR_MODE2FORM1RAW = 8,
        IMAPI_CD_SECTOR_MODE2FORM2RAW = 9,
    };
    enum class IMAPI_CD_TRACK_DIGITAL_COPY_SETTING : int32_t
    {
        IMAPI_CD_TRACK_DIGITAL_COPY_PERMITTED = 0,
        IMAPI_CD_TRACK_DIGITAL_COPY_PROHIBITED = 1,
        IMAPI_CD_TRACK_DIGITAL_COPY_SCMS = 2,
    };
    enum class IMAPI_FEATURE_PAGE_TYPE : int32_t
    {
        IMAPI_FEATURE_PAGE_TYPE_PROFILE_LIST = 0,
        IMAPI_FEATURE_PAGE_TYPE_CORE = 1,
        IMAPI_FEATURE_PAGE_TYPE_MORPHING = 2,
        IMAPI_FEATURE_PAGE_TYPE_REMOVABLE_MEDIUM = 3,
        IMAPI_FEATURE_PAGE_TYPE_WRITE_PROTECT = 4,
        IMAPI_FEATURE_PAGE_TYPE_RANDOMLY_READABLE = 16,
        IMAPI_FEATURE_PAGE_TYPE_CD_MULTIREAD = 29,
        IMAPI_FEATURE_PAGE_TYPE_CD_READ = 30,
        IMAPI_FEATURE_PAGE_TYPE_DVD_READ = 31,
        IMAPI_FEATURE_PAGE_TYPE_RANDOMLY_WRITABLE = 32,
        IMAPI_FEATURE_PAGE_TYPE_INCREMENTAL_STREAMING_WRITABLE = 33,
        IMAPI_FEATURE_PAGE_TYPE_SECTOR_ERASABLE = 34,
        IMAPI_FEATURE_PAGE_TYPE_FORMATTABLE = 35,
        IMAPI_FEATURE_PAGE_TYPE_HARDWARE_DEFECT_MANAGEMENT = 36,
        IMAPI_FEATURE_PAGE_TYPE_WRITE_ONCE = 37,
        IMAPI_FEATURE_PAGE_TYPE_RESTRICTED_OVERWRITE = 38,
        IMAPI_FEATURE_PAGE_TYPE_CDRW_CAV_WRITE = 39,
        IMAPI_FEATURE_PAGE_TYPE_MRW = 40,
        IMAPI_FEATURE_PAGE_TYPE_ENHANCED_DEFECT_REPORTING = 41,
        IMAPI_FEATURE_PAGE_TYPE_DVD_PLUS_RW = 42,
        IMAPI_FEATURE_PAGE_TYPE_DVD_PLUS_R = 43,
        IMAPI_FEATURE_PAGE_TYPE_RIGID_RESTRICTED_OVERWRITE = 44,
        IMAPI_FEATURE_PAGE_TYPE_CD_TRACK_AT_ONCE = 45,
        IMAPI_FEATURE_PAGE_TYPE_CD_MASTERING = 46,
        IMAPI_FEATURE_PAGE_TYPE_DVD_DASH_WRITE = 47,
        IMAPI_FEATURE_PAGE_TYPE_DOUBLE_DENSITY_CD_READ = 48,
        IMAPI_FEATURE_PAGE_TYPE_DOUBLE_DENSITY_CD_R_WRITE = 49,
        IMAPI_FEATURE_PAGE_TYPE_DOUBLE_DENSITY_CD_RW_WRITE = 50,
        IMAPI_FEATURE_PAGE_TYPE_LAYER_JUMP_RECORDING = 51,
        IMAPI_FEATURE_PAGE_TYPE_CD_RW_MEDIA_WRITE_SUPPORT = 55,
        IMAPI_FEATURE_PAGE_TYPE_BD_PSEUDO_OVERWRITE = 56,
        IMAPI_FEATURE_PAGE_TYPE_DVD_PLUS_R_DUAL_LAYER = 59,
        IMAPI_FEATURE_PAGE_TYPE_BD_READ = 64,
        IMAPI_FEATURE_PAGE_TYPE_BD_WRITE = 65,
        IMAPI_FEATURE_PAGE_TYPE_HD_DVD_READ = 80,
        IMAPI_FEATURE_PAGE_TYPE_HD_DVD_WRITE = 81,
        IMAPI_FEATURE_PAGE_TYPE_POWER_MANAGEMENT = 256,
        IMAPI_FEATURE_PAGE_TYPE_SMART = 257,
        IMAPI_FEATURE_PAGE_TYPE_EMBEDDED_CHANGER = 258,
        IMAPI_FEATURE_PAGE_TYPE_CD_ANALOG_PLAY = 259,
        IMAPI_FEATURE_PAGE_TYPE_MICROCODE_UPDATE = 260,
        IMAPI_FEATURE_PAGE_TYPE_TIMEOUT = 261,
        IMAPI_FEATURE_PAGE_TYPE_DVD_CSS = 262,
        IMAPI_FEATURE_PAGE_TYPE_REAL_TIME_STREAMING = 263,
        IMAPI_FEATURE_PAGE_TYPE_LOGICAL_UNIT_SERIAL_NUMBER = 264,
        IMAPI_FEATURE_PAGE_TYPE_MEDIA_SERIAL_NUMBER = 265,
        IMAPI_FEATURE_PAGE_TYPE_DISC_CONTROL_BLOCKS = 266,
        IMAPI_FEATURE_PAGE_TYPE_DVD_CPRM = 267,
        IMAPI_FEATURE_PAGE_TYPE_FIRMWARE_INFORMATION = 268,
        IMAPI_FEATURE_PAGE_TYPE_AACS = 269,
        IMAPI_FEATURE_PAGE_TYPE_VCPS = 272,
    };
    enum class IMAPI_FORMAT2_DATA_MEDIA_STATE : int32_t
    {
        IMAPI_FORMAT2_DATA_MEDIA_STATE_UNKNOWN = 0,
        IMAPI_FORMAT2_DATA_MEDIA_STATE_INFORMATIONAL_MASK = 15,
        IMAPI_FORMAT2_DATA_MEDIA_STATE_UNSUPPORTED_MASK = 64512,
        IMAPI_FORMAT2_DATA_MEDIA_STATE_OVERWRITE_ONLY = 1,
        IMAPI_FORMAT2_DATA_MEDIA_STATE_RANDOMLY_WRITABLE = 1,
        IMAPI_FORMAT2_DATA_MEDIA_STATE_BLANK = 2,
        IMAPI_FORMAT2_DATA_MEDIA_STATE_APPENDABLE = 4,
        IMAPI_FORMAT2_DATA_MEDIA_STATE_FINAL_SESSION = 8,
        IMAPI_FORMAT2_DATA_MEDIA_STATE_DAMAGED = 1024,
        IMAPI_FORMAT2_DATA_MEDIA_STATE_ERASE_REQUIRED = 2048,
        IMAPI_FORMAT2_DATA_MEDIA_STATE_NON_EMPTY_SESSION = 4096,
        IMAPI_FORMAT2_DATA_MEDIA_STATE_WRITE_PROTECTED = 8192,
        IMAPI_FORMAT2_DATA_MEDIA_STATE_FINALIZED = 16384,
        IMAPI_FORMAT2_DATA_MEDIA_STATE_UNSUPPORTED_MEDIA = 32768,
    };
    enum class IMAPI_FORMAT2_DATA_WRITE_ACTION : int32_t
    {
        IMAPI_FORMAT2_DATA_WRITE_ACTION_VALIDATING_MEDIA = 0,
        IMAPI_FORMAT2_DATA_WRITE_ACTION_FORMATTING_MEDIA = 1,
        IMAPI_FORMAT2_DATA_WRITE_ACTION_INITIALIZING_HARDWARE = 2,
        IMAPI_FORMAT2_DATA_WRITE_ACTION_CALIBRATING_POWER = 3,
        IMAPI_FORMAT2_DATA_WRITE_ACTION_WRITING_DATA = 4,
        IMAPI_FORMAT2_DATA_WRITE_ACTION_FINALIZATION = 5,
        IMAPI_FORMAT2_DATA_WRITE_ACTION_COMPLETED = 6,
        IMAPI_FORMAT2_DATA_WRITE_ACTION_VERIFYING = 7,
    };
    enum class IMAPI_FORMAT2_RAW_CD_DATA_SECTOR_TYPE : int32_t
    {
        IMAPI_FORMAT2_RAW_CD_SUBCODE_PQ_ONLY = 1,
        IMAPI_FORMAT2_RAW_CD_SUBCODE_IS_COOKED = 2,
        IMAPI_FORMAT2_RAW_CD_SUBCODE_IS_RAW = 3,
    };
    enum class IMAPI_FORMAT2_RAW_CD_WRITE_ACTION : int32_t
    {
        IMAPI_FORMAT2_RAW_CD_WRITE_ACTION_UNKNOWN = 0,
        IMAPI_FORMAT2_RAW_CD_WRITE_ACTION_PREPARING = 1,
        IMAPI_FORMAT2_RAW_CD_WRITE_ACTION_WRITING = 2,
        IMAPI_FORMAT2_RAW_CD_WRITE_ACTION_FINISHING = 3,
    };
    enum class IMAPI_FORMAT2_TAO_WRITE_ACTION : int32_t
    {
        IMAPI_FORMAT2_TAO_WRITE_ACTION_UNKNOWN = 0,
        IMAPI_FORMAT2_TAO_WRITE_ACTION_PREPARING = 1,
        IMAPI_FORMAT2_TAO_WRITE_ACTION_WRITING = 2,
        IMAPI_FORMAT2_TAO_WRITE_ACTION_FINISHING = 3,
        IMAPI_FORMAT2_TAO_WRITE_ACTION_VERIFYING = 4,
    };
    enum class IMAPI_MEDIA_PHYSICAL_TYPE : int32_t
    {
        IMAPI_MEDIA_TYPE_UNKNOWN = 0,
        IMAPI_MEDIA_TYPE_CDROM = 1,
        IMAPI_MEDIA_TYPE_CDR = 2,
        IMAPI_MEDIA_TYPE_CDRW = 3,
        IMAPI_MEDIA_TYPE_DVDROM = 4,
        IMAPI_MEDIA_TYPE_DVDRAM = 5,
        IMAPI_MEDIA_TYPE_DVDPLUSR = 6,
        IMAPI_MEDIA_TYPE_DVDPLUSRW = 7,
        IMAPI_MEDIA_TYPE_DVDPLUSR_DUALLAYER = 8,
        IMAPI_MEDIA_TYPE_DVDDASHR = 9,
        IMAPI_MEDIA_TYPE_DVDDASHRW = 10,
        IMAPI_MEDIA_TYPE_DVDDASHR_DUALLAYER = 11,
        IMAPI_MEDIA_TYPE_DISK = 12,
        IMAPI_MEDIA_TYPE_DVDPLUSRW_DUALLAYER = 13,
        IMAPI_MEDIA_TYPE_HDDVDROM = 14,
        IMAPI_MEDIA_TYPE_HDDVDR = 15,
        IMAPI_MEDIA_TYPE_HDDVDRAM = 16,
        IMAPI_MEDIA_TYPE_BDROM = 17,
        IMAPI_MEDIA_TYPE_BDR = 18,
        IMAPI_MEDIA_TYPE_BDRE = 19,
        IMAPI_MEDIA_TYPE_MAX = 19,
    };
    enum class IMAPI_MEDIA_WRITE_PROTECT_STATE : int32_t
    {
        IMAPI_WRITEPROTECTED_UNTIL_POWERDOWN = 1,
        IMAPI_WRITEPROTECTED_BY_CARTRIDGE = 2,
        IMAPI_WRITEPROTECTED_BY_MEDIA_SPECIFIC_REASON = 4,
        IMAPI_WRITEPROTECTED_BY_SOFTWARE_WRITE_PROTECT = 8,
        IMAPI_WRITEPROTECTED_BY_DISC_CONTROL_BLOCK = 16,
        IMAPI_WRITEPROTECTED_READ_ONLY_MEDIA = 16384,
    };
    enum class IMAPI_MODE_PAGE_REQUEST_TYPE : int32_t
    {
        IMAPI_MODE_PAGE_REQUEST_TYPE_CURRENT_VALUES = 0,
        IMAPI_MODE_PAGE_REQUEST_TYPE_CHANGEABLE_VALUES = 1,
        IMAPI_MODE_PAGE_REQUEST_TYPE_DEFAULT_VALUES = 2,
        IMAPI_MODE_PAGE_REQUEST_TYPE_SAVED_VALUES = 3,
    };
    enum class IMAPI_MODE_PAGE_TYPE : int32_t
    {
        IMAPI_MODE_PAGE_TYPE_READ_WRITE_ERROR_RECOVERY = 1,
        IMAPI_MODE_PAGE_TYPE_MRW = 3,
        IMAPI_MODE_PAGE_TYPE_WRITE_PARAMETERS = 5,
        IMAPI_MODE_PAGE_TYPE_CACHING = 8,
        IMAPI_MODE_PAGE_TYPE_INFORMATIONAL_EXCEPTIONS = 28,
        IMAPI_MODE_PAGE_TYPE_TIMEOUT_AND_PROTECT = 29,
        IMAPI_MODE_PAGE_TYPE_POWER_CONDITION = 26,
        IMAPI_MODE_PAGE_TYPE_LEGACY_CAPABILITIES = 42,
    };
    enum class IMAPI_PROFILE_TYPE : int32_t
    {
        IMAPI_PROFILE_TYPE_INVALID = 0,
        IMAPI_PROFILE_TYPE_NON_REMOVABLE_DISK = 1,
        IMAPI_PROFILE_TYPE_REMOVABLE_DISK = 2,
        IMAPI_PROFILE_TYPE_MO_ERASABLE = 3,
        IMAPI_PROFILE_TYPE_MO_WRITE_ONCE = 4,
        IMAPI_PROFILE_TYPE_AS_MO = 5,
        IMAPI_PROFILE_TYPE_CDROM = 8,
        IMAPI_PROFILE_TYPE_CD_RECORDABLE = 9,
        IMAPI_PROFILE_TYPE_CD_REWRITABLE = 10,
        IMAPI_PROFILE_TYPE_DVDROM = 16,
        IMAPI_PROFILE_TYPE_DVD_DASH_RECORDABLE = 17,
        IMAPI_PROFILE_TYPE_DVD_RAM = 18,
        IMAPI_PROFILE_TYPE_DVD_DASH_REWRITABLE = 19,
        IMAPI_PROFILE_TYPE_DVD_DASH_RW_SEQUENTIAL = 20,
        IMAPI_PROFILE_TYPE_DVD_DASH_R_DUAL_SEQUENTIAL = 21,
        IMAPI_PROFILE_TYPE_DVD_DASH_R_DUAL_LAYER_JUMP = 22,
        IMAPI_PROFILE_TYPE_DVD_PLUS_RW = 26,
        IMAPI_PROFILE_TYPE_DVD_PLUS_R = 27,
        IMAPI_PROFILE_TYPE_DDCDROM = 32,
        IMAPI_PROFILE_TYPE_DDCD_RECORDABLE = 33,
        IMAPI_PROFILE_TYPE_DDCD_REWRITABLE = 34,
        IMAPI_PROFILE_TYPE_DVD_PLUS_RW_DUAL = 42,
        IMAPI_PROFILE_TYPE_DVD_PLUS_R_DUAL = 43,
        IMAPI_PROFILE_TYPE_BD_ROM = 64,
        IMAPI_PROFILE_TYPE_BD_R_SEQUENTIAL = 65,
        IMAPI_PROFILE_TYPE_BD_R_RANDOM_RECORDING = 66,
        IMAPI_PROFILE_TYPE_BD_REWRITABLE = 67,
        IMAPI_PROFILE_TYPE_HD_DVD_ROM = 80,
        IMAPI_PROFILE_TYPE_HD_DVD_RECORDABLE = 81,
        IMAPI_PROFILE_TYPE_HD_DVD_RAM = 82,
        IMAPI_PROFILE_TYPE_NON_STANDARD = 65535,
    };
    enum class IMAPI_READ_TRACK_ADDRESS_TYPE : int32_t
    {
        IMAPI_READ_TRACK_ADDRESS_TYPE_LBA = 0,
        IMAPI_READ_TRACK_ADDRESS_TYPE_TRACK = 1,
        IMAPI_READ_TRACK_ADDRESS_TYPE_SESSION = 2,
    };
    enum class MEDIA_FLAGS : int32_t
    {
        MEDIA_BLANK = 1,
        MEDIA_RW = 2,
        MEDIA_WRITABLE = 4,
        MEDIA_FORMAT_UNUSABLE_BY_IMAPI = 8,
    };
    enum class MEDIA_TYPES : int32_t
    {
        MEDIA_CDDA_CDROM = 1,
        MEDIA_CD_ROM_XA = 2,
        MEDIA_CD_I = 3,
        MEDIA_CD_EXTRA = 4,
        MEDIA_CD_OTHER = 5,
        MEDIA_SPECIAL = 6,
    };
    enum class PlatformId : int32_t
    {
        PlatformX86 = 0,
        PlatformPowerPC = 1,
        PlatformMac = 2,
        PlatformEFI = 239,
    };
    enum class RECORDER_TYPES : int32_t
    {
        RECORDER_CDR = 1,
        RECORDER_CDRW = 2,
    };
#pragma endregion enums

#pragma region forward_declarations
    struct BlockRange;
    struct BlockRangeList;
    struct BootOptions;
    struct DDiscFormat2DataEvents;
    struct DDiscFormat2EraseEvents;
    struct DDiscFormat2RawCDEvents;
    struct DDiscFormat2TrackAtOnceEvents;
    struct DDiscMaster2Events;
    struct DFileSystemImageEvents;
    struct DFileSystemImageImportEvents;
    struct DWriteEngine2Events;
    struct EnumFsiItems;
    struct EnumProgressItems;
    struct FileSystemImageResult;
    struct FsiDirectoryItem;
    struct FsiFileItem;
    struct FsiNamedStreams;
    struct FsiStream;
    struct IBlockRange;
    struct IBlockRangeList;
    struct IBootOptions;
    struct IBurnVerification;
    struct IDiscFormat2;
    struct IDiscFormat2Data;
    struct IDiscFormat2DataEventArgs;
    struct IDiscFormat2Erase;
    struct IDiscFormat2RawCD;
    struct IDiscFormat2RawCDEventArgs;
    struct IDiscFormat2TrackAtOnce;
    struct IDiscFormat2TrackAtOnceEventArgs;
    struct IDiscMaster;
    struct IDiscMaster2;
    struct IDiscMasterProgressEvents;
    struct IDiscRecorder;
    struct IDiscRecorder2;
    struct IDiscRecorder2Ex;
    struct IEnumDiscMasterFormats;
    struct IEnumDiscRecorders;
    struct IEnumFsiItems;
    struct IEnumProgressItems;
    struct IFileSystemImage;
    struct IFileSystemImage2;
    struct IFileSystemImage3;
    struct IFileSystemImageResult;
    struct IFileSystemImageResult2;
    struct IFsiDirectoryItem;
    struct IFsiDirectoryItem2;
    struct IFsiFileItem;
    struct IFsiFileItem2;
    struct IFsiItem;
    struct IFsiNamedStreams;
    struct IIsoImageManager;
    struct IJolietDiscMaster;
    struct IMultisession;
    struct IMultisessionRandomWrite;
    struct IMultisessionSequential;
    struct IMultisessionSequential2;
    struct IProgressItem;
    struct IProgressItems;
    struct IRawCDImageCreator;
    struct IRawCDImageTrackInfo;
    struct IRedbookDiscMaster;
    struct IStreamConcatenate;
    struct IStreamInterleave;
    struct IStreamPseudoRandomBased;
    struct IWriteEngine2;
    struct IWriteEngine2EventArgs;
    struct IWriteSpeedDescriptor;
    struct MSDiscMasterObj;
    struct MSDiscRecorderObj;
    struct MSEnumDiscRecordersObj;
    struct MsftDiscFormat2Data;
    struct MsftDiscFormat2Erase;
    struct MsftDiscFormat2RawCD;
    struct MsftDiscFormat2TrackAtOnce;
    struct MsftDiscMaster2;
    struct MsftDiscRecorder2;
    struct MsftFileSystemImage;
    struct MsftIsoImageManager;
    struct MsftMultisessionRandomWrite;
    struct MsftMultisessionSequential;
    struct MsftRawCDImageCreator;
    struct MsftStreamConcatenate;
    struct MsftStreamInterleave;
    struct MsftStreamPrng001;
    struct MsftStreamZero;
    struct MsftWriteEngine2;
    struct MsftWriteSpeedDescriptor;
    struct ProgressItem;
    struct ProgressItems;
#pragma endregion forward_declarations

#pragma region delegates
#pragma endregion delegates

}
namespace win32::_impl_
{
#pragma region guids
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::BlockRange>{ 0xB507CA27,0x2204,0x11DD,{ 0x96,0x6A,0x00,0x1A,0xA0,0x1B,0xBC,0x58 } }; // B507CA27-2204-11DD-966A-001AA01BBC58
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::BlockRangeList>{ 0xB507CA28,0x2204,0x11DD,{ 0x96,0x6A,0x00,0x1A,0xA0,0x1B,0xBC,0x58 } }; // B507CA28-2204-11DD-966A-001AA01BBC58
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::BootOptions>{ 0x2C941FCE,0x975B,0x59BE,{ 0xA9,0x60,0x9A,0x2A,0x26,0x28,0x53,0xA5 } }; // 2C941FCE-975B-59BE-A960-9A2A262853A5
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::DDiscFormat2DataEvents>{ 0x2735413C,0x7F64,0x5B0F,{ 0x8F,0x00,0x5D,0x77,0xAF,0xBE,0x26,0x1E } }; // 2735413C-7F64-5B0F-8F00-5D77AFBE261E
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::DDiscFormat2EraseEvents>{ 0x2735413A,0x7F64,0x5B0F,{ 0x8F,0x00,0x5D,0x77,0xAF,0xBE,0x26,0x1E } }; // 2735413A-7F64-5B0F-8F00-5D77AFBE261E
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::DDiscFormat2RawCDEvents>{ 0x27354142,0x7F64,0x5B0F,{ 0x8F,0x00,0x5D,0x77,0xAF,0xBE,0x26,0x1E } }; // 27354142-7F64-5B0F-8F00-5D77AFBE261E
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::DDiscFormat2TrackAtOnceEvents>{ 0x2735413F,0x7F64,0x5B0F,{ 0x8F,0x00,0x5D,0x77,0xAF,0xBE,0x26,0x1E } }; // 2735413F-7F64-5B0F-8F00-5D77AFBE261E
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::DDiscMaster2Events>{ 0x27354131,0x7F64,0x5B0F,{ 0x8F,0x00,0x5D,0x77,0xAF,0xBE,0x26,0x1E } }; // 27354131-7F64-5B0F-8F00-5D77AFBE261E
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::DFileSystemImageEvents>{ 0x2C941FDF,0x975B,0x59BE,{ 0xA9,0x60,0x9A,0x2A,0x26,0x28,0x53,0xA5 } }; // 2C941FDF-975B-59BE-A960-9A2A262853A5
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::DFileSystemImageImportEvents>{ 0xD25C30F9,0x4087,0x4366,{ 0x9E,0x24,0xE5,0x5B,0xE2,0x86,0x42,0x4B } }; // D25C30F9-4087-4366-9E24-E55BE286424B
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::DWriteEngine2Events>{ 0x27354137,0x7F64,0x5B0F,{ 0x8F,0x00,0x5D,0x77,0xAF,0xBE,0x26,0x1E } }; // 27354137-7F64-5B0F-8F00-5D77AFBE261E
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::EnumFsiItems>{ 0x2C941FC6,0x975B,0x59BE,{ 0xA9,0x60,0x9A,0x2A,0x26,0x28,0x53,0xA5 } }; // 2C941FC6-975B-59BE-A960-9A2A262853A5
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::EnumProgressItems>{ 0x2C941FCA,0x975B,0x59BE,{ 0xA9,0x60,0x9A,0x2A,0x26,0x28,0x53,0xA5 } }; // 2C941FCA-975B-59BE-A960-9A2A262853A5
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::FileSystemImageResult>{ 0x2C941FCC,0x975B,0x59BE,{ 0xA9,0x60,0x9A,0x2A,0x26,0x28,0x53,0xA5 } }; // 2C941FCC-975B-59BE-A960-9A2A262853A5
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::FsiDirectoryItem>{ 0x2C941FC8,0x975B,0x59BE,{ 0xA9,0x60,0x9A,0x2A,0x26,0x28,0x53,0xA5 } }; // 2C941FC8-975B-59BE-A960-9A2A262853A5
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::FsiFileItem>{ 0x2C941FC7,0x975B,0x59BE,{ 0xA9,0x60,0x9A,0x2A,0x26,0x28,0x53,0xA5 } }; // 2C941FC7-975B-59BE-A960-9A2A262853A5
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::FsiNamedStreams>{ 0xC6B6F8ED,0x6D19,0x44B4,{ 0xB5,0x39,0xB1,0x59,0xB7,0x93,0xA3,0x2D } }; // C6B6F8ED-6D19-44B4-B539-B159B793A32D
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::FsiStream>{ 0x2C941FCD,0x975B,0x59BE,{ 0xA9,0x60,0x9A,0x2A,0x26,0x28,0x53,0xA5 } }; // 2C941FCD-975B-59BE-A960-9A2A262853A5
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::IBlockRange>{ 0xB507CA25,0x2204,0x11DD,{ 0x96,0x6A,0x00,0x1A,0xA0,0x1B,0xBC,0x58 } }; // B507CA25-2204-11DD-966A-001AA01BBC58
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::IBlockRangeList>{ 0xB507CA26,0x2204,0x11DD,{ 0x96,0x6A,0x00,0x1A,0xA0,0x1B,0xBC,0x58 } }; // B507CA26-2204-11DD-966A-001AA01BBC58
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::IBootOptions>{ 0x2C941FD4,0x975B,0x59BE,{ 0xA9,0x60,0x9A,0x2A,0x26,0x28,0x53,0xA5 } }; // 2C941FD4-975B-59BE-A960-9A2A262853A5
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::IBurnVerification>{ 0xD2FFD834,0x958B,0x426D,{ 0x84,0x70,0x2A,0x13,0x87,0x9C,0x6A,0x91 } }; // D2FFD834-958B-426D-8470-2A13879C6A91
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::IDiscFormat2>{ 0x27354152,0x8F64,0x5B0F,{ 0x8F,0x00,0x5D,0x77,0xAF,0xBE,0x26,0x1E } }; // 27354152-8F64-5B0F-8F00-5D77AFBE261E
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::IDiscFormat2Data>{ 0x27354153,0x9F64,0x5B0F,{ 0x8F,0x00,0x5D,0x77,0xAF,0xBE,0x26,0x1E } }; // 27354153-9F64-5B0F-8F00-5D77AFBE261E
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::IDiscFormat2DataEventArgs>{ 0x2735413D,0x7F64,0x5B0F,{ 0x8F,0x00,0x5D,0x77,0xAF,0xBE,0x26,0x1E } }; // 2735413D-7F64-5B0F-8F00-5D77AFBE261E
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::IDiscFormat2Erase>{ 0x27354156,0x8F64,0x5B0F,{ 0x8F,0x00,0x5D,0x77,0xAF,0xBE,0x26,0x1E } }; // 27354156-8F64-5B0F-8F00-5D77AFBE261E
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::IDiscFormat2RawCD>{ 0x27354155,0x8F64,0x5B0F,{ 0x8F,0x00,0x5D,0x77,0xAF,0xBE,0x26,0x1E } }; // 27354155-8F64-5B0F-8F00-5D77AFBE261E
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::IDiscFormat2RawCDEventArgs>{ 0x27354143,0x7F64,0x5B0F,{ 0x8F,0x00,0x5D,0x77,0xAF,0xBE,0x26,0x1E } }; // 27354143-7F64-5B0F-8F00-5D77AFBE261E
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::IDiscFormat2TrackAtOnce>{ 0x27354154,0x8F64,0x5B0F,{ 0x8F,0x00,0x5D,0x77,0xAF,0xBE,0x26,0x1E } }; // 27354154-8F64-5B0F-8F00-5D77AFBE261E
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::IDiscFormat2TrackAtOnceEventArgs>{ 0x27354140,0x7F64,0x5B0F,{ 0x8F,0x00,0x5D,0x77,0xAF,0xBE,0x26,0x1E } }; // 27354140-7F64-5B0F-8F00-5D77AFBE261E
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::IDiscMaster>{ 0x520CCA62,0x51A5,0x11D3,{ 0x91,0x44,0x00,0x10,0x4B,0xA1,0x1C,0x5E } }; // 520CCA62-51A5-11D3-9144-00104BA11C5E
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::IDiscMaster2>{ 0x27354130,0x7F64,0x5B0F,{ 0x8F,0x00,0x5D,0x77,0xAF,0xBE,0x26,0x1E } }; // 27354130-7F64-5B0F-8F00-5D77AFBE261E
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::IDiscMasterProgressEvents>{ 0xEC9E51C1,0x4E5D,0x11D3,{ 0x91,0x44,0x00,0x10,0x4B,0xA1,0x1C,0x5E } }; // EC9E51C1-4E5D-11D3-9144-00104BA11C5E
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::IDiscRecorder>{ 0x85AC9776,0xCA88,0x4CF2,{ 0x89,0x4E,0x09,0x59,0x8C,0x07,0x8A,0x41 } }; // 85AC9776-CA88-4CF2-894E-09598C078A41
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::IDiscRecorder2>{ 0x27354133,0x7F64,0x5B0F,{ 0x8F,0x00,0x5D,0x77,0xAF,0xBE,0x26,0x1E } }; // 27354133-7F64-5B0F-8F00-5D77AFBE261E
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::IDiscRecorder2Ex>{ 0x27354132,0x7F64,0x5B0F,{ 0x8F,0x00,0x5D,0x77,0xAF,0xBE,0x26,0x1E } }; // 27354132-7F64-5B0F-8F00-5D77AFBE261E
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::IEnumDiscMasterFormats>{ 0xDDF445E1,0x54BA,0x11D3,{ 0x91,0x44,0x00,0x10,0x4B,0xA1,0x1C,0x5E } }; // DDF445E1-54BA-11D3-9144-00104BA11C5E
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::IEnumDiscRecorders>{ 0x9B1921E1,0x54AC,0x11D3,{ 0x91,0x44,0x00,0x10,0x4B,0xA1,0x1C,0x5E } }; // 9B1921E1-54AC-11D3-9144-00104BA11C5E
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::IEnumFsiItems>{ 0x2C941FDA,0x975B,0x59BE,{ 0xA9,0x60,0x9A,0x2A,0x26,0x28,0x53,0xA5 } }; // 2C941FDA-975B-59BE-A960-9A2A262853A5
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::IEnumProgressItems>{ 0x2C941FD6,0x975B,0x59BE,{ 0xA9,0x60,0x9A,0x2A,0x26,0x28,0x53,0xA5 } }; // 2C941FD6-975B-59BE-A960-9A2A262853A5
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::IFileSystemImage>{ 0x2C941FE1,0x975B,0x59BE,{ 0xA9,0x60,0x9A,0x2A,0x26,0x28,0x53,0xA5 } }; // 2C941FE1-975B-59BE-A960-9A2A262853A5
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::IFileSystemImage2>{ 0xD7644B2C,0x1537,0x4767,{ 0xB6,0x2F,0xF1,0x38,0x7B,0x02,0xDD,0xFD } }; // D7644B2C-1537-4767-B62F-F1387B02DDFD
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::IFileSystemImage3>{ 0x7CFF842C,0x7E97,0x4807,{ 0x83,0x04,0x91,0x0D,0xD8,0xF7,0xC0,0x51 } }; // 7CFF842C-7E97-4807-8304-910DD8F7C051
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::IFileSystemImageResult>{ 0x2C941FD8,0x975B,0x59BE,{ 0xA9,0x60,0x9A,0x2A,0x26,0x28,0x53,0xA5 } }; // 2C941FD8-975B-59BE-A960-9A2A262853A5
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::IFileSystemImageResult2>{ 0xB507CA29,0x2204,0x11DD,{ 0x96,0x6A,0x00,0x1A,0xA0,0x1B,0xBC,0x58 } }; // B507CA29-2204-11DD-966A-001AA01BBC58
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::IFsiDirectoryItem>{ 0x2C941FDC,0x975B,0x59BE,{ 0xA9,0x60,0x9A,0x2A,0x26,0x28,0x53,0xA5 } }; // 2C941FDC-975B-59BE-A960-9A2A262853A5
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::IFsiDirectoryItem2>{ 0xF7FB4B9B,0x6D96,0x4D7B,{ 0x91,0x15,0x20,0x1B,0x14,0x48,0x11,0xEF } }; // F7FB4B9B-6D96-4D7B-9115-201B144811EF
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::IFsiFileItem>{ 0x2C941FDB,0x975B,0x59BE,{ 0xA9,0x60,0x9A,0x2A,0x26,0x28,0x53,0xA5 } }; // 2C941FDB-975B-59BE-A960-9A2A262853A5
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::IFsiFileItem2>{ 0x199D0C19,0x11E1,0x40EB,{ 0x8E,0xC2,0xC8,0xC8,0x22,0xA0,0x77,0x92 } }; // 199D0C19-11E1-40EB-8EC2-C8C822A07792
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::IFsiItem>{ 0x2C941FD9,0x975B,0x59BE,{ 0xA9,0x60,0x9A,0x2A,0x26,0x28,0x53,0xA5 } }; // 2C941FD9-975B-59BE-A960-9A2A262853A5
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::IFsiNamedStreams>{ 0xED79BA56,0x5294,0x4250,{ 0x8D,0x46,0xF9,0xAE,0xCE,0xE2,0x34,0x59 } }; // ED79BA56-5294-4250-8D46-F9AECEE23459
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::IIsoImageManager>{ 0x6CA38BE5,0xFBBB,0x4800,{ 0x95,0xA1,0xA4,0x38,0x86,0x5E,0xB0,0xD4 } }; // 6CA38BE5-FBBB-4800-95A1-A438865EB0D4
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::IJolietDiscMaster>{ 0xE3BC42CE,0x4E5C,0x11D3,{ 0x91,0x44,0x00,0x10,0x4B,0xA1,0x1C,0x5E } }; // E3BC42CE-4E5C-11D3-9144-00104BA11C5E
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::IMultisession>{ 0x27354150,0x7F64,0x5B0F,{ 0x8F,0x00,0x5D,0x77,0xAF,0xBE,0x26,0x1E } }; // 27354150-7F64-5B0F-8F00-5D77AFBE261E
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::IMultisessionRandomWrite>{ 0xB507CA23,0x2204,0x11DD,{ 0x96,0x6A,0x00,0x1A,0xA0,0x1B,0xBC,0x58 } }; // B507CA23-2204-11DD-966A-001AA01BBC58
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::IMultisessionSequential>{ 0x27354151,0x7F64,0x5B0F,{ 0x8F,0x00,0x5D,0x77,0xAF,0xBE,0x26,0x1E } }; // 27354151-7F64-5B0F-8F00-5D77AFBE261E
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::IMultisessionSequential2>{ 0xB507CA22,0x2204,0x11DD,{ 0x96,0x6A,0x00,0x1A,0xA0,0x1B,0xBC,0x58 } }; // B507CA22-2204-11DD-966A-001AA01BBC58
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::IProgressItem>{ 0x2C941FD5,0x975B,0x59BE,{ 0xA9,0x60,0x9A,0x2A,0x26,0x28,0x53,0xA5 } }; // 2C941FD5-975B-59BE-A960-9A2A262853A5
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::IProgressItems>{ 0x2C941FD7,0x975B,0x59BE,{ 0xA9,0x60,0x9A,0x2A,0x26,0x28,0x53,0xA5 } }; // 2C941FD7-975B-59BE-A960-9A2A262853A5
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::IRawCDImageCreator>{ 0x25983550,0x9D65,0x49CE,{ 0xB3,0x35,0x40,0x63,0x0D,0x90,0x12,0x27 } }; // 25983550-9D65-49CE-B335-40630D901227
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::IRawCDImageTrackInfo>{ 0x25983551,0x9D65,0x49CE,{ 0xB3,0x35,0x40,0x63,0x0D,0x90,0x12,0x27 } }; // 25983551-9D65-49CE-B335-40630D901227
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::IRedbookDiscMaster>{ 0xE3BC42CD,0x4E5C,0x11D3,{ 0x91,0x44,0x00,0x10,0x4B,0xA1,0x1C,0x5E } }; // E3BC42CD-4E5C-11D3-9144-00104BA11C5E
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::IStreamConcatenate>{ 0x27354146,0x7F64,0x5B0F,{ 0x8F,0x00,0x5D,0x77,0xAF,0xBE,0x26,0x1E } }; // 27354146-7F64-5B0F-8F00-5D77AFBE261E
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::IStreamInterleave>{ 0x27354147,0x7F64,0x5B0F,{ 0x8F,0x00,0x5D,0x77,0xAF,0xBE,0x26,0x1E } }; // 27354147-7F64-5B0F-8F00-5D77AFBE261E
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::IStreamPseudoRandomBased>{ 0x27354145,0x7F64,0x5B0F,{ 0x8F,0x00,0x5D,0x77,0xAF,0xBE,0x26,0x1E } }; // 27354145-7F64-5B0F-8F00-5D77AFBE261E
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::IWriteEngine2>{ 0x27354135,0x7F64,0x5B0F,{ 0x8F,0x00,0x5D,0x77,0xAF,0xBE,0x26,0x1E } }; // 27354135-7F64-5B0F-8F00-5D77AFBE261E
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::IWriteEngine2EventArgs>{ 0x27354136,0x7F64,0x5B0F,{ 0x8F,0x00,0x5D,0x77,0xAF,0xBE,0x26,0x1E } }; // 27354136-7F64-5B0F-8F00-5D77AFBE261E
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::IWriteSpeedDescriptor>{ 0x27354144,0x7F64,0x5B0F,{ 0x8F,0x00,0x5D,0x77,0xAF,0xBE,0x26,0x1E } }; // 27354144-7F64-5B0F-8F00-5D77AFBE261E
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::MSDiscMasterObj>{ 0x520CCA63,0x51A5,0x11D3,{ 0x91,0x44,0x00,0x10,0x4B,0xA1,0x1C,0x5E } }; // 520CCA63-51A5-11D3-9144-00104BA11C5E
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::MSDiscRecorderObj>{ 0x520CCA61,0x51A5,0x11D3,{ 0x91,0x44,0x00,0x10,0x4B,0xA1,0x1C,0x5E } }; // 520CCA61-51A5-11D3-9144-00104BA11C5E
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::MSEnumDiscRecordersObj>{ 0x8A03567A,0x63CB,0x4BA8,{ 0xBA,0xF6,0x52,0x11,0x98,0x16,0xD1,0xEF } }; // 8A03567A-63CB-4BA8-BAF6-52119816D1EF
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::MsftDiscFormat2Data>{ 0x2735412A,0x7F64,0x5B0F,{ 0x8F,0x00,0x5D,0x77,0xAF,0xBE,0x26,0x1E } }; // 2735412A-7F64-5B0F-8F00-5D77AFBE261E
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::MsftDiscFormat2Erase>{ 0x2735412B,0x7F64,0x5B0F,{ 0x8F,0x00,0x5D,0x77,0xAF,0xBE,0x26,0x1E } }; // 2735412B-7F64-5B0F-8F00-5D77AFBE261E
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::MsftDiscFormat2RawCD>{ 0x27354128,0x7F64,0x5B0F,{ 0x8F,0x00,0x5D,0x77,0xAF,0xBE,0x26,0x1E } }; // 27354128-7F64-5B0F-8F00-5D77AFBE261E
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::MsftDiscFormat2TrackAtOnce>{ 0x27354129,0x7F64,0x5B0F,{ 0x8F,0x00,0x5D,0x77,0xAF,0xBE,0x26,0x1E } }; // 27354129-7F64-5B0F-8F00-5D77AFBE261E
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::MsftDiscMaster2>{ 0x2735412E,0x7F64,0x5B0F,{ 0x8F,0x00,0x5D,0x77,0xAF,0xBE,0x26,0x1E } }; // 2735412E-7F64-5B0F-8F00-5D77AFBE261E
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::MsftDiscRecorder2>{ 0x2735412D,0x7F64,0x5B0F,{ 0x8F,0x00,0x5D,0x77,0xAF,0xBE,0x26,0x1E } }; // 2735412D-7F64-5B0F-8F00-5D77AFBE261E
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::MsftFileSystemImage>{ 0x2C941FC5,0x975B,0x59BE,{ 0xA9,0x60,0x9A,0x2A,0x26,0x28,0x53,0xA5 } }; // 2C941FC5-975B-59BE-A960-9A2A262853A5
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::MsftIsoImageManager>{ 0xCEEE3B62,0x8F56,0x4056,{ 0x86,0x9B,0xEF,0x16,0x91,0x7E,0x3E,0xFC } }; // CEEE3B62-8F56-4056-869B-EF16917E3EFC
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::MsftMultisessionRandomWrite>{ 0xB507CA24,0x2204,0x11DD,{ 0x96,0x6A,0x00,0x1A,0xA0,0x1B,0xBC,0x58 } }; // B507CA24-2204-11DD-966A-001AA01BBC58
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::MsftMultisessionSequential>{ 0x27354122,0x7F64,0x5B0F,{ 0x8F,0x00,0x5D,0x77,0xAF,0xBE,0x26,0x1E } }; // 27354122-7F64-5B0F-8F00-5D77AFBE261E
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::MsftRawCDImageCreator>{ 0x25983561,0x9D65,0x49CE,{ 0xB3,0x35,0x40,0x63,0x0D,0x90,0x12,0x27 } }; // 25983561-9D65-49CE-B335-40630D901227
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::MsftStreamConcatenate>{ 0x27354125,0x7F64,0x5B0F,{ 0x8F,0x00,0x5D,0x77,0xAF,0xBE,0x26,0x1E } }; // 27354125-7F64-5B0F-8F00-5D77AFBE261E
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::MsftStreamInterleave>{ 0x27354124,0x7F64,0x5B0F,{ 0x8F,0x00,0x5D,0x77,0xAF,0xBE,0x26,0x1E } }; // 27354124-7F64-5B0F-8F00-5D77AFBE261E
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::MsftStreamPrng001>{ 0x27354126,0x7F64,0x5B0F,{ 0x8F,0x00,0x5D,0x77,0xAF,0xBE,0x26,0x1E } }; // 27354126-7F64-5B0F-8F00-5D77AFBE261E
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::MsftStreamZero>{ 0x27354127,0x7F64,0x5B0F,{ 0x8F,0x00,0x5D,0x77,0xAF,0xBE,0x26,0x1E } }; // 27354127-7F64-5B0F-8F00-5D77AFBE261E
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::MsftWriteEngine2>{ 0x2735412C,0x7F64,0x5B0F,{ 0x8F,0x00,0x5D,0x77,0xAF,0xBE,0x26,0x1E } }; // 2735412C-7F64-5B0F-8F00-5D77AFBE261E
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::MsftWriteSpeedDescriptor>{ 0x27354123,0x7F64,0x5B0F,{ 0x8F,0x00,0x5D,0x77,0xAF,0xBE,0x26,0x1E } }; // 27354123-7F64-5B0F-8F00-5D77AFBE261E
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::ProgressItem>{ 0x2C941FCB,0x975B,0x59BE,{ 0xA9,0x60,0x9A,0x2A,0x26,0x28,0x53,0xA5 } }; // 2C941FCB-975B-59BE-A960-9A2A262853A5
    template <> inline constexpr guid guid_v<Windows::Win32::IMapi::ProgressItems>{ 0x2C941FC9,0x975B,0x59BE,{ 0xA9,0x60,0x9A,0x2A,0x26,0x28,0x53,0xA5 } }; // 2C941FC9-975B-59BE-A960-9A2A262853A5
#pragma endregion guids

}
#endif
