// WARNING: Please don't edit this file. It was generated by C++/Win32 v0.0.0.1

#ifndef WIN32_Windows_Win32_SystemRestore_0_H
#define WIN32_Windows_Win32_SystemRestore_0_H
WIN32_EXPORT namespace win32::Windows::Win32::SystemRestore
{
#pragma region enums
#pragma endregion enums

#pragma region forward_declarations
    struct RESTOREPOINTINFOA;
    struct RESTOREPOINTINFOW;
    struct STATEMGRSTATUS;
    struct _RESTOREPTINFOEX;
#pragma endregion forward_declarations

#pragma region delegates
#pragma endregion delegates

}
namespace win32::_impl_
{
#pragma region guids
#pragma endregion guids

}
#endif
