// WARNING: Please don't edit this file. It was generated by C++/Win32 v0.0.0.1

#ifndef WIN32_Windows_Win32_DistributedFileSystem_0_H
#define WIN32_Windows_Win32_DistributedFileSystem_0_H
WIN32_EXPORT namespace win32::Windows::Win32::DistributedFileSystem
{
#pragma region enums
    enum class DFS_NAMESPACE_VERSION_ORIGIN : int32_t
    {
        DFS_NAMESPACE_VERSION_ORIGIN_COMBINED = 0,
        DFS_NAMESPACE_VERSION_ORIGIN_SERVER = 1,
        DFS_NAMESPACE_VERSION_ORIGIN_DOMAIN = 2,
    };
    enum class DFS_TARGET_PRIORITY_CLASS : int32_t
    {
        DfsInvalidPriorityClass = -1,
        DfsSiteCostNormalPriorityClass = 0,
        DfsGlobalHighPriorityClass = 1,
        DfsSiteCostHighPriorityClass = 2,
        DfsSiteCostLowPriorityClass = 3,
        DfsGlobalLowPriorityClass = 4,
    };
#pragma endregion enums

#pragma region forward_declarations
    struct DFS_GET_PKT_ENTRY_STATE_ARG;
    struct DFS_INFO_1;
    struct DFS_INFO_100;
    struct DFS_INFO_101;
    struct DFS_INFO_102;
    struct DFS_INFO_103;
    struct DFS_INFO_104;
    struct DFS_INFO_105;
    struct DFS_INFO_106;
    struct DFS_INFO_107;
    struct DFS_INFO_150;
    struct DFS_INFO_2;
    struct DFS_INFO_200;
    struct DFS_INFO_3;
    struct DFS_INFO_300;
    struct DFS_INFO_4;
    struct DFS_INFO_5;
    struct DFS_INFO_50;
    struct DFS_INFO_6;
    struct DFS_INFO_7;
    struct DFS_INFO_8;
    struct DFS_INFO_9;
    struct DFS_SITELIST_INFO;
    struct DFS_SITENAME_INFO;
    struct DFS_STORAGE_INFO;
    struct DFS_STORAGE_INFO_1;
    struct DFS_SUPPORTED_NAMESPACE_VERSION_INFO;
    struct DFS_TARGET_PRIORITY;
#pragma endregion forward_declarations

#pragma region delegates
#pragma endregion delegates

}
namespace win32::_impl_
{
#pragma region guids
#pragma endregion guids

}
#endif
