// WARNING: Please don't edit this file. It was generated by C++/Win32 v0.0.0.1

#ifndef WIN32_Windows_Win32_WindowsFirewall_H
#define WIN32_Windows_Win32_WindowsFirewall_H
#include "win32/base.h"
static_assert(win32::check_version(CPPWIN32_VERSION, "0.0.0.1"), "Mismatched C++/Win32 headers.");
#define CPPWIN32_VERSION "0.0.0.1"
#include "win32/impl/Windows.Win32.WindowsFirewall.2.h"
WIN32_EXPORT namespace win32::Windows::Win32::WindowsFirewall
{
#pragma region methods
    inline int32_t NetworkIsolationSetupAppContainerBinaries(void* applicationContainerSid, uint16_t* packageFullName, uint16_t* packageFolder, uint16_t* displayName, Windows::Win32::SystemServices::BOOL bBinariesFullyComputed, uint16_t** binaries, uint32_t binariesCount)
    {
        auto win32_impl_result = WIN32_IMPL_NetworkIsolationSetupAppContainerBinaries(applicationContainerSid, packageFullName, packageFolder, displayName, bBinariesFullyComputed, binaries, binariesCount);
        return win32_impl_result;
    }
    inline uint32_t NetworkIsolationRegisterForAppContainerChanges(uint32_t flags, Windows::Win32::WindowsFirewall::PAC_CHANGES_CALLBACK_FN* callback, void* context, Windows::Win32::SystemServices::HANDLE* registrationObject)
    {
        auto win32_impl_result = WIN32_IMPL_NetworkIsolationRegisterForAppContainerChanges(flags, callback, context, registrationObject);
        return win32_impl_result;
    }
    inline uint32_t NetworkIsolationUnregisterForAppContainerChanges(Windows::Win32::SystemServices::HANDLE registrationObject)
    {
        auto win32_impl_result = WIN32_IMPL_NetworkIsolationUnregisterForAppContainerChanges(registrationObject);
        return win32_impl_result;
    }
    inline uint32_t NetworkIsolationFreeAppContainers(Windows::Win32::WindowsFirewall::INET_FIREWALL_APP_CONTAINER* pPublicAppCs)
    {
        auto win32_impl_result = WIN32_IMPL_NetworkIsolationFreeAppContainers(pPublicAppCs);
        return win32_impl_result;
    }
    inline uint32_t NetworkIsolationEnumAppContainers(uint32_t Flags, uint32_t* pdwNumPublicAppCs, Windows::Win32::WindowsFirewall::INET_FIREWALL_APP_CONTAINER** ppPublicAppCs)
    {
        auto win32_impl_result = WIN32_IMPL_NetworkIsolationEnumAppContainers(Flags, pdwNumPublicAppCs, ppPublicAppCs);
        return win32_impl_result;
    }
    inline uint32_t NetworkIsolationGetAppContainerConfig(uint32_t* pdwNumPublicAppCs, Windows::Win32::Security::SID_AND_ATTRIBUTES** appContainerSids)
    {
        auto win32_impl_result = WIN32_IMPL_NetworkIsolationGetAppContainerConfig(pdwNumPublicAppCs, appContainerSids);
        return win32_impl_result;
    }
    inline uint32_t NetworkIsolationSetAppContainerConfig(uint32_t dwNumPublicAppCs, Windows::Win32::Security::SID_AND_ATTRIBUTES* appContainerSids)
    {
        auto win32_impl_result = WIN32_IMPL_NetworkIsolationSetAppContainerConfig(dwNumPublicAppCs, appContainerSids);
        return win32_impl_result;
    }
    inline uint32_t NetworkIsolationDiagnoseConnectFailureAndGetInfo(uint16_t* wszServerName, Windows::Win32::WindowsFirewall::NETISO_ERROR_TYPE* netIsoError)
    {
        auto win32_impl_result = WIN32_IMPL_NetworkIsolationDiagnoseConnectFailureAndGetInfo(wszServerName, netIsoError);
        return win32_impl_result;
    }

#pragma endregion methods

}
#endif
