// WARNING: Please don't edit this file. It was generated by C++/Win32 v0.0.0.1

#ifndef WIN32_Windows_Win32_WindowsNetworkVirtualization_H
#define WIN32_Windows_Win32_WindowsNetworkVirtualization_H
#include "win32/base.h"
static_assert(win32::check_version(CPPWIN32_VERSION, "0.0.0.1"), "Mismatched C++/Win32 headers.");
#define CPPWIN32_VERSION "0.0.0.1"
#include "win32/impl/Windows.Win32.WindowsNetworkVirtualization.2.h"
WIN32_EXPORT namespace win32::Windows::Win32::WindowsNetworkVirtualization
{
#pragma region methods
    inline Windows::Win32::SystemServices::HANDLE WnvOpen()
    {
        auto win32_impl_result = WIN32_IMPL_WnvOpen();
        return win32_impl_result;
    }
    inline uint32_t WnvRequestNotification(Windows::Win32::SystemServices::HANDLE WnvHandle, Windows::Win32::WindowsNetworkVirtualization::WNV_NOTIFICATION_PARAM* NotificationParam, Windows::Win32::SystemServices::OVERLAPPED* Overlapped, uint32_t* BytesTransferred)
    {
        auto win32_impl_result = WIN32_IMPL_WnvRequestNotification(WnvHandle, NotificationParam, Overlapped, BytesTransferred);
        return win32_impl_result;
    }

#pragma endregion methods

}
#endif
