// WARNING: Please don't edit this file. It was generated by C++/Win32 v0.0.0.1

#ifndef WIN32_Windows_Win32_GamingDeviceInfo_H
#define WIN32_Windows_Win32_GamingDeviceInfo_H
#include "win32/base.h"
static_assert(win32::check_version(CPPWIN32_VERSION, "0.0.0.1"), "Mismatched C++/Win32 headers.");
#define CPPWIN32_VERSION "0.0.0.1"
#include "win32/impl/Windows.Win32.GamingDeviceInfo.2.h"
WIN32_EXPORT namespace win32::Windows::Win32::GamingDeviceInfo
{
#pragma region methods
    inline int32_t GetGamingDeviceModelInformation(Windows::Win32::GamingDeviceInfo::GAMING_DEVICE_MODEL_INFORMATION* information)
    {
        auto win32_impl_result = WIN32_IMPL_GetGamingDeviceModelInformation(information);
        return win32_impl_result;
    }

#pragma endregion methods

}
#endif
