// WARNING: Please don't edit this file. It was generated by C++/Win32 v0.0.0.1

#ifndef WIN32_Windows_Win32_WindowsMediaPlayer_H
#define WIN32_Windows_Win32_WindowsMediaPlayer_H
#include "win32/base.h"
static_assert(win32::check_version(CPPWIN32_VERSION, "0.0.0.1"), "Mismatched C++/Win32 headers.");
#define CPPWIN32_VERSION "0.0.0.1"
#include "win32/impl/Windows.Win32.WindowsMediaPlayer.2.h"
WIN32_EXPORT namespace win32::Windows::Win32::WindowsMediaPlayer
{
#pragma region methods

    inline constexpr float kfltTimedLevelMaximumFrequency = 0x1.5888p+14;
    inline constexpr float kfltTimedLevelMinimumFrequency = 0x1.4p+4;
    inline constexpr wchar_t const* g_szContentPartnerInfo_LoginState = L"LoginState";
    inline constexpr wchar_t const* g_szContentPartnerInfo_MediaPlayerAccountType = L"MediaPlayerAccountType";
    inline constexpr wchar_t const* g_szContentPartnerInfo_AccountType = L"AccountType";
    inline constexpr wchar_t const* g_szContentPartnerInfo_HasCachedCredentials = L"HasCachedCredentials";
    inline constexpr wchar_t const* g_szContentPartnerInfo_LicenseRefreshAdvanceWarning = L"LicenseRefreshAdvanceWarning";
    inline constexpr wchar_t const* g_szContentPartnerInfo_PurchasedTrackRequiresReDownload = L"PurchasedTrackRequiresReDownload";
    inline constexpr wchar_t const* g_szContentPartnerInfo_MaximumTrackPurchasePerPurchase = L"MaximumNumberOfTracksPerPurchase";
    inline constexpr wchar_t const* g_szContentPartnerInfo_AccountBalance = L"AccountBalance";
    inline constexpr wchar_t const* g_szContentPartnerInfo_UserName = L"UserName";
    inline constexpr wchar_t const* g_szMediaPlayerTask_Burn = L"Burn";
    inline constexpr wchar_t const* g_szMediaPlayerTask_Browse = L"Browse";
    inline constexpr wchar_t const* g_szMediaPlayerTask_Sync = L"Sync";
    inline constexpr wchar_t const* g_szItemInfo_PopupURL = L"Popup";
    inline constexpr wchar_t const* g_szItemInfo_AuthenticationSuccessURL = L"AuthenticationSuccessURL";
    inline constexpr wchar_t const* g_szItemInfo_LoginFailureURL = L"LoginFailureURL";
    inline constexpr wchar_t const* g_szItemInfo_HTMLViewURL = L"HTMLViewURL";
    inline constexpr wchar_t const* g_szItemInfo_PopupCaption = L"PopupCaption";
    inline constexpr wchar_t const* g_szItemInfo_ALTLoginURL = L"ALTLoginURL";
    inline constexpr wchar_t const* g_szItemInfo_ALTLoginCaption = L"ALTLoginCaption";
    inline constexpr wchar_t const* g_szItemInfo_ForgetPasswordURL = L"ForgotPassword";
    inline constexpr wchar_t const* g_szItemInfo_CreateAccountURL = L"CreateAccount";
    inline constexpr wchar_t const* g_szItemInfo_ArtistArtURL = L"ArtistArt";
    inline constexpr wchar_t const* g_szItemInfo_AlbumArtURL = L"AlbumArt";
    inline constexpr wchar_t const* g_szItemInfo_ListArtURL = L"ListArt";
    inline constexpr wchar_t const* g_szItemInfo_GenreArtURL = L"GenreArt";
    inline constexpr wchar_t const* g_szItemInfo_SubGenreArtURL = L"SubGenreArt";
    inline constexpr wchar_t const* g_szItemInfo_RadioArtURL = L"RadioArt";
    inline constexpr wchar_t const* g_szItemInfo_TreeListIconURL = L"CPListIDIcon";
    inline constexpr wchar_t const* g_szItemInfo_ErrorDescription = L"CPErrorDescription";
    inline constexpr wchar_t const* g_szItemInfo_ErrorURL = L"CPErrorURL";
    inline constexpr wchar_t const* g_szItemInfo_ErrorURLLinkText = L"CPErrorURLLinkText";
    inline constexpr wchar_t const* g_szUnknownLocation = L"UnknownLocation";
    inline constexpr wchar_t const* g_szRootLocation = L"RootLocation";
    inline constexpr wchar_t const* g_szFlyoutMenu = L"FlyoutMenu";
    inline constexpr wchar_t const* g_szOnlineStore = L"OnlineStore";
    inline constexpr wchar_t const* g_szVideoRecent = L"VideoRecent";
    inline constexpr wchar_t const* g_szVideoRoot = L"VideoRoot";
    inline constexpr wchar_t const* g_szCPListID = L"CPListID";
    inline constexpr wchar_t const* g_szAllCPListIDs = L"AllCPListIDs";
    inline constexpr wchar_t const* g_szCPTrackID = L"CPTrackID";
    inline constexpr wchar_t const* g_szAllCPTrackIDs = L"AllCPTrackIDs";
    inline constexpr wchar_t const* g_szCPArtistID = L"CPArtistID";
    inline constexpr wchar_t const* g_szAllCPArtistIDs = L"AllCPArtistIDs";
    inline constexpr wchar_t const* g_szCPAlbumID = L"CPAlbumID";
    inline constexpr wchar_t const* g_szAllCPAlbumIDs = L"AllCPAlbumIDs";
    inline constexpr wchar_t const* g_szCPGenreID = L"CPGenreID";
    inline constexpr wchar_t const* g_szAllCPGenreIDs = L"AllCPGenreIDs";
    inline constexpr wchar_t const* g_szCPAlbumSubGenreID = L"CPAlbumSubGenreID";
    inline constexpr wchar_t const* g_szAllCPAlbumSubGenreIDs = L"AllCPAlbumSubGenreIDs";
    inline constexpr wchar_t const* g_szReleaseDateYear = L"ReleaseDateYear";
    inline constexpr wchar_t const* g_szAllReleaseDateYears = L"AllReleaseDateYears";
    inline constexpr wchar_t const* g_szCPRadioID = L"CPRadioID";
    inline constexpr wchar_t const* g_szAllCPRadioIDs = L"AllCPRadioIDs";
    inline constexpr wchar_t const* g_szAuthor = L"Author";
    inline constexpr wchar_t const* g_szAllAuthors = L"AllAuthors";
    inline constexpr wchar_t const* g_szWMParentalRating = L"WMParentalRating";
    inline constexpr wchar_t const* g_szAllWMParentalRatings = L"AllWMParentalRatings";
    inline constexpr wchar_t const* g_szAllUserEffectiveRatingStarss = L"AllUserEffectiveRatingStarss";
    inline constexpr wchar_t const* g_szUserEffectiveRatingStars = L"UserEffectiveRatingStars";
    inline constexpr wchar_t const* g_szUserPlaylist = L"UserPlaylist";
    inline constexpr wchar_t const* g_szViewMode_Report = L"ViewModeReport";
    inline constexpr wchar_t const* g_szViewMode_Details = L"ViewModeDetails";
    inline constexpr wchar_t const* g_szViewMode_Icon = L"ViewModeIcon";
    inline constexpr wchar_t const* g_szViewMode_Tile = L"ViewModeTile";
    inline constexpr wchar_t const* g_szViewMode_OrderedList = L"ViewModeOrderedList";
    inline constexpr wchar_t const* g_szContentPrice_Unknown = L"PriceUnknown";
    inline constexpr wchar_t const* g_szContentPrice_CannotBuy = L"PriceCannotBuy";
    inline constexpr wchar_t const* g_szContentPrice_Free = L"PriceFree";
    inline constexpr wchar_t const* g_szRefreshLicensePlay = L"RefreshForPlay";
    inline constexpr wchar_t const* g_szRefreshLicenseBurn = L"RefreshForBurn";
    inline constexpr wchar_t const* g_szRefreshLicenseSync = L"RefreshForSync";
    inline constexpr wchar_t const* g_szVerifyPermissionSync = L"VerifyPermissionSync";
    inline constexpr wchar_t const* g_szStationEvent_Started = L"TrackStarted";
    inline constexpr wchar_t const* g_szStationEvent_Complete = L"TrackComplete";
    inline constexpr wchar_t const* g_szStationEvent_Skipped = L"TrackSkipped";
#pragma endregion methods

}
#endif
