// WARNING: Please don't edit this file. It was generated by C++/Win32 v0.0.0.1

#ifndef WIN32_Windows_Win32_OperationRecorder_H
#define WIN32_Windows_Win32_OperationRecorder_H
#include "win32/base.h"
static_assert(win32::check_version(CPPWIN32_VERSION, "0.0.0.1"), "Mismatched C++/Win32 headers.");
#define CPPWIN32_VERSION "0.0.0.1"
#include "win32/impl/Windows.Win32.OperationRecorder.2.h"
WIN32_EXPORT namespace win32::Windows::Win32::OperationRecorder
{
#pragma region methods
    inline Windows::Win32::SystemServices::BOOL OperationStart(Windows::Win32::OperationRecorder::OPERATION_START_PARAMETERS* OperationStartParams)
    {
        auto win32_impl_result = WIN32_IMPL_OperationStart(OperationStartParams);
        return win32_impl_result;
    }
    inline Windows::Win32::SystemServices::BOOL OperationEnd(Windows::Win32::OperationRecorder::OPERATION_END_PARAMETERS* OperationEndParams)
    {
        auto win32_impl_result = WIN32_IMPL_OperationEnd(OperationEndParams);
        return win32_impl_result;
    }

#pragma endregion methods

}
#endif
